### PR TITLE
Publish v2.3.0 of dalvany-image-panel

### PR DESCRIPTION
**Pull request by Dalvany**
Add new features (an overlay and an "underline") and fix some bugs.

### CODE REVIEW

**Comment by marcusolsson** [comment]
It looks like this plugin is unsigned. Since Grafana 7.3 we require all plugins to be signed in order to be published. For more information on how to sign your plugin, refer to [Sign a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/). Please sign your plugin and update the pull request 🙏

**Comment by Dalvany** [comment]
Hello @marcusolsson  thanks for the feedback, I'm trying to sign the plugin but I have an error :
```
$ grafana-toolkit plugin:sign
  Building manifest...
  Signing manifest...
  Error: Error signing manifest: Field is required: rootUrls
      at Object.<anonymous> (/home/runner/work/dalvany-image-panel/dalvany-image-panel/node_modules/@grafana/toolkit/src/plugins/manifest.js:165:31)
      at step (/home/runner/work/dalvany-image-panel/dalvany-image-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:140:27)
      at Object.throw (/home/runner/work/dalvany-image-panel/dalvany-image-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:121:57)
      at rejected (/home/runner/work/dalvany-image-panel/dalvany-image-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:112:69)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
It's the same error as #896.
When I opened my grafana cloud account and I tried to register the organization name it seems that I couldn't use `dalvany` (though there was a green tick when I fill the form, when I submitted, it stated that the slug was already taken, if I remember properly) and tried with `dalpass`.

**Comment by Dalvany** [comment]
I don't what I should do. If nobody's in `dalvany` organization, is it possible to transfer me there ? Or should I change the org part in the plugin ID ?

**Comment by Dalvany** [comment]
Hello @marcusolsson, is there something I can do about this error ?

**Comment by marcusolsson** [comment]
Check your email 🙂

**Comment by Dalvany** [comment]
Thank you ! I will sign the plugin asap

**Comment by Dalvany** [comment]
It worked fine, the plugin should be signed now. Thank you again !

**Comment by Dalvany** [comment]
Hello @marcusolsson, is there still something wrong with validation ? Local plugin validation doesn't seems to return any error.

**Comment by marcusolsson** [comment]
Looks good! Moving to Waiting for Review

**Comment by Dalvany** [comment]
Thank you !

**Comment by marcusolsson** [comment]
Tested the plugin and just wanted to check a couple of things:

1. Not sure how the overlay is supposed to work. I only get a colored rectangle, is this the intended behavior?
2. ... and 3. It doesn't seem like the underline text responds to the size option.

Screenshot 2021-07-06 at 17 21 19@2x

Let me know if I got the configuration wrong!

**Comment by Dalvany** [comment]
Hello @marcusolsson , thank you for reviewing.
The "overlay" is indeed supposed to show a colored rectangle depending on the field value selected. It's intended to behave like threshold if values are numbers, or behave like a "binding"  to a color if values are text. With your settings if you put a value below 10, the rectangle will be transparent ("base" value), 10 or above it will be gray unless you change the color.
In the following capture, the overlay is used to display temperature information (I don't remember what range for which color).
Overlay screenshot
I'll check and fix the size option.
Can I know what datasource you're using, it seems nice for testing !

**Comment by marcusolsson** [comment]
Thanks for the clarification! I'll await another update then!

The plugin I'm using is the [Static](https://grafana.com/grafana/plugins/marcusolsson-static-datasource/) data source, which I wrote specifically to test and develop panel plugins.

**Comment by Dalvany** [comment]
@marcusolsson font size should be fixed now.
Your datasource plugin is really usefull.

**Comment by marcusolsson** [comment]
Published! 🎉

**Comment by Dalvany** [comment]
Great, thank you !

**Pull request merged**
