### PR TITLE
Add Plotly panel plugin

### PR DESCRIPTION
**Pull request by ae3e**
Unlike the [natel-plotly-panel](https://github.com/NatelEnergy/grafana-plotly-panel), this plugin is not limited to specific types of charts. But, on the other hand, the user interface is really rough in order to let users to set all options available in Plotly.

### CODE REVIEW

**Comment by marcusolsson** [comment]
Thanks for considering contributing your plugin! Could you please add the production build to the commit (`yarn build && git add -f dist`) so I can start testing this plugin?

**Comment by ae3e** [comment]
The dist folder is added.

**Comment by marcusolsson** [comment]
We've been developing a [tool to validate plugins](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/). Would you mind fixing the issues reported for your plugin? You can enter the URL for this PR and press Enter.

**Comment by marcusolsson** [comment]
Also, could you consolidate the plugin versions to a single plugin object? Your pull request lists version `0.1.0` twice with two different commit SHAs.

**Comment by ae3e** [comment]
I fixed issues in my plugin with your validation tool and updated the repo.json file. I hope it will be fine... 😅

**Comment by marcusolsson** [comment]
I tried out your panel and have some feedback:

- The padding for the graph is pretty big. Not sure if that's something users can change.
- Would be nice if the code editors would expand to the full width of the panel editor. 

Screen Shot 2020-08-31 at 15 32 44

- `//Not working if variable is a Textbox : Maximum call stack size exceeded. Grafana bug?`

  This was indeed a bug that has been fixed in master, but hasn't yet made it to a release. I'd suggest you remove this comment for the release.

- "on Click Function" has a weird capitalization. Even if the callback is technically called `onClick`, maybe something more user-friendly could work, like "Click script", "Click handler, or something similar?

None are blockers, but let me know if you'd like to fix any of them before I publish.

**Comment by ae3e** [comment]
Thanks for your feedback, I followed all your suggestions and updated the version to my latest commit.
About the graph's margins, it can be change by the user in the layout settings. Nevertheless, I added some default values to have a prettier default chart : 
```json
"margin": {
    "t": 30,
    "b": 20
}
```

**Comment by marcusolsson** [comment]
Looks good! 

I'd be happy to publish this as soon as you've resolved the conflicts for this PR!

**Comment by ae3e** [comment]
Done!

**Comment by ae3e** [comment]
Hi,

I'm not really sure... Are you still waiting for changes from me or am I done (I don't see how I could solve conflict on repo.json file)?

**Comment by marcusolsson** [comment]
[Published](https://grafana.com/grafana/plugins/ae3e-plotly-panel)! 🎉

**Pull request closed without merging**
