### PR TITLE
Added HTML panel plugin

### PR DESCRIPTION
**Pull request by linar-jether**
a fork of the ajax plugin with support for iframes and template variables (Easily add panels from other systems)

### CODE REVIEW

**Comment by linar-jether** [comment]
Added some fixes and updated the commit #

**Comment by daniellee** [comment]
Thanks for sending this. The plugin looks fine both the metadata and your changes all work they way should (template variables and iframes). 

My only problem/question is: it is so similar to the Ajax panel plugin, could you not ask Ryan to merge these changes into his plugin?

If that is not possible for whatever reason then I can absolutely publish this.

**Comment by linar-jether** [comment]
No problem with merging back to Ryan's repo, created a fork mainly because of it not being only ajax and more general purpose way to display panels/content from external systems (i thought about making this more like the text/raw html panel but with passing time range as arguments)

Think it would be better to merge back to the ajax panel? 

Either way is fine by me

**Comment by daniellee** [comment]
Closing this as it looks like you are going to merge this into the Ajax panel instead.

Ref: https://github.com/jether-energy/grafana-html-panel/issues/1

**Comment by gesaleh** [comment]
is the merge done ?
i don't see any iframe option in ajax plugin 
and another question how you pass the parameter from,to height in my case they are not even passed to iframe

**Comment by linar-jether** [comment]
@gesaleh waiting for @ryantxu to do the merge

**Pull request closed without merging**
