### PR TITLE
Clickhouse Datasource plugin version update to 2.0.1

### PR DESCRIPTION
**Pull request by Slach**
# 2.0.1 (2020-06-19)
See release notes here: https://github.com/Vertamedia/clickhouse-grafana/releases/tag/2.0.1

## Fixes:
* fix golang alerts for $columns, $perSecond, $perSecondColumns macros https://github.com/Vertamedia/clickhouse-grafana/pull/200

# 2.0.0 (2020-06-17) 
See release notes here: https://github.com/Vertamedia/clickhouse-grafana/releases/tag/2.0.0

## Enhancements:
* compatibility with grafana 7.x, please use environment variable `GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=vertamedia-clickhouse-datasource` or `allow_loading_unsigned_plugins=vertamedia-clickhouse-datasource` in plugins section of `grafana.ini` https://github.com/Vertamedia/clickhouse-grafana/pull/192
* add grafana 7.x alerting support thanks to Brian Thai https://github.com/bmanth60
* add alias support to $perSecondColumns macro https://github.com/Vertamedia/clickhouse-grafana/pull/193
* Support `custom` variable type and empty values for `$conditionalTest` macro https://github.com/Vertamedia/clickhouse-grafana/pull/178
* add docker-compose.yaml to improve local development

## Fixes:
* fix AST for corner case when quotes escaped inside quotes https://github.com/Vertamedia/clickhouse-grafana/pull/123, https://github.com/Vertamedia/clickhouse-grafana/pull/195
* fix https://github.com/Vertamedia/clickhouse-grafana/issues/179,  add "Extrapolation" checkbox to Query Editor

### CODE REVIEW

**Comment by Slach** [comment]
@briangann could you look at this PR?

**Comment by daniellee** [comment]
@Slach I'm testing this now but getting the following error when testing alerting:

```
tsdb.HandleRequest() error rpc error: code = Unknown desc = unable to parse response json: { "meta": [ { "name": "t", "type": "UInt64" }, { "name": "groupArr", "type": "Array(Tuple(String, UInt64))" } ], "data": [ { "t": "1592404500000", "groupArr": [["test1","51"],["test2","3"]] }, { "t": "1592404800000", "groupArr": [["test1","22"],["test2","20"]] }, { "t": "1592405400000", "groupArr": [["test1","22"],["test2","20"]] } ], "rows": 3, "statistics": { "elapsed": 0.001250821, "rows_read": 8, "bytes_read": 224 } } : json: cannot unmarshal array into Go struct field ClickHouseResponse.Data of type string
```

It's a very simple query for a table with 3 columns:

```
$columns(Name, sum(Value) c)  FROM test.timeseries
```

Generated:
```
SELECT t, groupArray((Name, c)) AS groupArr FROM ( SELECT (intDiv(toUInt32(EventTime), 300) * 300) * 1000 AS t, Name, sum(Value) c FROM test.timeseries WHERE EventDate >= toDate(1592402523) AND EventTime >= toDateTime(1592402523) GROUP BY t, Name ORDER BY t, Name) GROUP BY t ORDER BY t
```


With the following result:

```
┌─────────────t─┬─groupArr────────────────────┐
│ 1592404500000 │ [('test1',51),('test2',3)]  │
│ 1592404800000 │ [('test1',22),('test2',20)] │
│ 1592405400000 │ [('test1',22),('test2',20)] │
└───────────────┴──────────────────────────┘
```

**Comment by Slach** [comment]
@daniellee thanks a lot for feedback, we miss this test case, I will try to fix it ASAP

**Comment by Slach** [comment]
@DanCech could you look this PR again?

**Comment by DanCech** [comment]
@Slach I think you mean @daniellee

**Comment by Slach** [comment]
@marcusolsson @briangann and @daniellee could you look to this PR?

**Comment by daniellee** [comment]
@Slach I just tested 2.0.1 with commit sha and I'm still seeing the same error for alerting. Am I testing the right version?

Same query as before:

image


This is the alert condition:

image

**Comment by Slach** [comment]
@daniellee could you see screenshot with error message?

**Comment by daniellee** [comment]
@Slach exact same as before:

```
{
  "firing": true,
  "state": "pending",
  "conditionEvals": " = true",
  "timeMs": "13.227ms",
  "error": "tsdb.HandleRequest() error rpc error: code = Unknown desc = unable to parse response json: {\n\t\"meta\":\n\t[\n\t\t{\n\t\t\t\"name\": \"t\",\n\t\t\t\"type\": \"UInt64\"\n\t\t},\n\t\t{\n\t\t\t\"name\": \"groupArr\",\n\t\t\t\"type\": \"Array(Tuple(String, UInt64))\"\n\t\t}\n\t],\n\n\t\"data\":\n\t[\n\t\t{\n\t\t\t\"t\": \"1593078300000\",\n\t\t\t\"groupArr\": [[\"test1\",\"20\"],[\"test2\",\"25\"]]\n\t\t}\n\t],\n\n\t\"rows\": 1,\n\n\t\"statistics\":\n\t{\n\t\t\"elapsed\": 0.002012242,\n\t\t\"rows_read\": 16,\n\t\t\"bytes_read\": 448\n\t}\n}\n: json: cannot unmarshal array into Go struct field ClickHouseResponse.Data of type string",
  "logs": [
    {
      "message": "Condition[0]: Query",
      "data": {
        "from": 1593077430655,
        "queries": [
          {
            "refId": "A",
            "model": {
              "compiledQuery": "SELECT t, groupArray((Name, c)) as groupArr FROM ( SELECT (intDiv(toUInt32(EventTime), 300) * 300) * 1000 as t, Name,  sum(Value) c FROM test.timeseries WHERE EventDate >= toDate(1497986913) AND EventTime >= toDateTime(1497986913) GROUP BY t, Name ORDER BY t, Name) GROUP BY t ORDER BY t ",
              "database": "test",
              "dateColDataType": "EventDate",
              "dateTimeColDataType": "EventTime",
              "dateTimeType": "DATETIME",
              "extrapolate": true,
              "format": "time_series",
              "formattedQuery": "$columns(Name, sum(Value) c)  FROM test.timeseries",
              "interval": "300s",
              "intervalFactor": 1,
              "query": "$columns(Name, sum(Value) c)  FROM test.timeseries",
              "rawQuery": "SELECT t, groupArray((Name, c)) AS groupArr FROM ( SELECT (intDiv(toUInt32(EventTime), 300) * 300) * 1000 AS t, Name, sum(Value) c FROM test.timeseries WHERE EventDate >= toDate(1593074723) AND EventTime >= toDateTime(1593074723) GROUP BY t, Name ORDER BY t, Name) GROUP BY t ORDER BY t",
              "refId": "A",
              "resultFormat": "time_series",
              "round": "0s",
              "table": "timeseries",
              "tags": [],
              "targetLists": [
                [
                  {
                    "params": [
                      "Value"
                    ],
                    "type": "field"
                  },
                  {
                    "params": [],
                    "type": "min"
                  }
                ]
              ]
            },
            "datasource": {
              "id": 43,
              "name": "Clickhouse"
            },
            "maxDataPoints": 0,
            "intervalMs": 0
          }
        ],
        "to": 1593078330655
      }
    }
  ]
}
```

**Comment by Slach** [comment]
@daniellee  could you share
```
SHOW CREATE TABLE test.timeseries;
```

and maybe share some data samples?

I can't reproduce any alerts error when I test the latest master branch and when test 2.0.1 from https://github.com/Vertamedia/clickhouse-grafana/tree/7b73be0ab0dbc2db2bb3897b57a68af667a5eee1/dist

**Comment by daniellee** [comment]
@Slach I tested again with 2.0.1 to make sure I was still seeing the error and still seeing the same error when I click the `Test rule` button. It's a very simple table:

```
SHOW CREATE TABLE test.timeseries

┌─statement──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE test.timeseries
(
    `Name` String,
    `EventDate` Date,
    `EventTime` DateTime,
    `Value` UInt64
)
ENGINE = Memory │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

An example of inserting data:

`insert into timeseries values ('test1', toDate(now()), now(), 21);`

**Comment by daniellee** [comment]
I also tested creating a new dashboard and followed the wizard and chose a database, table, and datetime column. I got exactly the same query as before and the same error when testing the alert rule.

**Comment by Slach** [comment]
@daniellee 
Please, help me reproduce your error
or confirm your command
```
ls -la clickhouse-grafana/disk/vertamedia-clickhouse-plugin_linux_amd64
```
return something like this with the same size  15584589 
```
-rwx------+ 1 Slach Отсутствует 15584589 Jul  5 14:08 vertamedia-clickhouse-plugin_linux_amd64 
```

could you reproduce your error and follow the next steps:

```
git clone https://github.com/Vertamedia/clickhouse-grafana
cd clickhouse-grafana
docker-compose up --no-deps -d grafana clickhouse
```
open http://localhost:3000/ -> auth admin/admin -> dashboards -> Test Alerts Dashboard -> Edit panel "Test alerts" -> switch to Alerts tab -> click "Test rule"

I create test table as you described  (but change `ENGINE=Memory()` to `ENGINE=MergreTree()`
when I click to "Test Rule" button I see the following picture:
image

and JSON
```json
{
  "firing": true,
  "state": "pending",
  "conditionEvals": "true = true",
  "timeMs": "12.182ms",
  "matches": [
    {
      "metric": "test1",
      "value": 21
    }
  ],
  "logs": [
    {
      "message": "Condition[0]: Query",
      "data": {
        "from": 1593940054343,
        "queries": [
          {
            "refId": "A",
            "model": {
              "database": "default",
              "dateColDataType": "EventDate",
              "dateLoading": false,
              "dateTimeColDataType": "EventTime",
              "dateTimeType": "DATETIME",
              "datetimeLoading": false,
              "extrapolate": true,
              "format": "time_series",
              "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
              "interval": "5m",
              "intervalFactor": 1,
              "query": "$columns(Name, sum(Value) c) FROM $table",
              "rawQuery": "SELECT t, groupArray((Name, c)) AS groupArr FROM ( SELECT (intDiv(toUInt32(EventTime), 300) * 300) * 1000 AS t, Name, sum(Value) c FROM default.test_alerts WHERE EventDate >= toDate(1593939447) AND EventTime >= toDateTime(1593939447) GROUP BY t, Name ORDER BY t, Name) GROUP BY t ORDER BY t",
              "refId": "A",
              "round": "0s",
              "table": "test_alerts",
              "tableLoading": false
            },
            "datasource": {
              "id": 1,
              "name": "clickhouse"
            },
            "maxDataPoints": 0,
            "intervalMs": 0
          }
        ],
        "to": 1593940354343
      }
    },
    {
      "message": "Condition[0]: Query Result",
      "data": {
        "meta": [
          {
            "Name": "t",
            "Type": "UInt64"
          },
          {
            "Name": "groupArr",
            "Type": "Array(Tuple(String, UInt64))"
          }
        ],
        "series": [
          {
            "name": "test1",
            "points": [
              [
                21,
                1593939900000
              ]
            ]
          }
        ]
      }
    },
    {
      "message": "Condition[0]: Eval: true, Metric: test1, Value: 21.000",
      "data": null
    }
  ]
}
```

when I click to "State history" I see the following picture:
image

**Comment by daniellee** [comment]
Thanks for the tip about examining the binary. I must have missed an error when upgrading from 2.0.0 to 2.0.1 (due to the binary being in use). The Go binary was an older version. 

Two observations:
- The documentation needs to be updated: [Why no alerts support](https://github.com/Vertamedia/clickhouse-grafana#faq)
- The plugin only supports alerting for Linux distributions and not Windows or MacOS

Thanks for being so patient and digging into this - I should have found the problem earlier.

Merged and published.

**Pull request merged**
