### PR TITLE
Update pierosavi-imageit-panel to v1

### PR DESCRIPTION
**Pull request by pierosavi**
Rewritten plugin in react
Release is unsigned as suggested via ticket

### CODE REVIEW

**Comment by pierosavi** [comment]
Weird, it doesn't find the release file but it looks fine to me

**Comment by marcusolsson** [comment]
Nice! 🎉 

It seems like the release is still in draft state. Could you make sure that it's been published? Once the release has been published, you can right-click and copy the address to the plugin zip file, and update this pull request.

Also, since this plugin is already available on the marketplace, we've gone ahead and configure a signature level for you already. You should be able to sign the plugin now. Let me know if you have any issue doing so!

**Comment by pierosavi** [comment]
@marcusolsson Thanks! Trying to sign the plugin I'm getting `Error signing manifest: Field is required: rootUrls`, is it possible that the signature level was configured incorrectly?

**Comment by marcusolsson** [comment]
Hm. I've confirmed that we've configured a community signature level for `pierosavi-imageit-panel`. Do you have multiple Grafana.com accounts perhaps? If so, can you confirm that the API key was created in the the `pierosavi` org?

**Comment by pierosavi** [comment]
Ah that's the problem: even though my grafana username is pierosavi my org id is psavi for some reason
Is it possible to connect pierosavi org to my user?

**Comment by pierosavi** [comment]
@marcusolsson Thanks again! Updated the url, working fine now :)

**Comment by berilslv** [comment]
Still in plugin page imageit highest version is 0.1.3 . Hope newest version will appear soon! :)

**Comment by marcusolsson** [comment]
Published! 🎉

**Comment by frdve** [comment]
I'm sorry for asking it again, but I don't see the publish in my Grafana instance and on the plugin website.  The highest version is still 0.1.3.  
Does it take a long time to propagate to the plugin repo?
Thanks!

**Comment by marcusolsson** [comment]
The required Grafana version for this plugin is `7.0.x`, which means that grafana-cli will only install the plugin for the following Grafana versions:

- 7.0.0
- 7.0.1
- 7.0.2
- 7.0.3
- 7.0.4
- 7.0.5

If you want to try the plugin for another version of Grafana, you can download the plugin manually and unzip it to your plugins directory.

**Comment by pierosavi** [comment]
`7.0.x` is a mistake, I'll update v1.0.1 with that in mind

But it's true that 1.0.0 doesn't seem to be online yet.
[Plugin Versions](https://grafana.com/api/plugins/pierosavi-imageit-panel/versions)

**Comment by marcusolsson** [comment]
Weird. I've uploaded it again and verified it's there now. I'll make sure to publish 1.0.1 as soon as it's available.

**Pull request merged**
