### PR TITLE
Update clickhouse-grafana to 1.9.2

### PR DESCRIPTION
**Pull request by gimm3fuel**
Please, see release updates https://github.com/Vertamedia/clickhouse-grafana/releases/tag/1.9.2

## Fixes:
* Compatibility fix to support grafana 6.4.x
* Ad Hoc Filters fix
* $conditionalTest ALL value option fix

### CODE REVIEW

**Comment by Knot3n** [comment]
Hello,

can someone review and merge this update please?

Many users are using the clickhouse plugin and the whole monitoring is not working right now.

Thank you

**Comment by alex-zaitsev** [comment]
@daniellee ^, please

**Comment by daniellee** [comment]
@gimm3fuel the plugin version is incorrect, it is 1.9.0 instead of 1.9.2: https://github.com/Vertamedia/clickhouse-grafana/blob/1.9.2/dist/plugin.json#L27

**Comment by meob** [comment]
Works as expected!
Thanks

**Pull request closed without merging**
