### PR TITLE
Update flant-statusmap-panel version to 0.3.1

### PR DESCRIPTION
**Pull request by diafour**
- Tooltip freeze on click
- Show URLs in tooltip
- Pagination controls
- Fix tooltip and null buckets
- Fix display for 6.7+, 7.0+

### CODE REVIEW

**Comment by diafour** [comment]
The plugin still uses angular.

**Comment by diafour** [comment]
Update to 0.3.1 to work with recent Grafana 7.1.0.

**Comment by marcusolsson** [comment]
Hi @diafour! You're removing previous versions in your pull request. Are you asking for these plugins to be unpublished?

Also, the [plugin validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/) reports a few issues. Would you mind addressing these while we review your plugin? You can enter `flant/grafana-statusmap@<commitsha>` to validate a specific commit.

**Comment by diafour** [comment]
@marcusolsson Wow! I never see that download statistics before. I'll revert the `0.2.0` version.

Is it ok to have a deprecated field and a new one in "dependencies" section in plugin.json?

```
  "dependencies": {
    "grafanaDependency": ">=5.4.3",
    "grafanaVersion": "5.4.3 6.x.x 7.x.x",
    "plugins": [ ]
  }
```

**Comment by marcusolsson** [comment]
Yes, you can put both in there! `grafanaVersion` is only used for display (and not much else), while `grafanaDependency` will have stricter semver validation. It's safe to use both.

**Comment by marcusolsson** [comment]
> Wow! I never see that download statistics before.

Congrats to 2M+ downloads! 🎉

**Comment by diafour** [comment]
@marcusolsson I've made proposed changes. Also, previous versions are restored.

**Comment by marcusolsson** [comment]
[Published](https://grafana.com/grafana/plugins/flant-statusmap-panel?version=0.3.2)! Thank you for contributing! ❤️

**Pull request merged**
