### PR TITLE
Adding Vertica datasource 0.1.0

### PR DESCRIPTION
**Pull request by huebnerr**
Initial commit of Micro Focus Vertica 0.1.0 Datasource

### CODE REVIEW

**Comment by huebnerr** [comment]
Fixed warning of mismatched version # per CI lint warning.

**Comment by daniellee** [comment]
@huebnerr I'm reviewing now - any tips on how to test this properly? Do you have a test environment? I'll try first with [docker](https://hub.docker.com/r/dataplatform/docker-vertica/) (or maybe [this](https://github.com/jbfavre/docker-vertica)).

**Comment by daniellee** [comment]
No worries - got a vertica db up and running quite easily.

**Comment by huebnerr** [comment]
Thank you, @daniellee! You can use the 'jbfavre/vertica' docker image as:
'docker run -d -p 5433:5433 jbfavre/vertica' as a quick get-up-and-go.

**Comment by huebnerr** [comment]
If there are any questions I can answer, please let me know. Thanks again.

**Comment by huebnerr** [comment]
Updated with latest vertica-sql-go driver.

**Comment by huebnerr** [comment]
@daniellee, please let me know if there is anything I can do to facilitate.

**Comment by briangann** [comment]
@huebnerr can you rebase and fix the merge conflict with repo.json?

**Comment by huebnerr** [comment]
Thank you, @briangann. I've updated.

**Comment by huebnerr** [comment]
Any update would be hugely appreciated.

**Comment by huebnerr** [comment]
@daniellee, is there any update? The original PR was on Aug 9 and we really need forward movement on this to user requests.

**Comment by huebnerr** [comment]
@alexanderzobnin Maybe you could help?

**Comment by huebnerr** [comment]
@briangann with all of the updates, would love to finally get feedback on this. Have repeatedly resolved and requested since Aug 8.

**Comment by briangann** [comment]
looking at it now

**Comment by briangann** [comment]
going to merge this with another PR.

The only warning that came back form the PR was
```
Warning
The README.md file contains HTML tags: <i>,</i>
```

**Comment by briangann** [comment]
merged and published under PR #538

**Comment by huebnerr** [comment]
Thank you.

On Dec 23, 2019 10:35 PM, Brian Gann <notifications@github.com> wrote:

looking at it now

**Comment by huebnerr** [comment]
Thank you so much for this, Brian!

On Dec 23, 2019 10:47 PM, Brian Gann <notifications@github.com> wrote:

going to merge this with another PR.

The only warning that came back form the PR was

Warning
The README.md file contains HTML tags: <i>,</i>

**Pull request closed without merging**
