### PR TITLE
update natel discrete-panel

### PR DESCRIPTION
**Pull request by ryantxu**

### CODE REVIEW

**Comment by daniellee** [comment]
Can you update the version number in the plugin.json file to 0.0.5 as well: https://github.com/NatelEnergy/grafana-discrete-panel/blob/master/dist/plugin.json#L29

**Comment by ryantxu** [comment]
dooh.  I just fixed it so i can't make that mistake again

the new hash is:
https://github.com/NatelEnergy/grafana-discrete-panel/commit/3b89c28b538fd5c12fe389ba191e93eec67cdd0b

i can update the pull request later if you need one

thanks!

**Comment by ryantxu** [comment]
ok, should be ready to go!

**Comment by daniellee** [comment]
Merged and published!

**Pull request merged**
