### PR TITLE
plugin: diagram - adds v1.6.4 and v1.7.1

### PR DESCRIPTION
**Pull request by jdbranham**
This is my first v7 plugin - it works locally =]  

I used the plugin starter code, so hoping I've got packaged correctly.

### CODE REVIEW

**Comment by marcusolsson** [comment]
Nice! 🎉 

I'll test this out later today. In the meantime, could you address the issues reported by the [plugin validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app)?

[grafana-7x](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/?url=https://github.com/jdbranham/grafana-diagram/tree/grafana-7x)
[grafana-6x](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/?url=https://github.com/jdbranham/grafana-diagram/tree/grafana-6x)

The warnings are not critical but improves the overall quality of your plugin.

**Comment by marcusolsson** [comment]
I tried the 7.x branch, and I'm having some trouble (I think).

- The value from the time series doesn't seem to show in the nodes (as indicated by the screenshot in the README).
- The min height and width don't seem to have any effect on the visualization.

Any idea what I'm doing wrong?

Screen Shot 2020-09-29 at 11 19 41

**Comment by jdbranham** [comment]
Thanks @marcusolsson 
I've fixed all the validation errors. 
Let me know if you still have trouble with the new version [which browser are you using?]

**Comment by jdbranham** [comment]
Also, should we still include the `dist` folder with the compiled code?

**Comment by marcusolsson** [comment]
Published! 🎉

**Pull request merged**
