### PR TITLE
Add TencentCloud Monitor Grafana App Plugin

### PR DESCRIPTION
**Pull request by jamesxwang**
Hi @marcusolsson, on behalf of [Tencent Cloud](https://intl.cloud.tencent.com/), we would like to add our `TencentCloud Monitor Grafana App` to Grafana Plugins. (plugin id: `tencentcloud-monitor-app`)

Please note that the previous [Pull Request](https://github.com/grafana/grafana-plugin-repository/pull/430) is now deprecated and you are free to close in anytime.

The SecretKey/SecretId credentials for Grafana testing this plugin will send to you via email.

Please let me know if you have any comments and we may change it.

Thank you,
James Wang @ Tencent Cloud

### CODE REVIEW

**Comment by marcusolsson** [comment]
Hi @jamesxwang,

Could you please update your PR to the [following format](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson):

```
{
  "id": "briangann-gauge-panel",
  "type": "panel",
  "url": "https://github.com/briangann/grafana-gauge-panel",
  "versions": [
    {
      "version": "0.0.8",
      "url": "https://github.com/briangann/grafana-gauge-panel",
      "download": {
        "any": {
          "url": "https://github.com/briangann/grafana-gauge-panel/releases/download/v0.0.8/briangann-gauge-panel-0.0.8.zip",
          "md5": "782c973460f330287b7efca5486aa015"
        }
      }
    }
  ]
}
```

Once you've updated your PR, make sure you paste the URL to the ZIP archive into the [plugin validator](https://plugin-validator.grafana.net/) to make sure it's ready for review.

**Comment by jamesxwang** [comment]
> Hi @jamesxwang,
> 
> Could you please update your PR to the [following format](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson):
> 
> ```
> {
>   "id": "briangann-gauge-panel",
>   "type": "panel",
>   "url": "https://github.com/briangann/grafana-gauge-panel",
>   "versions": [
>     {
>       "version": "0.0.8",
>       "url": "https://github.com/briangann/grafana-gauge-panel",
>       "download": {
>         "any": {
>           "url": "https://github.com/briangann/grafana-gauge-panel/releases/download/v0.0.8/briangann-gauge-panel-0.0.8.zip",
>           "md5": "782c973460f330287b7efca5486aa015"
>         }
>       }
>     }
>   ]
> }
> ```
> 
> Once you've updated your PR, make sure you paste the URL to the ZIP archive into the [plugin validator](https://plugin-validator.grafana.net/) to make sure it's ready for review.

Hi @marcusolsson, if I don't want to publish a release 1.5.0, how can I get the zip file URL? Thanks

**Comment by jamesxwang** [comment]
Hi, I have released an alpha version with the production zip.
Please tell me if there are any other ways to do this.
Thanks.

**Comment by marcusolsson** [comment]
The plugin needs to packaged according to the instructions on [Package a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/). 

Once you've packaged the plugin, could you maybe add the ZIP file as a release asset for the [1.5.0-alpha](https://github.com/TencentCloud/tencentcloud-monitor-grafana-app/releases/tag/1.5.0-alpha) release?

**Comment by jamesxwang** [comment]
Ready for review.
image

**Comment by jamesxwang** [comment]
Hi @marcusolsson, our team eventually decided to give the compatibility and embrace the change.
We have added a golang backend, see [TencentCloud/tencentcloud-monitor-app PR#49](https://github.com/TencentCloud/tencentcloud-monitor-grafana-app/pull/49/commits/1562ac9c17da9f84155ff98fd637af50468fff2a), for secretId/secretKey issues.

Please review this updated PR #907 and tell us if there are any other new issues upcoming.

If not, I will update the version from alpha to 2.0.0 and re-commit with the correct version.

Cheers.

**Comment by jamesxwang** [comment]
image

**Comment by jamesxwang** [comment]
Hi, we would like to update a new version [2.0.1](https://github.com/TencentCloud/tencentcloud-monitor-grafana-app/releases/tag/2.0.1 ) for bugfixes.

image

Thanks

**Comment by marcusolsson** [comment]
Published! 🎉

**Pull request merged**
