### PR TITLE
Add the OpenNMS datasource to the list of available plugins.

### PR DESCRIPTION
**Pull request by j-white**
Great job on the plugin architecture! I'm happy I don't have to maintain my own RPMs anymore :)

### CODE REVIEW

**Comment by DanCech** [comment]
@j-white this looks good, to publish on grafana.net you will need to update the plugin id in your plugin.json as the `grafana-*` namespace is reserved.  You're welcome to use the `opennms-datasource` id to match what's in the PR.  I'll give you a hand setting up the opennms org on grafana.net as that's still a somewhat manual process.

Your readme.md and any screenshots listed in your plugin.json will also be used to populate the plugin page on grafana.net, so you may want to flesh those out a bit.

**Comment by j-white** [comment]
Thanks for the feedback @DanCech.

I've updated the id, fleshed out the readme and added a few screenshots.

**Comment by DanCech** [comment]
Looking great!

**Comment by DanCech** [comment]
@j-white the plugin is now live at https://grafana.net/plugins/opennms-datasource

**Pull request merged**
