### PR TITLE
OpenNMS Helm 5.0.3

### PR DESCRIPTION
**Pull request by RangerRick**
This release contains significant documentation updates, as well as a few bug fixes including Grafana 6.7 support.
It also bumps the Grafana provided by our Docker images to `6.7.2`.

* Document how to use the filter panel (Issue [HELM-206](http://issues.opennms.org/browse/HELM-206))
* Document how to use the entity data-source (Issue [HELM-207](http://issues.opennms.org/browse/HELM-207))
* Publish build artifacts with CircleCI to Cloudsmith (Issue [HELM-214](http://issues.opennms.org/browse/HELM-214))
* Convert docs from Asciibinder to Antora (Issue [HELM-217](http://issues.opennms.org/browse/HELM-217))
* Integrate Antora documentation into CircleCI (Issue [HELM-218](http://issues.opennms.org/browse/HELM-218))
* Sign RPM and DEB packages with GPG key (Issue [HELM-222](http://issues.opennms.org/browse/HELM-222))
* Some filter could be documented (Issue [HELM-227](http://issues.opennms.org/browse/HELM-227))
* Cannot add an Alarm Table widget when using Grafana 6.6.x (Issue [HELM-229](http://issues.opennms.org/browse/HELM-229))
* Support Grafana 6.7.x for our Helm plugin (Issue [HELM-232](http://issues.opennms.org/browse/HELM-232))

### CODE REVIEW

**Comment by daniellee** [comment]
Sorry for the delay with testing. With Grafana 7.0, I am getting a crash on the alarm table panel when trying to change the query:

```
An unexpected error happened
Details
TypeError: this.dashboard.isTimezoneUtc is not a function

    in AppContainer (created by HotExportedConnect(DashboardPage))
    in HotExportedConnect(DashboardPage) (created by LoadableComponent)
    in LoadableComponent (created by Component)
    in Component (created by Component)
    in ModalsProvider (created by Component)
    in Component (created by Component)
    in ThemeProvider (created by Component)
    in Component (created by ConfigProvider)
    in ConfigProvider
    in ErrorBoundary (created by ErrorBoundaryAlert)
    in ErrorBoundaryAlert
    in Provider
```

**Comment by marcusolsson** [comment]
Hi @RangerRick! Could you fix the issues reported by [this plugin validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/) (enter the URL to this pull request)?

**Comment by RangerRick** [comment]
@marcusolsson I'm hoping to get a 5.0.3 update out this week, which fixes Grafana 6.7; I can make this adjustment while I'm at it.  While I'm changing these things, is there a way to indicate that we work with 6 but don't yet work with 7?  I've got fixes incoming but we do some complicated things with our plugin that keep breaking as the glue between angular and react keeps changing.

**Comment by marcusolsson** [comment]
`grafanaVersion` has been deprecated in favor of `grafanaDependency` which follows the [node-semver](https://github.com/npm/node-semver) format. Specifically, we accept whatever [semver.validRange](https://github.com/grafana/grafana-com/blob/5ee09cbcbd0053b9a34445bcfbd72fbb433fd626/api/routes/plugin-versions.js#L35) accepts.

I.e. something like `>=6.3.0 <7.0.0` should be fine.

**Comment by RangerRick** [comment]
Bumped to helm 5.0.3 with the changes you suggested and more bugfixes.  Release notes:

---

This release does not yet fix Grafana 7 support (it's complicated...) but it fixes a few more bugs while
we work on Grafana 7 support.

Also note, the docs that used to be included in the archive are now published at https://docs.opennms.com/ -- our
future home for all OpenNMS documentation.

* Make Helm docs publicly available (Issue [HELM-221](http://issues.opennms.org/browse/HELM-221))
* "How to configure the data sources in Grafana" docs are missing (Issue [HELM-231](http://issues.opennms.org/browse/HELM-231))
* Enhance HELM documentation (Issue [HELM-240](http://issues.opennms.org/browse/HELM-240))
* Add expression examples (Issue [HELM-241](http://issues.opennms.org/browse/HELM-241))
* JEXL expressions (Issue [HELM-242](http://issues.opennms.org/browse/HELM-242))
* Cannot see list of nodes and resources when editing a panel. (Issue [HELM-243](http://issues.opennms.org/browse/HELM-243))
* update requirements (Issue [HELM-251](http://issues.opennms.org/browse/HELM-251))

**Comment by RangerRick** [comment]
@marcusolsson @daniellee let me know if you need anything else from me.

Thanks!  Sorry about the slow response time, other things got in the way.

**Comment by opennms-bamboo** [comment]
PR updated to include OpenNMS Helm 6:

OpenNMS Helm 6.0.0
================

OpenNMS Helm now supports Grafana 7, and has dropped support for versions older than 7.

* the `nodeResources()` function has been enhanced to support displaying the resource label (Issue [HELM-95](https://issues.opennms.org/browse/HELM-95))
* the Filter and Alarm Table panels have been updated to work with Grafana 7 (Issue [HELM-247](https://issues.opennms.org/browse/HELM-247))

**Comment by RangerRick** [comment]
> Hi @RangerRick! Could you fix the issues reported by [this plugin validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/) (enter the URL to this pull request)?

@marcusolsson I just tried the validator again and now it complains I have 2 versions in here. What's the best way to move this forward?  It's still useful to have 5.0.3 in the official repository list, but 6.0.0 is now the latest.  Should I make a separate PR for 6.0.0?  Should it depend on this one, or pretend it doesn't exist?

**Pull request closed without merging**
