### PR TITLE
grafadruid-druid-datasource v1.2.0

### PR DESCRIPTION
**Pull request by jbguerraz**
See https://github.com/grafadruid/druid-grafana/blob/master/CONTRIBUTE.md for setup.
You're also welcome on https://join.slack.com/t/grafadruid/shared_invite/zt-kxaiq5gm-c6akAiceMzgHvUBV~KXeiA for support :)
Thank you a lot!

### CODE REVIEW

**Comment by davidnewhall** [comment]
Dear Grafana,

What do we need to do to merge this? As an Enterprise user, I need this feature.

**Comment by MathieuEtchepare** [comment]
Hello Grafana,

When do you plan on reviewing this merge? I would really use this awesome feature for my company too.
Thanks

**Comment by marcusolsson** [comment]
I had some trouble creating test data for this when I first reviewed it, but I can see that more instructions have been added to the README. I'll give this another go this week.

**Comment by marcusolsson** [comment]
Hi, I've successfully been able to run the queries against the wiki data set, and it indeed looks like it working as intended.

I don't have much feedback other than maybe the query editor could make better use of horizontal space. But there's nothing that's blocking the plugin from being published.

Screenshot 2021-04-30 at 10 34 32@2x

I have configured the plugin to be signed as a Community plugin. Please sign the plugin using the instructions on [Sign a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/). Make sure that you generate the API key from the `grafadruid` account.

Once you're done, please update this PR with the URL and MD5 for the signed version.

**Comment by jbguerraz** [comment]
@marcusolsson tadam! here is the 1.2.0 version, signed :) Thank you for your support!

**Comment by marcusolsson** [comment]
Nice! 💪 I've tested the plugin it seems to be working as intended. 

The only comment I have is regarding the README (it looks great btw!). Unfortunately, due to limitations in how we currently host plugins on grafana.com, we don't support relative links. This means that while the images looks great on GitHub, they won't be displayed on grafana.com.

The best workaround I've found is to use absolute permalinks for any images in the README.

Let me know how you wish to proceed!

**Comment by jbguerraz** [comment]
I've re-released that same version 1.2.0 with that little change (absolute permalinks). Should be ok!
Thank you :+1:

**Comment by marcusolsson** [comment]
Got an error while publishing this:

```
Could not find image file in zip: grafadruid-druid-datasource/img/screenshot-datasource.png
```

Looks like one of the screenshots have been removed/renamed? Could you update the [path](https://github.com/grafadruid/druid-grafana/blob/5bfcd20d031d4a67ffc6ea51f0b0ecc9a73ccb36/src/plugin.json#L31)?

So close now! 🙏

**Comment by marcusolsson** [comment]
Published! 🎉 Please allow for a few minutes before it becomes available on grafana.com.

**Comment by jbguerraz** [comment]
@marcusolsson sorry! I had totally forgot about that screenshots section.

**Comment by jbguerraz** [comment]
Thank you! :100:

**Comment by marcusolsson** [comment]
Thanks for contributing to Grafana! 🙏

**Pull request merged**
