### PR TITLE
Update Organisations panel

### PR DESCRIPTION
**Pull request by timyllym**
Updated Organisations panel to work with Grafana 5.0

### CODE REVIEW

**Comment by timyllym** [comment]
Hi @daniellee, thanks, I forgot to recompile the dist version. That's now fixed.

**Comment by daniellee** [comment]
@timyllym just noticed now that the css in the panel is affecting the Grafana .btn class:

https://github.com/digiapulssi/grafana-organisations-panel/blob/master/src/style.scss#L11-L20

image

**Comment by timyllym** [comment]
Ok, I'll change the class name to something else.

**Comment by timyllym** [comment]
I just created a new PR.

**Pull request merged**
