### PR TITLE
Add Cloudflare Grafana App 0.1.1

### PR DESCRIPTION
**Pull request by vavrusa**
Hey, I'd like to add Cloudflare Grafana App to the repo.

### CODE REVIEW

**Comment by DanCech** [comment]
Thanks for the PR!  The version in the referenced commit is 0.1.0 so you'll need to update this PR to match that or update the version in plugin.json and update the PR with the new commit hash.

https://github.com/cloudflare/cloudflare-grafana-app/blob/master/dist/plugin.json#L39

**Comment by vavrusa** [comment]
Ok, updated.

**Comment by DanCech** [comment]
The plugin is now live at https://grafana.net/plugins/cloudflare-app

Whenever you're ready to publish a new version please add it to the version list and open a new PR.

Thanks for being part of the Grafana community!

**Comment by vavrusa** [comment]
Thanks a lot! The logo renders weirdly squished (while it's great in Grafana itself), should I rather use a square format or is it a UI bug?

**Comment by DanCech** [comment]
You'll want to use a square logo, @mattttt actually pushed you a PR with a couple of square ones.

**Pull request merged**
