### PR TITLE
New panel plugin Flowcharting

### PR DESCRIPTION
**Pull request by algenty**
## 0.1
 - Display Graph
 - inspect tab
## 0.2
 - Display graph through xml definition
 - Calibrate display (scale, center,background)
 - inspect graph to test states and shape
 - Mapping values and colors (use stroke in color options for arrows instead fill)
 - String type added with range or value mapping.
 - Date type added
 - multi rules with expand/collapes for better displa, possibility to reorg rules
/!\ Only dark theme is supported at this time

### CODE REVIEW

**Comment by algenty** [comment]
have news ?

**Comment by alexanderzobnin** [comment]
@algenty Thanks for the contribution and publishing new plugin! I noticed a version mismatch between a repo.json and actual `plugin.json`:
```
Version in repo.json (0.2.0) doesn't match plugin.json (0.0.1)
```
Please, fix it and update this PR.
Also, I've found another PR (#397), it seems, it's wrong, so closing that one.

**Comment by alexanderzobnin** [comment]
Otherwise, looks very good for the beta, so I can merge it after the version fix.

**Comment by algenty** [comment]
yes, i forget plugin.json,i'll fix it

**Comment by alexanderzobnin** [comment]
@algenty still the same:
```
Warning
Version in repo.json (0.2.0) doesn't match plugin.json (0.0.1)
```
Are you sure you build a plugin (maybe you've just updated plugin.json in src/)?

**Comment by algenty** [comment]
Can i suggest 0.3.0 instead 0.2.0 ?

**Comment by algenty** [comment]
plugin for 0.2.0 in dist fixed, for 0.3.0, i need to merge with master. As soon, this week. You can publish 0.2.0

**Pull request merged**
