### PR TITLE
Update Annunciator to v1.0.5, adding new 'Shock & Awe' alarm indicator

### PR DESCRIPTION
**Pull request by michaeldmoore**
Added option to display unmistakable 'Shock and Awe' display using CSS animation to display threshold violations

### CODE REVIEW

**Comment by daniellee** [comment]
@michaeldmoore you missed bumping the version here: https://github.com/michaeldmoore/michaeldmoore-annunciator-panel/blob/master/dist/plugin.json#L13

**Comment by michaeldmoore** [comment]
Wow - good catch.  Very impressive catch actually.

Recompiled and re-committed with new hash (
3796550c2d733b777f85f1536b086b1ade33b75b).   updated the repo.json patch
accordingly.

Thanks Daniel
Michael Moore

**Comment by daniellee** [comment]
Sorry for the delay - merged and published

**Comment by michaeldmoore** [comment]
No problem, thank you for getting to this.   Just checked out Version 7
(beta) - looks really good too, though I shall have to reorganize the
settings forms to make them less wide.

Cheers
M

**Comment by daniellee** [comment]
Will talk to the frontend team to see if they can make some tweaks. Your two plugins look mostly ok but other plugins are affected more by the UI changes.

**Comment by michaeldmoore** [comment]
I'm getting a report that with g7, my multistat panel isn't recognizing a
table-formatted data set as being a table.  I haven't been able to
reproduce it here, but have requested the person reporting this to send me
a copy of the JSON data from the query inspector.  I'm looking for the
type:"table" value - is this still the proper way to tell if a data set is
table-formatted as opposed to a time-series?

**Comment by michaeldmoore** [comment]
The guy was using a SQL Server data source, something I can't test here
today.

**Pull request merged**
