### PR TITLE
Anodot-datasource v.1.0.3.

### PR DESCRIPTION
**Pull request by gooduling**
- Fix the issue with the same localstorage-key for multiple instances of anodot-datasource
- Add api path settings in Config Editor
- Add "Analityc" feature

### CODE REVIEW

**Comment by marcusolsson** [comment]
Hi @gooduling, 

When I test this version I get this error in the existing dashboard:

Screenshot 2021-07-15 at 13 48 32@2x

I suspect that it has something to do with the relative API path. Does this version contain a breaking change? Do I need to update the data source configuration to make this work?

**Comment by gooduling** [comment]
> Hi @gooduling,
> 
> When I test this version I get this error in the existing dashboard:
> 
> Screenshot 2021-07-15 at 13 48 32@2x
> 
> I suspect that it has something to do with the relative API path. Does this version contain a breaking change? Do I need to update the data source configuration to make this work?

Hi @marcusolsson, yes, you should update the configuration. Just open your Config Editor once and it will be enough. The thing is that "https://urlBase/api/v2/endpointName" was hardcoded before, and now users can customize it. So your old datasource just can't find this "/api/v2/" part without re-configinfg it

**Comment by gooduling** [comment]
@marcusolsson I've updated this PR. 
1. Increased datasource version to 2.0.1 to confirm it has breaking changes
2. Added anodot-panel v.1.0.3 - Topology Investigate link fixes

**Comment by gooduling** [comment]
@marcusolsson please review the PR now

**Comment by briangann** [comment]
There are two readme issues detected by the validator

image

Otherwise the plugins work as-is. 

If you want to publish this one and update the docs in another PR let me know.

**Comment by gooduling** [comment]
@briangann Thank you for your update! Yes, please, merge it as it is please, and I will fix it soon in a separate commit. Thank you!

**Review by briangann — APPROVED** [review]
both plugins have been published, thanks!

**Comment by gooduling** [comment]
@briangann please see the Readme changes here https://github.com/grafana/grafana-plugin-repository/pull/1022

**Pull request merged**
