### PR TITLE
Sunburst plugin for Grafana

### PR DESCRIPTION
**Pull request by Dikshita25**
- Read the [Review Guidelines](http://docs.grafana.org/plugins/developing/plugin-review-guidelines/) before submitting your plugin. These guidelines determine if the plugin is ready to be published or not.

- Commercial plugins require a plugin subscription to be published. Commercial plugin subscriptions help us fund continued development of our open source platform and software. See the [terms](https://grafana.com/terms) for more details.

- If possible, for datasource plugins please provide a description on how to set up a simple test environment. A docker container or simple install script helps speed up the review process a lot.

**REMOVE THE TEXT ABOVE BEFORE CREATING THE PULL REQUEST**

### CODE REVIEW

**Comment by marcusolsson** [comment]
Hi @Dikshita25, and thank you for considering contributing your plugin!

Before we can start reviewing your plugin, we need you to fix the issues reported by the plugin validator:

[Validate your plugin](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app?url=https://github.com/Dikshita25/sunburst-grafana-plugin/tree/97ed56b98f1974594a8b6e50ea7c116737a5e3ca)

Also, this PR reformats the repo.json. Could you update your PR with the existing format, so that it's easier to review?

**Comment by Dikshita25** [comment]
Hi @marcusolsson,
I have fixed all the mentioned issues and validated my plugin with the plugin validator. Please continue with the reviewing process. 
Thanks and Regards, 
Dikshita

**Comment by marcusolsson** [comment]
I've tried out the plugin, but I had some trouble creating the data needed for the visualization.

A recommendation is to document the data frame schema the panel expects. That way, users will know how to adapt their data queries to your panel, for any data source (and not just InfluxDB).

Screen Shot 2020-08-31 at 12 12 08

I can't wait to get this working :)

**Comment by Dikshita25** [comment]
Hi @marcusolsson , 
There were few issues in-order to plot the sunburst using table format. I have handled it and pushed my code with the latest changes. 
Also as recommended by you, have added a screenshot of the data frame schema in the read me file. Reference link : https://res.cloudinary.com/drgawxlgf/image/upload/v1598881232/Screenshot_2020-08-31_at_7.04.53_PM_rebhbc.png

**Comment by marcusolsson** [comment]
Thanks! Definitely works better now. I've categorized the feedback in descending priority. Only Priority 1 is required for me to publish your plugin. Priority 2 and 3 are recommended fixes to make your plugin even better.

**Priority 1**

- Please remove the default panel options from the plugin template.

Screen Shot 2020-09-01 at 14 55 08

**Priority 2**

- While the background looks great with the light theme, the black background looks off with using dark theme. Is there any way you can set a transparent background?

Screen Shot 2020-09-01 at 14 54 30

**Priority 3**

- If you want to take your panel to the next level, consider using the colors from the current Grafana theme. This will make your panel look more official/built-in. It's not a blocker for publishing at this point, but something I'd recommend you to look at for the next version if you'd like. For example, check out the [Treemap panel](https://github.com/marcusolsson/grafana-treemap-panel/blob/42f4105c5097de055eac8effabeb2db791f9a6a2/src/TreemapPanel.tsx#L216-L222) for how to get the theme colors.

This is a really cool panel! Looking forward to publishing it!

**Comment by Dikshita25** [comment]
Hi @marcusolsson , 
I have incorporated your suggested and recommended changes. Please review and let me know if anything else would be required from my side in-order to publish it. 
Here's a latest image of the chart with Grafana theme
Sunburst

Excited and eagerly waiting to see it on Grafana plugins :)

**Comment by Dikshita25** [comment]
Hi @marcusolsson , 
Wanted to check if any progress on the plugin. Just asking out of curiosity :)

**Comment by marcusolsson** [comment]
Looks awesome! And [published](https://grafana.com/grafana/plugins/dikshitashirodkar25-sunburst-panel)!  🎉 

Thanks for contributing to Grafana! ❤️

**Comment by marcusolsson** [comment]
@Dikshita25 Hm. Looking at the screenshots with the light theme, I realized I missed the notice about the "FusionCharts Trial". What are the conditions for the trial license? If it doesn't allow distribution (which I assume), I don't think we can have this on Grafana.com. Sorry I didn't catch this earlier.

**Comment by marcusolsson** [comment]
From https://github.com/fusioncharts/fusioncharts-trial:

> FusionCharts trial is free to use for as long as you want. No feature restrictions.
>
> DOWNLOAD FREE TRIAL
>
> You can easily buy a license for using our charts in commercial applications.

Looks like the trial isn't allowed for commercial applications. As all plugins on grafana.com can be installed by anyone using Grafana Cloud, I'm afraid we need to unpublish this :(

I'll look into this and get back to you!

**Comment by Dikshita25** [comment]
Hey @marcusolsson,
Sorry, i didn't notice that too. Let me remove the fusion chart and create a custom one for this plugin. Will get back to you soon. 
Thanks!

**Comment by marcusolsson** [comment]
Thank you, and no worries! It's an awesome plugin so I really want to get this up. 

I'll unpublish this in the meantime, and will be happy to review the next version!

**Pull request merged**
