### PR TITLE
add Flowhook 0.1.2

### PR DESCRIPTION
**Pull request by sjones427**
PR for adding new datasource plugin for Flowhook integration.
The plugin allows to consume webhook payloads, map and route them into your Grafana Logs panel.

**Testing notes:**
The plugin can be tested by creating a small webhook mapping at https://flowhook.herokuapp.com which is currently released simultaneously.

1. Please follow the instructions and copy the generated Flowhook ID to the plugin config after installation. Other settings can be left as default.

2. Visualize the datasource using the standard Logs panel.

3. When config is done, go to the explorer and in parallel fire a couple of webhook requests. The mapped extract of the webhook payload should show up in the panel.

### CODE REVIEW

**Comment by sjones427** [comment]
- upgrade version to 0.1.2
- merge repo.json

**Comment by marcusolsson** [comment]
Thank you for your patience while waiting for us to review your plugin. 

We're working hard at improving the plugin experience for both users and authors. I'd like to share some important information on how to package and publish plugins going forward.

Since Grafana 7.3, we require all plugins to be _signed_. By signing your plugin, users can guarantee the integrity of the plugin and that the plugin version they've installed hasn't been modified since it was released. For more information on how to sign your plugin, refer to [Sign a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/).

With this, we now require plugins to be _packaged_ before we publish them. This means that instead of a commit containing a `dist` directory, you will need to submit a link to a ZIP archive containing your plugin. For more information on how to package your plugin, refer to [Package a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/).

Once you've packaged your plugin, you'll need to update your entry to `repo.json` to the new format. You can read more on how to do this under [Add a plugin to repo.json](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson).

To summarize, to publish your plugin, make sure that you:

1. [Sign your plugin](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/)
2. [Package your plugin](https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/)
3. Create a new GitHub release and upload the packaged plugin as a release asset
4. [Update your repo.json entry](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson)

Here's an [example](https://github.com/marcusolsson/grafana-jsonapi-datasource/releases/tag/v0.6.0) of a properly packaged plugin. In the same repository, you can find a [GitHub Action](https://github.com/marcusolsson/grafana-jsonapi-datasource/blob/master/.github/workflows/main.yml) that signs, packages, and releases the plugin whenever you create a new tag.

Once you've created a GitHub release with the packaged plugin, you can right-click the release asset, copy the link, and validate it using [the plugin validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app). 

Finally, in the November [community call](https://groups.google.com/g/grafana-developers/c/ps2vzCXRDCM/m/i7uAK1u9AQAJ), I'll be walking through the steps needed to sign and package your plugin. A recording will be made available on our [YouTube account](https://www.youtube.com/playlist?list=PLDGkOdUX1Ujo0OyE5HFffHE9GJVvaVXGs), in case you can't make it.

**Comment by sjones427** [comment]
@marcusolsson I signed, packaged and re-verified the plugin with the tool. The repo.json is now including the download section with the link to the asset plus md5 checksum.

**Comment by marcusolsson** [comment]
I tried testing this, but I seem to have some trouble setting it up.

The only configuration on https://flowhook.herokuapp.com seems to be "Flowhook cookie token", but there's no such configuration field in the config editor:

Screen Shot 2020-11-24 at 17 52 32

Tried pasting it as "Flowhook" and "Password". Didn't seem to be any difference as both tested successfully, but didn't seem to get any data. What's the easiest way to generate test data?

**Comment by sjones427** [comment]
Ah, I see. That might be confusing. This token is just used for identifying and tying Flowhook configurations for your browser.

You need to scroll down into section 1 and create a new flowhook first (tab create from scratch).
grafik

Then the mapper will open and show you the IDs you need to copy into the plugin configuration field.
grafik

There are a couple of predefined mappings but you can of course also create your own.

If you need a hand with the setup I am also available on Gitter at https://gitter.im/verticle-io/flowhook

**Comment by marcusolsson** [comment]
Thank you for the guidance, it was very helpful! 🙏 

Screen Shot 2020-11-26 at 14 20 31

Once I configured the Flowhook ID, it worked as expected. I have a few comments from the initial review:

- I felt it was a bit hard to understand the config editor. I'd suggest that you rename the "Flowhook" field to "Flowhook ID". 
- The placeholder for the Flowhook ID is a bit cryptic. "json field returned to frontend" could instead be a correctly formatted ID, which would've helped me figure out what to look for. 
- I would change "BrokerURL" -> "Broker URL" to make it read easier
- I'm not sure when the broken URL, username and password would be applicable, but I assume it's when you're hosting it yourself. I'd suggest that you add some more documentation on the fields. You can use the `tooltip` prop on the `FormField` to add a short description of what the field does.
- The QueryField is a bit redundant right now. I understand that you might add querying abilities later, but maybe for now you can replace it with some text saying something like "Your events are now streaming ...". Maybe using an [InfoBox](https://developers.grafana.com/ui/latest/index.html?path=/story/layout-infobox--basic).
- Just noticed that your plugin has a backend plugin that isn't being used. Do you have plans for this?

None of the comments are blocking imo, but I think it would improve the user experience. Let me know if you'd like to fix any of them before I publish this!

**Comment by sjones427** [comment]
Thanks for the feedback, makes sense. I will provide an update.

**Comment by sjones427** [comment]
@marcusolsson I have improved a couple of things in the UI according to your suggestions. It should be ready for publishing now.

**Comment by marcusolsson** [comment]
Looks great! I think this is ready to publish. We're working on some kinks in the publishing script at the moment, but I'll publish this as soon as I've sorted it out.

**Comment by marcusolsson** [comment]
[Published](https://grafana.com/grafana/plugins/verticle-flowhook-datasource)! 🎉

**Pull request merged**
