### PR TITLE
Release v0.2.1 simpod-json-datasource

### PR DESCRIPTION
**Pull request by simPod**

### CODE REVIEW

**Comment by fedeneira** [comment]
I might be doing something wrong, but I am not seeing [#100](https://github.com/simPod/grafana-json-datasource/issues/100) fixed in v0.2.1

**Comment by simPod** [comment]
what are you doing?

**Comment by fedeneira** [comment]
I apologyze in advance, just in case I want to clarify that I am not a developer, only and advances Grafana user. What I did was to:
.Download the files from release v0.2.1
.Paste them on top of the files of v.0.2.0 in the plugins directory of my grafana installation
.Restart grafana
.Just in case I also created the datasource again.
Capture


Please see attached image

**Comment by diafour** [comment]
@fedeneira you've downloaded a fork of `grafana/grafana-plugin-repository`, not a plugin repo.

**Comment by simPod** [comment]
Hi @daniellee @briangann, can we please release this? It's sitting here for too long :/ Thanks

**Comment by simPod** [comment]
@briangann thanks, do you have a documentation on that? What is the difference between `grafanaDependency` and `grafanaVersion`?

**Comment by briangann** [comment]
> @briangann thanks, do you have a documentation on that? What is the difference between `grafanaDependency` and `grafanaVersion`?

grafanaVersion isn't being parsed anywhere, but this new property "grafanaDependency" is semver checked.  if a user is running 7.0, and the value is >=7.1.0, this version will not be offered.

**Comment by simPod** [comment]
@briangann can I drop grafanaVersion then?

**Comment by simPod** [comment]
I'll drop it and see the answer during next version bump.

**Pull request merged**
