### PR TITLE
Update flowcharting 0.9.0

### PR DESCRIPTION
**Pull request by algenty**
Hi the team,

It's time for me to push the next version of flowcharting before the last version, I've exhausted all my ideas. still only "multi diagram feature" for the last  (big evolve) and off course migration to react.

### Added
  - CSV Format support for flowchart source (https://drawio-app.com/import-from-csv-to-drawio/)
  - New aggregation : Time of last point  
  - New fill Method : Gradient ([See example](https://algenty.github.io/flowcharting-repository/images/gradients_color_ani2.gif?raw=true))  
  - Graph hover support ([See example](https://algenty.github.io/flowcharting-repository/images/floorplan_graphhover.gif?raw=true))  
  - Better rendering of color animation with chroma-js
  - New Events/Animations Mapping :  
    * Modify Gradient direction  
    * Modify Arrow start and end connectors ([See example](https://algenty.github.io/flowcharting-repository/images/connectors_color_ani2.gif?raw=true))  
    * Flip shape horizontally or vertically  
    * Resize shape in percent ([See example](https://algenty.github.io/flowcharting-repository/images/resize_ani.gif?raw=true))  
    * Flow animation (experimental, not work with a shadow on arrow)  
  - New homepage schema
  - Support external fonts like google fonts ([See example](https://algenty.github.io/flowcharting-repository/images/google_fonts.png?raw=true))  
  - New anonymizer feature in inspect section to share the diagrams without sensible data ([See example](https://algenty.github.io/flowcharting-repository/images/anonymize_ani.gif?raw=true))  
  
### Fixed
  - Fixed : Flowchart grid display  
  - Fixed : background color field in edit mode  
  - Fixed : Blink event  
  - Fixed : Overflow on grafana v7 [(issue #172)](https://github.com/algenty/grafana-flowcharting/issues/172)   
  
BR
Arnaud
PS : Could you update play.grafana.com with it ?

### CODE REVIEW

**Comment by algenty** [comment]
I understand that all ressources are mobilized on grafana 7, could i have a date for this update ?
It will fix a bug for grafana v7

**Comment by briangann** [comment]
i'll review it during the day today, sorry for the delay

**Comment by briangann** [comment]
published thanks!

**Comment by algenty** [comment]
it's me, thx

**Comment by algenty** [comment]
> editor

It would be very cool if user have the choice to move query tabs and configuration when he wants like a panel.

**Comment by daniellee** [comment]
@algenty I updated the plugin on play.grafana.org.

**Comment by algenty** [comment]
> @algenty I updated the plugin on play.grafana.org.

Thx Daniel

**Pull request merged**
