### PR TITLE
update grafana-radar-panel: Few graphical options added

### PR DESCRIPTION
**Pull request by snuids**
Merged @fremag modifications: New chart options: min, max, step, animation

### CODE REVIEW

**Comment by alexanderzobnin** [comment]
@snuids 
1. There's a version mismatch between repo.json and plugin.json: `Version in repo.json (1.4.3) doesn't match plugin.json (1.4.2)`
2. You should add a new version into the 'repo.json` rather than change an old one.

**Comment by snuids** [comment]
@alexanderzobnin

I restored the previous version.

спасибо,

**Comment by alexanderzobnin** [comment]
@snuids version in `plugin.json` is still outdated: `Version in repo.json (1.4.3) doesn't match plugin.json (1.4.2)`

**Comment by snuids** [comment]
@alexanderzobnin 

I am probably missing something here. I guess that the repo.json is OK. The plugin.json in my repo is also 1.4.3. Is there something more that I should do ?

Cheers,

**Comment by briangann** [comment]
@alexanderzobnin looks like repo.json and plugin.json match, should be fine to publish.

**Comment by alexanderzobnin** [comment]
@snuids check `plugin.json` in the dist/ folder. It seems, you forgot to build it:
https://github.com/snuids/grafana-radar-panel/blob/7ee4013b618875710b2c767542095ce9ab91a645/dist/plugin.json#L29

**Comment by snuids** [comment]
@ alexanderzobnin

Hi Alexander. You were right since the beginning. I lazily tried to update the plugin in the repo without building it.

Thx,

Cheers

**Comment by snuids** [comment]
Re opened as a new request

**Pull request closed without merging**
