### PR TITLE
Add Check_MK Datasource

### PR DESCRIPTION
**Pull request by cbmueller**

### CODE REVIEW

**Comment by alexanderzobnin** [comment]
@cbmueller Hi! Thanks for your contribution! Could you provide some description of Check_MK and how to configure it for testing your data source?

**Comment by cbmueller** [comment]
@alexanderzobnin Hi! Check_MK is used to gather system monitoring information on different hosts. The datapoints are quite diverse, examples are host availability or CPU load, Memory usage, etc. We have added a development setup section in the repository readme (https://github.com/tribe29/grafana-checkmk-datasource). You will need to setup a Check_MK installation and some host to generate some actual data to be displayed. I can provide you with a docker image for the correct Check_MK version. I'd need to send you the credentials on some private channel, just let me know the preferred way ;)
Thanks in advance for your effort!

**Comment by daniellee** [comment]
@cbmueller Hi, it's my week to review plugins. Not sure if Alex followed up here?

I tested with the open source version of Check MK and got this error when trying to select a metric:

`Check_MK exception: Currently not supported with this Check_MK Edition`

Is that me doing something wrong or are metrics an Enterprise feature?

Also, for version 1.0.1, the [plugin.json in dist](https://github.com/tribe29/grafana-checkmk-datasource/blob/33e5c04e5d62c4188c2c25fe8cb10df378305f2b/dist/plugin.json#L26) is incorrect and has not been updated.

**Comment by cbmueller** [comment]
@daniellee Hi, thanks for reviewing. You are right, the metrics are an enterprise feature. You can download a working version here:
https://checkmk.com/download_version.php?&version=1.5.0p19&edition=cee
using the credentials i will send you in a private message.
I will also fix the 1.0.1 plugin.json and update this PR.

**Comment by cbmueller** [comment]
[plugin.json](https://github.com/tribe29/grafana-checkmk-datasource/blob/3254e11c746a19a3bbed47e09692c0d427143df5/dist/plugin.json#L26) has been updated to the correct 1.0.1 version.

**Comment by martinhv** [comment]
Hey @daniellee 
I am from Checkmk. We have a lot of users, who are eager to get the integration done. Thus, the faster this is included, the better.
We are happy to assist in the testing, e.g. have one of our consultants guide you through the integration with actual data. Let me now at mh@tribe29.com, if this is needed.
Best, Martin

**Comment by marcusolsson** [comment]
Closing this as it seems like there hasn't been any activity on this submission in a while.

If you'd like to submit the plugin again, I'd like to invite you to use our new submission flow inside Grafana Cloud. For more information and instructions, check out the [README](https://github.com/grafana/grafana-plugin-repository).

**Pull request closed without merging**
