### PR TITLE
Add grafana-druid-plugin entry

### PR DESCRIPTION
**Pull request by abhisant**
Adding an entry for grafana-druid-plugin to contribute the druid plugin on grafana.net.

### CODE REVIEW

**Comment by abhisant** [comment]
Hi, 

I need to make one minor change. I am cancelling the pull request and will be issuing a new pull request shortly.

**Comment by abhisant** [comment]
Changing the commit-id and datasource-id.

**Comment by abhisant** [comment]
@DanCech : Sorry for closing one and opening other. I wanted to make minor changes to plugin.json which eventually changed the commit-id. The repo.json is updated with the correct commit-id. 

Please let me know if you have any questions. Thank you in advance.

**Comment by DanCech** [comment]
To be published on grafana.net you'll actually need the plugin id to be something like `abhisant-druid-datasource` (assuming your grafana.net org name is `abhisant`)

**Comment by abhisant** [comment]
Got it. Will update it and get back to you. Thanks for the quick response.

**Comment by abhisant** [comment]
As per @DanCech 's suggestion, I have updated the plugin with correct id "abhisant-druid-datasource" and updated repo.json with correct id and commit

**Comment by torkelo** [comment]
Ok will try to test it in the coming 2-3 dayz

**Comment by grafana-druid-plugin** [comment]
@torkelo @DanCech . Did you get a chance to test it.

**Comment by abhisant** [comment]
@torkelo @DanCech . Just wanted to followup regarding the status of this plugin to be added on grafana.net. Thank you.

**Comment by torkelo** [comment]
@abhisant it is not working, the partial paths seem to be wrong.

https://github.com/grafana-druid-plugin/druidplugin/blob/master/dist/config_ctrl.js#L10

If you clone your plugin into the "external plugins" directory you will see the issue yourself (external plugin dir is /var/lib/grafana/plugins or <workingdir>/data/plugins (if running local dev build). 

The partials path can be relative, so specify `partials/config.html` should fix it

**Comment by abhisant** [comment]
@torkelo : Apologize for having the explicit path. I have fixed the issue and tested it. Please let me know if you have any further questions.
I have added the latest commit-id and issued a new pull request:
https://github.com/grafana-druid-plugin/grafana-plugin-repository/blob/master/repo.json#L537

**Comment by torkelo** [comment]
ok, better, looks like the query editor has some layout bugs

image

some padding around the first row due to Custom Granularity wrapper to two rows. 

Increase width class here to width-11 (or remove width class for auto width)
https://github.com/grafana-druid-plugin/druidplugin/blob/master/src/partials/query.editor.html#L26 

Also gf-form-switch should not be inside a gf-form (it has that already) so you can move that outside. 

There are some other issues where you nest gf-form inside gf-form, this you should never do. 
Example:
https://github.com/grafana-druid-plugin/druidplugin/blob/master/src/partials/query.editor.html#L116

Also the special row depending on query type is missing a grow element (notice the black are to the right)
image

**Comment by abhisant** [comment]
@torkelo ... Surprisingly I don't see these layout issues, in my local setup.

 I tried to test this in all Chrome, Firefox and Safari .. Even I tried to shrink the window but I always have "Custom Granularity" in one row only instead of wrapping up to two rows as you see.

image

**Comment by torkelo** [comment]
Change query type to something else than time series

**Comment by abhisant** [comment]
@torkelo : Following are the UI Bug Fixes in the commit:

1. Fixed padding around the first row issue because of which Custom Granularity wraps to two rows.
2. Fixed all issues where gf-form was nested under another gf-form
3. Fixed all issues where gf-form-switch was nested under gf-form
4. Fixed issue where special row depending on query type is missing a grow element
5. Fixed alignment issues.

Please find the screen-shot below:

image

**Comment by abhisant** [comment]
@torkelo : Did you get a chance to review / test the changes. Thank you in advance.

**Comment by DanCech** [comment]
There is a slight problem, the version needs to be included in the info object in plugin.json before we can upload it to grafana.net, so for now I've reverted this merge.

@abhisant can you add the version to your plugin.json and open a new PR with the updated commit hash?

Something like:
```
  "info": {
    "version": "0.0.1",
    ...
  }
```

**Comment by abhisant** [comment]
Does this look fine ? I will open a new PR if this is correct.

{
  "type": "datasource",
  "name": "Druid",
  "id": "abhisant-druid-datasource",

  "metrics": true,

  "info": {
    "version": "0.0.1",
    "author": {
      "name": "Abhishek Sant",
      "url": "https://github.com/grafana-druid-plugin/druidplugin"
    },
   "links":[
     {"name": "GitHub", "url": "https://github.com/grafana-druid-plugin/druidplugin"}
    ],
   "logos": {
      "small": "img/druid_logo.png",
      "large": "img/druid_logo.png"
    },
   "dependencies": {
     "grafanaVersion": "3.x.x",
     "plugins": [ ]
    }
  }
}

**Comment by abhisant** [comment]
Done: https://github.com/grafana/grafana-plugin-repository/pull/35 <https://github.com/grafana/grafana-plugin-repository/pull/35>

**Pull request merged**
