### PR TITLE
Add akumuli-datasource

### PR DESCRIPTION
**Pull request by Lazin**
This PR adds `akumuli-datasource` plugin. Akumuli is a time-series database available at http://github.com/akumuli/Akumuli

### CODE REVIEW

**Comment by daniellee** [comment]
Did you close this on purpose?

**Comment by Lazin** [comment]
Yes, I found some issues and need to fix my plugin.json and change repository name. I will reopen when it will be ready. Otherwise, it will be a waste of time for the reviewers.

**Comment by Lazin** [comment]
You can use this instance for testing - http://34.213.9.196:8181
It stores it's own metrics.

**Comment by daniellee** [comment]
The [plugin.json](https://github.com/akumuli/akumuli-datasource/blob/master/dist/plugin.json) file in the dist directory is missing version in the info section:

http://docs.grafana.org/plugins/developing/code-styleguide/#plugin-json-mandatory

**Comment by Lazin** [comment]
Templating support added.

**Comment by daniellee** [comment]
Sorry for the delay - have been very busy with Grafana 5.0. I have everything up and running locally - what is the easiest way to ingest data into Akumui? I just need some test data to test the plugin with.

**Comment by Lazin** [comment]
Hi,
I think that the easiest way is to use OpenTSDB protocol (you may already have the tools). Akumuli implements OpenTSDB telnet protocol. Alternatively, you can use native RESP based API. Both protocols are described in this article - https://github.com/akumuli/Akumuli/wiki/Writing-data-using-the-TCP-API.
Also, I have a server with Akumuli here - http://34.213.9.196:8181
It runs Akumuli and tcollector that writes monitoring data.

**Comment by daniellee** [comment]
Thanks for the link to your server - that was exactly what I needed.

Feedback on Metadata:

- README.md has a relative link which will not work on the plugins page in Grafana or on Grafana.com. So `Grafana dashboard` should be changed to: `https://raw.githubusercontent.com/akumuli/akumuli-datasource/master/akumuli.grafana.png`

Feedback on Plugin

- Could not find any docs about EWMA smoothing - just a line or two explaining the acronym and concept and maybe why it is a great fit with Grafana's alerting.
- Show/hide queries in the query editor (by clicking on the eye icon) does not work. This needs to be implemented in the data source. Here is an [example from the Simple JSON data source](https://github.com/grafana/simple-json-datasource/blob/master/src/datasource.js#L21).
- Downsampling didn't work for me or maybe I just don't understand how it works. But I tried different values for downsampling and did not see any changes in the graph. Here I've chosen a 1 hour interval with 10m downsampling but am still seeing a point per 15s

    image

Generally, it looks good. The query editor is easy to use and looks neat and tidy. Great work!

**Comment by Lazin** [comment]
Hi @daniellee 
Thanks for the feedback! I fixed the bugs that you've found and removed EWMA support (I'm going to reintroduce it in the next iteration with proper documentation and a bunch of other stuff). Also, I added the aliasing support and improved the documentation.

**Comment by Lazin** [comment]
I created new demo server here - http://206.189.27.155:8181
It has around 10K metrics. There are tcollector metrics (e.g. "proc.net.packets" ...) and netdata metrics (all have "netdata prefix"). Also, the server pings a bunch of hosts and stores latencies in the database. These metrics are also available in the datasource. The old demo server will be turned off in a while.

**Comment by Lazin** [comment]
Hi @daniellee,
any news on this PR?

**Comment by Lazin** [comment]
I created the dashboard for the test endpoint - https://gist.github.com/Lazin/879e47c4edba91cceb9108d3bbc3a0d4

**Comment by daniellee** [comment]
Thanks @Lazin - will get back to you with feedback this week.

**Comment by Lazin** [comment]
Thank you @daniellee!

**Pull request merged**
