### PR TITLE
Bigquery grafana 2.0.2

### PR DESCRIPTION
**Pull request by ofir5300**
Already approved @daniellee 

https://github.com/grafana/grafana-plugin-repository/pull/913

### CODE REVIEW

**Comment by daniellee** [comment]
I am getting a modified signature warning again unfortunately:

```
WARN[06-29|23:57:29] The following files were not included in the signature logger=plugins plugin=doitintl-bigquery-datasource files=[.DS_Store]
```

**Comment by ofir5300** [comment]
@daniellee 
I updated the zip file once again.
Before uploading everything works as expected, but when I am trying to download and run it locally im running into this error:
`pluginId=doitintl-bigquery-datasource error="Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol."`

I did updated binary files permissions using `chmod +rwx`, dont know if its related.

**Comment by daniellee** [comment]
@ofir5300 seems to work for me locally with the Linux version. I can do some more testing to see if I can reproduce your error.

**Comment by ofir5300** [comment]
@daniellee great to hear it works.
I am using the darwin version, so do whatever is required before approval and let me know if further changes need to be done.

**Review by daniellee — APPROVED** [review]
LGTM

**Comment by ofir5300** [comment]
Hi @daniellee tnx for approving,
I checked my newest zip and found out it can not run on mac (darwin) due to .DS_store file issue with the manifest.
So please re-approve my new zip (v2.0.2 is useless at the moment) #991
Tnx and sorry for the ping-pong

**Pull request merged**
