### PR TITLE
AppDynamics v1.1.0 - Template support

### PR DESCRIPTION
**Pull request by dlopes7**
This adds templating support for the AppDynamics Datasource plugin.

### CODE REVIEW

**Comment by daniellee** [comment]
Fantastic work! Sorry for the delay - took me a while to get around to setting up everything in App Dynamics again.

**Comment by jameyg42** [comment]
@dlopes7 this is 404ing

**Comment by dlopes7** [comment]
@jameyg42 The repository is private

**Comment by jameyg42** [comment]
@dlopes7 i'm saying that `grafana-cli plugins update dlopes7-appdynamics-datasource` is failing (404), and i'm assuming it's  because the repo is private.  i.e i can't download the plugin

**Comment by daniellee** [comment]
@jameyg42 the AppDynamics plugin got converted to a premium plugin. The version you have is open source but to get future updates you will need to have a support subscription:

https://grafana.com/services/support

Nearly all the plugins are open source (and plugins for open source products will always be open source) but for some "enterprise" integrations we have decided to package them as premium plugins. This is both a way for us to fund Grafana development and a way to maintain plugins that will not receive much support from our community but are valuable for companies.

**Comment by jameyg42** [comment]
ok..that's fair - wasn't obvious since the plugin keeps listing as "update available" (the previous version never worked for me, so i never actually used this).  The license on the plugin's page still says MIT though (so that should change)

**Pull request merged**
