### PR TITLE
add offical spotify heroic datasource plugin.

### PR DESCRIPTION
**Pull request by sjoeboo**
replaces #501  with a clean commit. 

@ryantxu @briangann

### CODE REVIEW

**Comment by ryantxu** [comment]
> "id": "heroic-grafana-datasource",

What about just:
 ""id": "heroic-datasource",

Also, have you made the heroic org yet?  I see:
image

**Comment by sjoeboo** [comment]
@briangann fixed, sorry about that! 

@ryantxu we decided to just stick with things as they are and worry about org changes down the line if/when they happen.

**Comment by briangann** [comment]
The org "spotify" needs to be created with the current plugin id.

Whatever the "first" word of the plugin is name has to have a corresponding org.

**Comment by sjoeboo** [comment]
@ryantxu @briangann i'm actually failing to see how/where to create an org for this...any docs you can point me to?

**Comment by sjoeboo** [comment]
nevermind, think i've got one created now.

**Comment by briangann** [comment]
merged and published!

**Pull request merged**
