### PR TITLE
Add Darksky API plugin

### PR DESCRIPTION
**Pull request by andig**
## DarkSky Datasource - weather and forecast data for Grafana

This plugin allows to history weather conditions and forecast data as returned by the [DarkSky](https://darksky.net) API.

dashboard

### Requirements

1. API key

   Register for a DarkSky API key at [DarkSky](https://darksky.net). The free plan will allow 1000 API calls per day.

2. Geo location

   Weather data will be available for the location defined when creating the data source. If unsure you can alwayds use [Google Maps](https://maps.google.com) or IP location APIs like [ipgeolocation.io](https://ipgeolocation.io).

### Configuration

Example configuration:

config

### CODE REVIEW

**Comment by andig** [comment]
CI fails on unrelated plugin

**Comment by andig** [comment]
Hello @daniellee can we have an update on this one please?
Thanks

**Comment by andig** [comment]
After 18 days since first asking and 5 days since pinging I'm starting what it would take to get a response. Sorry to say that- but together with my experience with the simplejson plugin- I feel that Grafana (at least the plugin part of the ecosystem) is really unwelcoming.

**Comment by andig** [comment]
Ping @torkelo @daniellee it has now been 24 days without any sign of communication. Is there a particular reason that this plugin request doesn‘t deserve an answer? If so it would be nice to know about it so I can stop trying...

**Comment by marefr** [comment]
Sorry for not getting back to you. Thought this build failed due to a real linting error. Seems like it fails with an unhandled exception. We need to investigate and we'll let you know when we know what's wrong. Thanks

**Comment by DanCech** [comment]
The problem is that the plugin id is not valid https://github.com/andig/grafana-darksky/blob/master/dist/plugin.json#L3

The plugin id should be `andig-darksky-datasource` (assuming your grafana.com username is `andig` also.  You'll need to update your repo with the correct id in `plugin.json`, then update this PR with the correct plugin id and the updated commit hash.

**Comment by andig** [comment]
Thanks @DanCech the failure wasn't obvious. I've updated accordingly.

**Comment by DanCech** [comment]
It looks like you manually modified `dist/plugin.json`. What you'll want to do is to update `src/plugin.json` then re-run `grunt` to update `dist/`

**Comment by daniellee** [comment]
Merged and published: https://grafana.com/plugins/andig-darksky-datasource

I apologize for the lack of response - most of the plugin work falls on me and I just haven't had time in the last few weeks. I will try and spread it out and get more people involved in the reviewing process.

The plugin is nice and simple and seems to be bug free - nice work!

**Comment by andig** [comment]
> I apologize for the lack of response - most of the plugin work falls on me and I just haven't had time in the last few weeks. I will try and spread it out and get more people involved in the reviewing process.

I have to admit it was a bit painful. I'm wondering why you need to maintain such a level of control. If you look at e.g. node-red it's much easier to install plugins. If it is for grafana cloud- it might make sense to enforce this review procedure only for allowing plugins into the hosted Grafana?

> Just noticed that this sentence in the README is a bit strange:

Thanks for the hint, will fix that.

**Pull request merged**
