### PR TITLE
Add Im comparison panel

### PR DESCRIPTION
**Pull request by scipper**
Hi grafana team,

this plugin adds the ability to view the trend of two datasets from different time ranges.

### CODE REVIEW

**Comment by marcusolsson** [comment]
Could you please update your PR to the [following format](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson):

```
{
  "id": "briangann-gauge-panel",
  "type": "panel",
  "url": "https://github.com/briangann/grafana-gauge-panel",
  "versions": [
    {
      "version": "0.0.8",
      "url": "https://github.com/briangann/grafana-gauge-panel",
      "download": {
        "any": {
          "url": "https://github.com/briangann/grafana-gauge-panel/releases/download/v0.0.8/briangann-gauge-panel-0.0.8.zip",
          "md5": "782c973460f330287b7efca5486aa015"
        }
      }
    }
  ]
}
```

Once you've updated your PR, make sure you paste the URL to the ZIP archive into the [plugin validator](https://plugin-validator.grafana.net/) to make sure it's ready for review.

**Comment by scipper** [comment]
@marcusolsson I have a little bit trouble understanding this step. This would require me to create a tag/release. But this release won't have a valid manifest (obviously). Do I need to make some kind of prelease (v0.0.1) and after your submission I create my "real" release (v1.0.0) and a new Pul Request to this repo?

**Comment by scipper** [comment]
I tried to create a release anyway, but the manifest is missing:
image
And if I get the [documentation](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/) right, the manifest can only be created, after Grafana approved the plugin and granted a signature level.

**Comment by marcusolsson** [comment]
Sorry for the confusion. You're right that you won't be able to sign the plugin until we've done the initial review. You don't have to worry about that for now.

**Comment by marcusolsson** [comment]
You can just skip the signing step and create a package without the signature for now.

**Comment by scipper** [comment]
Alright. I will delete the broken release then.

**Comment by scipper** [comment]
@marcusolsson the plugin validator is now satisfied as far as possible :)

**Comment by marcusolsson** [comment]
I've been reviewing the plugin a bit and it seems to parse not just the query result, but the query as well (by parsing the `status` from the `expr` property).

This would mean that the panel is more or less tied to the Prometheus data source rather than supporting other data sources. It also makes it somewhat hard to test (and for others to use for that matter). I'll have to generate custom Prometheus data with the status label.

I'd be able to help out, if you'd be up for updating the panel requirements to make it more user friendly? Alternatively, I'll look into a script to generate some test data and review the plugin as it is.

Also, I can't find a Grafana Cloud account called `im` so I won't be able to configure a signature level for the plugin right now. Do you have a Grafana Cloud account you wish to have ownership of the plugin?

**Comment by scipper** [comment]
@marcusolsson Thank you, for reviewing. 
First of all, I created the cloud account. So this should be fixed.

The coupling to Prometheus is currently intended, but I see the problem of course. I will discuss with my colleges, what options we have, to make this part more user friendly. 

What do you mean with this: 

> Alternatively, I'll look into a script to generate some test data and review the plugin as it is.

**Comment by marcusolsson** [comment]
I meant that if, after talking to your colleagues, you wish to publish the plugin as is, I can also generate the Prometheus metrics needed to test the plugin in its current state.

Normally I use the [Static](https://grafana.com/grafana/plugins/marcusolsson-static-datasource/) data source to mock the data source when reviewing panels.

Let me know if you have any questions!

**Comment by scipper** [comment]
I removed the query expression parsing and replaced it by appropriate options. I hope this helps users and makes it more flexible regarding to the data source.

**Comment by marcusolsson** [comment]
Awesome! When it's ready for testing, please update the pull request with the new version 🙏

**Comment by scipper** [comment]
Can you help me figuring out what the probleme with `build-branches-and-prs` is? For some reason, the README.md could not be found. 
image
Screenshot from circleci.

**Comment by marcusolsson** [comment]
When I run the [plugin validator](https://github.com/grafana/plugin-validator):

```
plugincheck2 -config ~/src/github.com/grafana/plugin-validator/cmd/plugincheck2/config/publishing.yaml https://github.com/IntegrationMatters/im-comparison-panel/raw/master/im-comparison-panel.zip
```

I'm getting an error saying:

```
error: archive contains more than one directory
```

For more information, check out [Package a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/).

Basically, you'll want to run the following commands:

```
mv dist/ im-comparison-panel
zip im-comparison-panel-1.0.0.zip im-comparison-panel -r
```

**Comment by scipper** [comment]
My bad, I created the archive wrongly.

**Comment by marcusolsson** [comment]
Thank you! I've done a final review of the plugin. I have a few suggestions, but I'm ok with publishing the plugin as is.

Unfortunately, I'm still not able to see the `im` Grafana Cloud account. Could you let me know the name of the account you'd like to use?

### Suggestions

- The "Panel" in "Comparison Panel" is a bit redundant when display in the visualization list. I think it would look better with just "Comparison".

Screenshot 2021-07-12 at 10 30 35@2x

- When the panel is too small, the content overflows.

Screenshot 2021-07-12 at 10 28 52@2x

- Minor UX feedback, but I noticed that the color of the Change value depends on the Status type. Maybe it's just me, but I got a bit confused about positive values being red, and negative values being green. I understand that less errors is good, so the color makes sense to me. Maybe use icons with up and down arrows instead of +/-?

**Comment by scipper** [comment]
I notices your suggestions and would forward them to the next patch. 

Can you tell me, if there is a way to change my account name? I already changed the organization name to `im`, but the account still is `skowalski`.

**Comment by scipper** [comment]
Another question: I wanted to create a now account, but the account length minimun is 3 chars. So, I can't create `im`. Can I refer to something else, like `integrationmatters`?

**Comment by marcusolsson** [comment]
Yes, you can! The only important thing is that since we use the plugin name to determine ownership, the first part of the plugin ID needs to match the account ID. If you create an account called `integrationmatters`, you'd also need to change the plugin ID to `integrationmatters-comparison-panel`, or `skowalski-comparison-panel`.

**Comment by scipper** [comment]
I changed the plugin prefix to `integrationmatters`

**Comment by marcusolsson** [comment]
I've configured `integrationmatters-comparison-panel` to be signed  under a Community signature level. You should now be able to sign the plugin. Let me know if not. Make sure that you generate the API key for signing from the `integrationmatters` account.

**Comment by scipper** [comment]
I was able to create a manifest. How do I proceed from here? Do I have to copy it from the dist folder into the project source and version it? Or just create a new archive?

**Comment by marcusolsson** [comment]
1. `yarn build` generates `dist`
2. `yarn sign` generates `dist/MANIFEST.txt`
3. `mv dist/ integrationmatters-comparison-panel`
4. `zip -r integrationmatters-comparison-panel-1.0.0.zip integrationmatters-comparison-panel`

Alternatively, you can use the [workflows for GitHub Actions](https://github.com/grafana/plugin-workflows) which will build, sign, and package the plugin for you.

Feel free to update this pull request once you've created a signed plugin package.

**Comment by scipper** [comment]
I updated the PR with the new archive, containing the manifest. 
Thank you alot for your help!

**Comment by marcusolsson** [comment]
Thank you 🙏 I've published the plugin, but please allow for a few minutes before it becomes available.

**Pull request merged**
