### PR TITLE
release cognite-datasource v2.0.0

### PR DESCRIPTION
**Pull request by polomani**
### General improvements

- A new query language inspired by PromQL and compatible with synthetic time series in CDF. [Learn more](https://docs.cognite.com/cdf/dashboards/guides/grafana/timeseries.html#custom-queries).
- Support for all filtering capabilities available in [CDF API v1](https://docs.cognite.com/api/v1/) for the respective resource types (assets, events, times series).
- Any future **filtering** capabilities added to CDF API v1 will be **automatically supported** by the data source (filters are passed directly to CDF).
- Query expressions resulting in errors now **displays error messages** in the UI.
- Regular expressions filtering can be used as part of the **Query** expression. The **Filter** field has been removed.
- Supports CDF [API v1](https://docs.cognite.com/dev/API_versioning.html#current-api-versions), with no dependency to older API versions.
- [New documentation section](https://docs.cognite.com/cdf/dashboards/guides/grafana/getting_started.html) for the connector, covering installation and administration, upgrades, feature documentation and getting started information.
- Compatibility with Grafana 7.0. Learn more about the new capabilities [here](https://grafana.com/blog/2020/05/18/grafana-v7.0-released-new-plugin-architecture-visualizations-transformations-native-trace-support-and-more/?isource=hp).

### Time series and custom queries

- You can now access time series that don't have the `legacyName` attribute populated with the data source.
- Setting `Root Asset` in the **Custom query** tab is no longer required. This filter has been removed from the UI and is now available as part of a custom query expression. For example: `ts{rootAssetIds=[12335453, 3455566]}`.
- Custom query aggregation requests are less likely to trigger rate limiting in CDF API.
- Functions:
  - Support for **string time series** through the new `map` function allows you to convert string values to numeric values which can then be plotted by Grafana. For example: `map(ts{externalId='pump_29'}, ['OPEN', 'CLOSED'], [1, 0], -1)`.
  - Use the `on_error` function to gain control over query calculations resolving with errors, such as division by 0. The function allows you to set a default value for individual data points that resolved with errors. Without the `on_error` function, the chart shows empty space in those places. Example: `on_error(1/ts{externalId='canBeZero'}, 0)`.
  - Variable length functions: `max(x1, x2, ...)`, `min(...)`, `avg(...)`.
  - The `power` function has been renamed to `pow`.
  - These functions are no longer supported: `acos`, `asin`, `atan`, `ceil`, `celing`, `cot`, `degrees`, `floor`, `log`, `log2`, `log10`, `radians`, `sign`, `tan`, `atan2`, `mod`, `truncate`, `rand`, `crc32`, `conv`, `div`.
- These aggregates are no longer supported by custom queries: `max`, `min`, `count`, `sum`, `continuousVariance`, `discreteVariance`, `totalVariation`.
- Short names for aggregation functions are no longer supported. Use full names instead: `average`, `interpolation`, `stepInterpolation`.
- The `timeseries{options}` function has been renamed to `ts{options}`.
- Filtering:
  - New options:`isString=false`, `externalId='my_id'`, `id=123`, `externalIdPrefix='my_'`
  - Relate to asset tree with: `assetSubtreeIds=[{id=754173880412890},{externalId="23-TE-96148"}]`, `assetIds=[123, 234]`, `assetExternalIds=['pump_1', 'pump_2']`, `rootAssetIds=[123, 234]`
  - New range filters for create and updated time: `createdTime={min=0, max= 1593018651}`, `lastUpdatedTime={min=1493018651, max= 1593018651}`
  - Select time series based on dataSet membership: `dataSetIds=[{externalId='Prediction Model A'},{id=123}]`
  - `path` is no longer supported
  - See the full list of [supported filters](https://docs.cognite.com/api/v1/#operation/listTimeSeries) for the `ts{}` expression.

### Annotations

- New filters: `assetExternalIds`, `rootAssetIds`, `dataSetIds`, `externalIdPrefix`, `source`.
- Find active events in range with the `activeAtTime` filter. If `endTime` is null, the event is active from `startTime` onwards. The `activeAtTime` filter will match all events that are active at some point from `min` to `max`. Example: `activeAtTime={min=1591018651, max= 1593018651}`.
- `description` supports only regular expression operators `=~`, `!~`, and `!=`.
- `minStartTime`/`maxStartTime` has been replaced by the `startTime={min=0, max= 1593018651}` filter.
- `minEndTime`/`maxEndTime` has been replaced by the `endTime={min=0, max= 1593018651}` filter, enabling you to also filter for events without the `endTime` set: `endTime={isNull=true}`.
- `minCreatedTime`/`maxCreatedTime` has been replaced by the `createdTime={min=0, max= 1593018651}` filter.
- `minLastUpdatedTime`/`maxLastUpdatedTime` has been replaced by the `lastUpdatedTime={min=0, max= 1593018651}` filter.
- `assetSubtrees` has been replaced by the `assetSubtreeIds=[{id=754173880412890},{externalId="23-TE-96148"}]` filter which introduces support for `Id`/`ExternalId` input.
- These filters are no longer supported: `sort`, `dir`, `limit`, `offset`, `sourceId`.
- See the full list of [supported filters](https://docs.cognite.com/api/v1/#operation/advancedListEvents) for the `events{}` expression.

### Templating

- New filters: `parentIds`, `parentExternalIds`, `rootIds`, `dataSetIds`, `externalIdPrefix`, `root`.
- The `description` field supports only regular expression operators `=~`, `!~`, and `!=`.
- Select assets based on **label**: `labels={contains={externalId="pump"}}`, `labels={containsAny=[{externalId="pump_type_A"},{externalId="pump_type_B"}]}`, `labels={containsAll=[{externalId="pump"},{externalId="rust_detected"}]}`
- `assetSubtrees` replaced by the `assetSubtreeIds=[{id=754173880412890},{externalId="23-TE-96148"}]` filter which introduces support for `Id`/`ExternalId` inputs.
- `minCreatedTime`/`maxCreatedTime` has been replaced by the `createdTime={min=0, max= 1593018651}` filter.
- `minLastUpdatedTime`/`maxLastUpdatedTime` has been replaced by the `lastUpdatedTime={min=1592222651, max= 1593018651}` filters.
- These options are no longer supported: `query`, `sort`, `dir`, `offset`, `boostname`, `path`, `depth`, `sourceId`.
- See the full list of [supported filters](https://docs.cognite.com/api/v1/#operation/listAssets) for the `assets{}` expression.

### CODE REVIEW

**Comment by daniellee** [comment]
Hi @polomani,

Impressive update! I have started reviewing and it mostly looks fine so far. The links to the docs site weren't working yesterday but seem to work today. 

Just one small thing that I noticed straight away - there is a broken link in the readme: https://raw.githubusercontent.com/cognitedata/cognite-grafana-datasource/docs/dashboard-development/images/readme/image2.png

Also have a question about custom queries. Why am I getting a syntax error with the new version of the data source - is this a breaking change and should `ts` be used instead of `asset` now?

image

**Comment by polomani** [comment]
@daniellee Hi! Thanks you for reviewing!

> Just one small thing that I noticed straight away - there is a broken link in the readme
I believe it's fixed now? It goes to a non-master branch, but shouldn't be a bit issue

>  is this a breaking change and should ts be used instead of asset now?
Yes, we have a number of breaking changes. You can find some documentation about the new syntax under the `(i)` button.
I believe something that you are trying to do looks more like: `ts{assetIds=[$test]}`

**Comment by polomani** [comment]
@daniellee a bit technical question.  could `gf-form-dropdown`.`get-options` callback return array where each item has `value` of type number? 
going through the pr myself and noticed this line
```
value: type === Tab.Timeseries ? id : id.toString()
```
which I am not sure why was introduced and if it behaves properly

**Comment by polomani** [comment]
@daniellee we found an issues related to question above.
I pushed a hotfix to this PR, the source code is here:
https://github.com/cognitedata/cognite-grafana-datasource/pull/120/files

**Comment by daniellee** [comment]
@polomani the fix works for me.

Unfortunately, the get-options function for metric segments only returns the text (https://github.com/grafana/grafana/blob/master/public/app/core/directives/metric_segment.ts#L222). In the future, I'd recommend moving away from the metric segment component and using one of the new React components ([Select](https://developers.grafana.com/ui/latest/index.html?path=/story/forms-select--basic-select-async) or the [Cascader](https://developers.grafana.com/ui/latest/index.html?path=/story/forms-cascader--with-initial-value)

## Functionality

Everything looks good - this is a very ambitious plugin. The three different ways of querying all work well and the templating works. Nice work with the help section for template variable queries (and the first step towards migrating to React)

The only thing I got stuck on was that it was a bit hard to figure out the metadata properties for an asset and I had to use the Chrome developer tools to figure out what they were.

- In the [docs](https://docs.cognite.com/cdf/dashboards/guides/grafana/variables.html), you recommend using the `${variable:csv}` formatting option but you can set that as default for the Cognite data source when [replacing](https://github.com/cognitedata/cognite-grafana-datasource/blob/master/src/datasource.ts#L165). There is a third parameter for format:

    ```
    this.templateSrv.replace(query.trim(), scopedVars, 'csv')
    ```
## Code

You have a lot of typing (which is great). The [@grafana/data](https://grafana.com/docs/grafana/latest/packages_api/data/) library might help with removing some boilerplate. (See here for an [example](https://github.com/grafana/simple-datasource/blob/master/src/DataSource.ts))

Generally the structure looks good. The datasource.ts class is much smaller and nicely refactored. The connector class with chunking and caching looks really nice. The parser functionality lifts this plugin to be one of the most advanced Grafana plugins.

We will support Angular for a long time but if you are interested in converting the query editors and config page to React then we could help. The rest of the code will work well in a React plugin. There is also some tooling in the @grafana/toolkit that you could also start using (though your current webpack and jest configs look good). 

Merged and published! Great work.

**Comment by polomani** [comment]
@daniellee thanks a lot for a comprehensive review and suggestions!
I can see the plugin on the market place now and it feels quite revealing a after a few months of work :)

We will consider suggested improvements for the next iterations.
There is no one in our team who knows angular, however we can do react :)
Is there a migration guide anywhere? Or maybe someone's pr?

**Comment by wardbekker** [comment]
@polomani We do have a tutorial on how to build a panel plugin with react: https://grafana.com/tutorials/build-a-panel-plugin/ . Perhaps @daniellee also knows some additional resources that can be helpful here.

**Pull request merged**
