### PR TITLE
Add pierosavi-imageit-panel to repo.json

### PR DESCRIPTION
**Pull request by pierosavi**
Started as a fork of PictureIt (now sadly abandoned), a lot of improvements like support for grafana 5/6 and draggable sensors on picture

### CODE REVIEW

**Comment by alexanderzobnin** [comment]
@pierosavi I get this error when navigating _Value Color Mapping_ tab:
```
angular.js:14700 DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('panel-editor-tab-pierosavi-imageit-panelvalue-color mapping') is not a valid name.
    at t.addDirective (http://localhost:3004/public/build/app.469095018b321ef1da7c.js:1:94632)
    at t.link (http://localhost:3004/public/build/app.469095018b321ef1da7c.js:1:94842)
    at Object.link (http://localhost:3004/public/build/app.469095018b321ef1da7c.js:1:95087)
    at http://localhost:3004/public/build/vendor.469095018b321ef1da7c.js:130:7414
    at http://localhost:3004/public/build/vendor.469095018b321ef1da7c.js:130:55088
    at Ne (http://localhost:3004/public/build/vendor.469095018b321ef1da7c.js:130:55145)
    at ie (http://localhost:3004/public/build/vendor.469095018b321ef1da7c.js:130:50579)
    at http://localhost:3004/public/build/vendor.469095018b321ef1da7c.js:130:43466
    at http://localhost:3004/public/build/vendor.469095018b321ef1da7c.js:130:43483
    at http://localhost:3004/public/build/vendor.469095018b321ef1da7c.js:130:42679 "<panel-editor-tab editor-tab="tab" ctrl="ctrl" index="$index">"
(anonymous) @ angular.js:14700
(anonymous) @ angular.js:11142
Ne @ angular.js:10547
ie @ angular.js:9934
(anonymous) @ angular.js:9174
(anonymous) @ angular.js:9177
(anonymous) @ angular.js:9039
(anonymous) @ angular.js:9430
r @ angular.js:9217
k @ angular.js:9984
(anonymous) @ angular.js:27856
$digest @ angular.js:18260
$apply @ angular.js:18531
(anonymous) @ angular.js:27346
dispatch @ jquery.js:5183
g.handle @ jquery.js:4991
```

**Comment by pierosavi** [comment]
@alexanderzobnin the issue is now fixed in 0.0.2.
It worked in grafana v6 somehow before but not in v5

**Comment by pierosavi** [comment]
> When enabling "Use Label Grouping"
> 
> image
> 
> I'm seeing an error:
> 
> image

This is now fixed in 0.1.0 with the new value mapping feature

Also the circle-ci check is failing for 
> Updated version should be greater than previous: 0.1.0 < 0.2.1 (plugin: xginn8-pagerduty-datasource)
 
?

**Comment by briangann** [comment]
> Also the circle-ci check is failing for
> 
> > Updated version should be greater than previous: 0.1.0 < 0.2.1 (plugin: xginn8-pagerduty-datasource)

bug in the script, will take a look at it.

**Comment by briangann** [comment]
circleci is stuck on change d66de18e96aa16319458a78db1562053cc9e8e26, the script is ok, and the diff looks ok

**Comment by briangann** [comment]
published!

**Pull request merged**
