### PR TITLE
Crate data source v0.5.1

### PR DESCRIPTION
**Pull request by alexanderzobnin**

### CODE REVIEW

**Comment by daniellee** [comment]
Hi @alexanderzobnin can you update the version number to 0.5.1 in the plugin.json -> https://github.com/raintank/crate-datasource/blob/master/dist/plugin.json#L27

**Comment by alexanderzobnin** [comment]
@daniellee sorry, forgot to build it before publishing.

**Comment by alexanderzobnin** [comment]
@daniellee check it now, please

**Comment by daniellee** [comment]
Merged and published: https://grafana.com/plugins/crate-datasource

**Pull request merged**
