### PR TITLE
Release prometheus-alertmanager-datasource 1.0.0

### PR DESCRIPTION
**Pull request by cryptobioz**

### CODE REVIEW

**Review by SonyViao — APPROVED** [review]

**Comment by marcusolsson** [comment]
Could you update the PR to the format listed in the [README](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson)?

**Comment by marcusolsson** [comment]
The [plugin validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/?url=https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource/releases/download/1.0.0/camptocamp-prometheus-alertmanager-datasource-1.0.0.zip) reports a few issues for the plugin.

Since this is an already published plugin, we can't do much about the invalid plugin ID, but could you have a look at the other issues?

**Comment by cryptobioz** [comment]
Yes, @el-psycho did an awesome work regarding those issues (cf. https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource/pull/96). However, I was worried about the plugin ID. What do you think would be the best: create a new plugin (with a new plugin ID) from this release or keep the badly formatted plugin ID?

**Comment by karlism** [comment]
@marcusolsson, can you please look into this?

**Comment by marcusolsson** [comment]
Even if the plugin ID doesn't abide by the naming conventions, it will still work as expected. For now I don't recommend changing the plugin ID as it would create duplicate entries on the marketplace. We have a few other plugins that was published with an incorrect plugin ID. If this becomes an issue in the future, we'll let you know.

**Comment by cryptobioz** [comment]
Thank you @marcusolsson! I updated the plugin in order to make it pass the validation (except the plugin ID). Could you please have a look at it?

**Comment by marcusolsson** [comment]
I've reviewed the plugin, and the only comment I have is that you're targeting 7.1.x which means you're only targeting patch releases of 7.1. This is likely not what you intended. I think you want something like `>=7.1.0` instead?

**Comment by cryptobioz** [comment]
Thanks @marcusolsson, I just updated my code and the PR.

**Comment by marcusolsson** [comment]
Thank you! Though it seems like something went wrong while packaging this. It looks like the archive is empty?

**Comment by cryptobioz** [comment]
Sorry, I made a mistake, it should be fixed now

**Comment by marcusolsson** [comment]
I'm getting a few validation errors with the new packaged plugin. Could you run it through the [plugin validator](https://plugin-validator.grafana.net/) and address the issues (apart from the plugin ID error)?

**Comment by gorSign** [comment]
...waiting for signed prometheus-alertmanager datasource v1.0.0.

**Comment by cryptobioz** [comment]
@marcusolsson @attachmentgenie 
The plugin is now signed and some errors have been fixed. Is it good for you?

**Comment by attachmentgenie** [comment]
@cryptobioz i have no power to approve anything nor understand the inner working of the approval process, i am just really interested in getting this released.

I proposed a fix one of those checks in camptocamp/grafana-prometheus-alertmanager-datasource/pull/104 the other 2 just seem to choke on the fact that this datasource has an additional '-' in its name.

however my original comment still stands, the current CI error still requires you to rebase to $latest, but @marcusolsson would be much better suited to confirm this

**Comment by cryptobioz** [comment]
Thanks for your help @attachmentgenie, I updated the release archive and rebased the PR.

**Comment by marcusolsson** [comment]
Published! 🎉

**Comment by gorSign** [comment]
Still can't use prometheus-alertmanager-datasource 1.0.0, (-e "GF_INSTALL_PLUGINS=camptocamp-prometheus-alertmanager-datasource 1.0.0"), I got this error:
Error: ✗ Failed to find requested plugin, check if the plugin_id is correct: 404 not found error

Grafana v7.5.3. is used, need to use new wersion? Which one?

**Comment by marcusolsson** [comment]
Can you install it with the following?

```
grafana-cli --pluginUrl https://grafana.com/api/plugins/camptocamp-prometheus-alertmanager-datasource/versions/1.0.0/download plugins install camptocamp-prometheus-alertmanager-datasource
```

**Comment by gorSign** [comment]
Tried this:

    # docker exec -it it_grafana /bin/bash
    bash-5.0$ grafana-cli --pluginUrl https://grafana.com/api/plugins/camptocamp-prometheus-alertmanager-datasource/versions/1.0.0/download plugins install camptocamp-prometheus-alertmanager-datasource
    installing camptocamp-prometheus-alertmanager-datasource @
    from: https://grafana.com/api/plugins/camptocamp-prometheus-alertmanager-datasource/versions/1.0.0/download
    into: /var/lib/grafana/plugins
    
    ✔ Installed camptocamp-prometheus-alertmanager-datasource successfully
    
    Restart grafana after installing plugins . <service grafana-server restart>
    
    bash-5.0$ exit
    exit
    # docker restart it_grafana

After it in Grafana there were no 1.0.0 version, only visible "update available", after I made:
    # docker exec -it it_grafana /bin/bash
    bash-5.0$ grafana-cli plugins update camptocamp-prometheus-alertmanager-datasource
    Removing plugin: camptocamp-prometheus-alertmanager-datasource
    installing camptocamp-prometheus-alertmanager-datasource @ 1.0.0
    from: https://grafana.com/api/plugins/camptocamp-prometheus-alertmanager-datasource/versions/1.0.0/download
    into: /var/lib/grafana/plugins
    
    ✔ Installed camptocamp-prometheus-alertmanager-datasource successfully
    
    Restart grafana after installing plugins . <service grafana-server restart>
    
    bash-5.0$ exit
    exit
    # docker restart it_grafana

Now I could see v1.0.0:
image

Why approach with GF_INSTALL_PLUGINS doesn't work?

**Comment by marcusolsson** [comment]
Grafana returns a 404 if your Grafana version isn't satisfied by the grafanaDependency of the plugin. I see that the grafanaDependency for the plugin has a space in it, `>= 7.1.0`, which I suspected could have an impact. But then it should fail when using grafana-cli as well.

**Pull request merged**
