### PR TITLE
Add New plugin for Continuous Delivery Director

### PR DESCRIPTION
**Pull request by ashlomi**
This is a new plugin for the Continuous Delivery Director of CA (a Broadcom Company) - https://cddirector.io

### CODE REVIEW

**Comment by ashlomi** [comment]
This pul request is in order to sign the plugin. 
Once the plugin will be signed, we will be able to create the ZIP and add the download section.

**Comment by ashlomi** [comment]
Hi @briangann - can you please advise what the process to create a public signature is?
I couldn't find it in the documentation.

**Comment by zuchka** [comment]
Hi @ashlomi 

After the initial review of your plugin the team will add a stub to your Grafana Organization's Account with the proper signature level configured. Then you can follow the steps to sign your plugin and resubmit for final publication.

We are experiencing a slight backlog right now as we move through the Summer months but things will pick up soon 👍

**Comment by marcusolsson** [comment]
Hi,

I'm missing a URL to the packaged plugin you wish to submit for review.

To package a plugin, refer to the documentation: https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/

Once we've reviewed your plugin, we'll assign a signature level for your plugin so that you can create the plugin signature.

I have a couple of questions in order to help us review your plugin:

- Continuous Delivery Director seems to be a commercial offering. Is there an open source version that users can run themselves, or would they need purchase a subscription?
- Are you affiliated with CA Technologies/Broadcom?

Official plugins for strictly commercial offerings require a commercial signature, which can be purchasing a plugin subscription from Grafana Labs. If this would be of interest to you, please let me know and I'll let a representative contact you with more information.

**Comment by itai-broadcom** [comment]
Hi @marcusolsson,
1. The link to package a plugin has a step of signing it. To package by skipping this step?
2. Following the instructions to package, as you can see in the attached image, running `yarn build` fails with the following error. Note that `yarn dev` succeeds. How can this be fixed?
Thanks!

screenshot grafana yarn build

**Comment by ashlomi** [comment]
Hi Marcus, 

In addition to Itai's answers - 
- Indeed Continuous Delivery Director (CDD) is a commercial product, however, the plugin to grafana is not billable. CDD is not an open-source product, but we have a freemium offering, and users can use CDD for free with Grafana. 
- Yes. I am the Continuous Delivery Director product manager. My work email is assaf.shlomi@broadcom.com.

**Comment by marcusolsson** [comment]
Hi @ashlomi,

We're deprecating this repository in favor of the new submission process. Could you please submit your plugin from your Grafana Cloud account? More information is available in the README for this repository.

**Pull request closed without merging**
