### PR TITLE
ClickHouse Database datasource plugin update to 2.2.0

### PR DESCRIPTION
**Pull request by Slach**
# 2.2.0 (2020-11-30)
## Enhancement:

* add region support to annotation query, try to fix wrong column orders for table format, fix https://github.com/Vertamedia/clickhouse-grafana/issues/303
* add plugin sign process, fix https://github.com/Vertamedia/clickhouse-grafana/issues/212
* add `DateTime64` support, fix https://github.com/Vertamedia/clickhouse-grafana/issues/292
* add `linux\arm64` backend plugin build
* improve ARRAY JOIN parsing, fix https://github.com/Vertamedia/clickhouse-grafana/issues/284
* improve `docker-compose.yaml` add ability to redefine `GRAFANA_VERSION` and `CLICKHOUSE_VERSION` via environment variables `latest` by default

## Fixes:
* add `*.js.map` and `*.js` from src and spec folder to .gitignore
* don't apply adhoc filters twice when used $adhoc macros, fix https://github.com/Vertamedia/clickhouse-grafana/issues/282
* fix corner case for table format with wrong columns order between meta and data response section, fix https://github.com/Vertamedia/clickhouse-grafana/issues/281
* add trickster to docker-compose environment
* actualize links in README.md

Signed-off-by: Eugene Klimov <eklimov@altinity.com>

### CODE REVIEW

**Comment by marcusolsson** [comment]
Hi @Slach,

Since Grafana 7.3, we've changed how we package plugins. For more information, refer to [Package a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/).

You can enter the URL to the plugin archive in the [plugin validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/?url=https://github.com/Vertamedia/clickhouse-grafana/archive/2.2.0.zip) to see if it's ready to be published. Let me know if you have any questions!

**Comment by Slach** [comment]
@marcusolsson please look at this PR again, currently, all `plugin-validator` checks passed

**Comment by Slach** [comment]
@marcusolsson any news about this Pull Request?

**Comment by Slach** [comment]
@marcusolsson please merge this pull request

**Comment by Slach** [comment]
@marcusolsson could you look at this PR again? 
anything else that I should do to able this PR to merge?

**Comment by marcusolsson** [comment]
Hi @Slach,

Just got back from the holidays 👋 Will take a look at this in the coming days!

**Comment by marcusolsson** [comment]
It looks like you're affected by a bug in the sign command where grafana-toolkit generates invalid paths in the MANIFEST.txt (I believe this bug appears when running the sign command on a Windows machine). For more information, refer to https://github.com/grafana/grafana-plugin-repository/pull/798#issuecomment-741663511.

Could you please update the manifest with the changes listed below?

In the MANIFEST.txt, change the double backslash, `\\`, in the file names to a forward slash, `/`.

For example, change:

```
"img\\annotations.png": "09cc19df992fede5c4dd830f7b3c7a783702feced07ea9693d417ec127077b00",
```

into

```
"img/annotations.png": "09cc19df992fede5c4dd830f7b3c7a783702feced07ea9693d417ec127077b00",
```

**Comment by Slach** [comment]
@marcusolsson done
please check and merge pull request

**Comment by Slach** [comment]
@marcusolsson 
https://app.circleci.com/pipelines/github/grafana/grafana-plugin-repository/776/workflows/1f099572-d903-4a7f-8b3a-2ac101f17731/jobs/2957/parallel-runs/0/steps/0-105

what exactly means "README.md not found"
where exactly your tool try to find README.md?
it already exists in fresh uploaded ZIP file

image

**Comment by Slach** [comment]
@marcusolsson and README.md already contains in github https://github.com/Vertamedia/clickhouse-grafana/tree/67e5b7f80cfe5198db9ac8fdabfe2d70c7f2aaa1

**Comment by marcusolsson** [comment]
I can see that you've fixed the MANIFEST file. Unfortunately, I'm still getting a warning about a "Modified signature" when I try to load it. 

Screen Shot 2021-01-05 at 18 45 15

I _think_ the errors are due to an unsupported archive structure. It looks like the plugin assets are located at the root of the ZIP archive instead of in a directory named as the plugin ID.

Could you verify that you've packaged your plugin according to the instructions on [Package a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/), i.e.:

```
yarn build
mage
mv dist/ vertamedia-clickhouse-datasource
zip vertamedia-clickhouse-datasource-2.2.0.zip vertamedia-clickhouse-datasource -r
```

For future reference, I recommend that you take a look at the [GitHub Actions](https://github.com/grafana/plugin-workflows) for building, testing, and packaging plugins. It should make life easier :)

**Comment by Slach** [comment]
@marcusolsson  done
image
please merge

**Comment by Slach** [comment]
@marcusolsson could you suggest when a bug in the signing process will fix and `npx @grafana/toolkit plugin:sign` will work properly in all OSes?

**Comment by marcusolsson** [comment]
Thank you for your patience and for fixing the issues so quickly! I can confirm that the plugin is packaged correctly. Marking this as ready for review. You can see your current position in the review queue on the [project board](https://github.com/grafana/grafana-plugin-repository/projects/2).

I'm not aware of a fix at the moment, but I will check with the plugin team tomorrow for when this can be fixed.

**Comment by marcusolsson** [comment]
[Published](https://grafana.com/grafana/plugins/vertamedia-clickhouse-datasource?pg=plugins&plcmt=featured-undefined&version=2.2.0)! 🎉

**Comment by marcusolsson** [comment]
@Slach FYI, here's the pull request for the issue with the invalid MANIFEST.txt: https://github.com/grafana/grafana/pull/30287

**Comment by Slach** [comment]
@marcusolsson thanks a lot for suggestion

**Pull request merged**
