### PR TITLE
Logstreaming Plugin

### PR DESCRIPTION
**Pull request by Chris7**
This adds in a plugin that can stream data from a data source into a panel. It is useful for log aggregation across multiple services.

### CODE REVIEW

**Comment by daniellee** [comment]
Sorry for the delay here. I will be back home after travelling next week and will get back to you with feedback then. This looks very interesting!

**Comment by daniellee** [comment]
Noticed that the plugin id is not following the [plugin id convention](http://docs.grafana.org/plugins/developing/code-styleguide/#plugin-json-mandatory).

`ginkgobioworks-grafana-logstream` should be `ginkgobioworks-logstream-panel` in the plugin.json file.

**Comment by Chris7** [comment]
Thanks for the check, fixed the id.

**Comment by daniellee** [comment]
@Chris7 could you explain how to use this plugin? To get streaming data does it rely on the auto refresh in Grafana? 

I tried with autorefresh every 5 seconds but I couldn't see that toggling the tail function did anything. Think I'm missing something here :-)

**Comment by Chris7** [comment]
It should populate whatever is present from the query time. If you have a datasource like elasticsearch, use the raw document metric, then choose the columns to display in options. It works very much like the table display.

**Comment by daniellee** [comment]
aha, got totally tricked by the name and was searching the code for streaming functionality (like the Snap plugin has). Will get back to you with feedback soon. Thanks for your patience!

**Comment by daniellee** [comment]
Here's my feedback so far:

### Meta Data

- This [image link](https://github.com/ginkgobioworks/grafana-logstream/blob/master/dist/plugin.json#L15) in the plugin.json is incorrect. The link should be relative to the plugin.json file in the dist directory. One way to solve this is to create a src directory in the dist directory - an example [here](https://github.com/grafana/worldmap-panel/tree/master/dist/src/images).

- The plugin.json should contain a link to the GitHub project.

- The README.md should explain a bit more what the plugin does. (Just a little intro paragraph at the start - explain that it is an alternative to the table panel).

### Plugin

- The Sanitize HTML option in the column styles for strings does not work.

So just a few small changes and we're good to go! Thanks again for your patience.

**Comment by daniellee** [comment]
Followup on the image link. It is easier to just move the plugin.json into the src directory instead of changing the link.

**Comment by Chris7** [comment]
Hi @daniellee,

With respect to point 2, does https://github.com/ginkgobioworks/grafana-logstream/blob/master/dist/plugin.json#L18 not do that?

**Comment by daniellee** [comment]
Aha, there is no plugin.json in the dist directory. That's why there was no link. Grafana loads the plugin from the dist subdirectory if it exists so everything the plugin needs must be in the dist directory.

**Comment by Chris7** [comment]
Yes, I moved it per your suggestion :). I'll rebundle it

**Comment by daniellee** [comment]
Sorry for the confusion here. The idea with a src and dist directory is that src is for development files and dist is for the minified/compiled/built files. The build step typically uses the src files to build the dist files (either by copying or generating a new compiled version). Everything the plugin needs should be in the dist directory. If there is a dist directory then that is the code that Grafana will attempt to load. It will ignore the src directory.

Right now the src and dist directories have some differences. The plugin.json file and img subdirectory are not in the dist directory. Also, the libs subdirectory is not in the src directory.

**Comment by Chris7** [comment]
I updated the dist directory with a new release. By the libs subdir, do you mean bower_components/node_modules? They aren't related to the project and shouldn't be in the src directory. Grunt takes care of bundling whatever code is necessary and puts it all in dist.

**Comment by daniellee** [comment]
Thanks for your patience! Could you fix the incorrect link to the image in the plugin.json file here: https://github.com/ginkgobioworks/grafana-logstream/blob/master/dist/plugin.json#L15

**Comment by daniellee** [comment]
@Chris7 did you ever get time to fix that last error?

**Comment by Chris7** [comment]
@daniellee 

I believe it is fixed, the image exists at the path (relative to `dist`).

**Comment by Chris7** [comment]
I just updated the commit hash in the PR.

**Comment by daniellee** [comment]
Sorry about that - I totally missed that you had made an update.

**Comment by daniellee** [comment]
I apologize for the long delay on giving feedback. This panel does not work with Grafana 5.x as the dashboard grid now uses a different component so the height calculations in the plugin will not work anymore.

Are you still interested in getting this published?

**Comment by daniellee** [comment]
Closing this - let me know if you want to reopen.

**Pull request closed without merging**
