### PR TITLE
added diagram v1.4.0

### PR DESCRIPTION
**Pull request by jdbranham**

### CODE REVIEW

**Comment by jdbranham** [comment]
tagging @daniellee

**Comment by daniellee** [comment]
Hi Jeremy,

Sorry for the delay, we've had a hectic week or so getting ready for GrafanaCon but now I'm back in action. Could you bump the version in the plugin json files to 1.4.0. It's still [1.3.0](https://github.com/jdbranham/grafana-diagram/blob/master/dist/plugin.json#L17) right now.

Thanks!

**Comment by jdbranham** [comment]
Done, thanks @daniellee !

**Comment by daniellee** [comment]
Can you bump it up in the plugin.json in the dist directory too as that is the one used by Grafana:

https://github.com/jdbranham/grafana-diagram/blob/master/dist/plugin.json#L17

Thanks!

**Comment by jdbranham** [comment]
I'm slackin! =]
Thanks @daniellee

**Comment by daniellee** [comment]
Seeing some artifacts with the data values under the text in the diagram:

image

with this diagram definition:

graph LR
Countries((This is the text in the circle2)) --> SE
Countries --> IE
Countries --> HI
Countries --> US

Is it because the labels (IE, SE, US) are narrower than the data values? 

Anyway, published and merged. Great to see the plugin advancing so much.

**Pull request merged**
