### PR TITLE
Update btplc-alarm-box-panel

### PR DESCRIPTION
**Pull request by benthorner**
Add Values tab to btplc-alarm-box-panel to allow advanced users to change the way the display and color values are calculated.

### CODE REVIEW

**Comment by daniellee** [comment]
Sorry for the delay. Got an error when generating a thumbnail from one of the images and haven't had time to investigate it yet - not sure if the problem is with the image or with our code :grimacing:

**Comment by daniellee** [comment]
It is a bug in the grafana.com api. I have sent a fix so I should be able to publish this later today.

**Comment by daniellee** [comment]
Merged and published!

**Comment by benthorner** [comment]
Thanks Dan - that's great!

**Pull request merged**
