### PR TITLE
Added Ambari Metrics Datasource

### PR DESCRIPTION
**Pull request by prajwalrao**
Datasource Plugin for Ambari Metrics System including various dashboards.

### CODE REVIEW

**Comment by DanCech** [comment]
Thanks for the PR!

You'll need to make a couple of adjustments before we can import this plugin, specifically updating the plugin id in both your plugin.json and here in the PR.  A valid plugin id would be something like `prajwalrao-ambari-datasource`.

You'll also want to remove the 1.0.0 release from the PR, since it references a commit hash that will have the wrong plugin id, and update your README.md to include a description at the top of the functionality of the datasource, and add the instructions for installing from grafana.net.  An example of this would be https://grafana.net/plugins/fastweb-openfalcon-datasource

**Comment by prajwalrao** [comment]
@DanCech Thanks Dan. I'll do the changes and update the PR.

**Comment by prajwalrao** [comment]
@DanCech I've updated the PR and made the suggested changes

plugin-repo
- updated plugin-id
- removed older version
- updated hash

plugin.json
- edited readme to include description
- added screenshot

**Comment by DanCech** [comment]
@prajwalrao looking much better, you just need to update the `plugin.json` in your repo to have the correct plugin id `praj-ams-datasource` (rather than `ambari-metrics`) and to reference yourself as the author rather than the Ambari project.

**Comment by prajwalrao** [comment]
@DanCech Done.

**Comment by DanCech** [comment]
@prajwalrao Thanks! It's now live at https://grafana.net/plugins/praj-ams-datasource

**Pull request merged**
