### PR TITLE
Radar Panel v1.4.4 (20/Apr/2019)

### PR DESCRIPTION
**Pull request by snuids**
# Radar Panel
## v1.4.4 (20/Apr/2019)
- Autoscale option added
- Tick background can be hidden

### CODE REVIEW

**Comment by alexanderzobnin** [comment]
@snuids Looks good, but I see that version in `plugin.json` is `1.4.3`. Is it right?

**Comment by snuids** [comment]
I made a new version 1.4.4 since my last pull request attempt.

So there should be two tags with two commits that match the two versions.

Cheers,

**Comment by alexanderzobnin** [comment]
Aha, OK, I see.

**Comment by snuids** [comment]
Good thx :-)

**Pull request merged**
