### PR TITLE
New version of bubble chart.

### PR DESCRIPTION
**Pull request by digrich**
Releasing v1.1.0 of a bubble chart. It is fixing all open issues and also making it compatible with 5.0.0 Grafana release.

### CODE REVIEW

**Comment by daniellee** [comment]
I was maybe a bit too quick at publishing this. It's great to see all the changes and it works fine for me in 5.0. But can you explain what this commit is doing:

https://github.com/digrich/bubblechart-panel/commit/a08093a704c24abff592827968d7590130beeded

**Comment by daniellee** [comment]
I disabled the new version for now.

**Comment by digrich** [comment]
It keeps track of plugin usages through google analytics. I am not sure if this allowed for grafana plugins.

**Comment by digrich** [comment]
@daniellee What you suggest for google analytics code?

**Comment by daniellee** [comment]
@digrich For a published open source plugin on Grafana, I don't think it is ok. I know it is sort of annoying to not be able to see exactly what users are doing but that is just how it is with open source - people do expect their open source monitoring software to be tracking them.

We haven't made it public yet (we will soon once we have finished moving play.grafana.org) but we have some very basic plugin downloads and plugin install stats. Grafana sends some very basic stats once a day if it is not turned off or if the Grafana instance is not behind a firewall. Here are the last 30 days for the bubblechart:

image

This means there are approximately 1200 Grafana instances with the bubblechart plugin installed. (Although the real number is probably 20-30% higher).

**Comment by digrich** [comment]
Thanks, @daniellee. I have removed the google analytic code and created a new PR
https://github.com/grafana/grafana-plugin-repository/pull/233

It's a great idea, to make these stats public for everyone. I was also trying to get the similar information but it's good, you guys are already having that stats and planning to make it public.

**Comment by digrich** [comment]
@daniellee Can you please merge the new PR and enable the plugin? People are trying to download the new version and they are not seeing it under https://grafana.com/plugins

**Pull request merged**
