### PR TITLE
Update 'pr0ps-trackmap-panel' to v2.1.2

### PR DESCRIPTION
**Pull request by pR0Ps**
- Ignore coordinates of (0, 0)
 - Fix displaying hover dot in Grafana v7.4.0+
 - Fix rendering lines that cross the antimeridian

### CODE REVIEW

**Comment by marcusolsson** [comment]
Could you please update your PR to the [following format](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson):

```
{
  "id": "briangann-gauge-panel",
  "type": "panel",
  "url": "https://github.com/briangann/grafana-gauge-panel",
  "versions": [
    {
      "version": "0.0.8",
      "url": "https://github.com/briangann/grafana-gauge-panel",
      "download": {
        "any": {
          "url": "https://github.com/briangann/grafana-gauge-panel/releases/download/v0.0.8/briangann-gauge-panel-0.0.8.zip",
          "md5": "782c973460f330287b7efca5486aa015"
        }
      }
    }
  ]
}
```

Once you've updated your PR, make sure you paste the URL to the ZIP archive into the [plugin validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/) to make sure it's ready for review.

**Comment by pR0Ps** [comment]
@marcusolsson I've updated the PR to comply with the new format.

The plugin check doesn't like the relative links in the README but everything else is fine. I'd like to keep the URLs relative since I don't want to create a hard dependency on an external image hosting service or use GitHub as a CDN. The solution I used previously (see https://github.com/grafana/grafana-plugin-repository/pull/364#issuecomment-470278681 for details) seems to still work.

**Comment by marcusolsson** [comment]
While your fix works when displaying the README inside Grafana, it results in broken images on grafana.com/plugins.

Screenshot 2021-03-22 at 11 55 52@2x

It's not a great experience for anyone browsing the plugin marketplace, but since it's already published I don't consider it a blocker.

**Comment by pR0Ps** [comment]
Ah, I see. I'm fine with that since the screenshots are still shown in the carousel above.

In the future I'd like to figure out a way to make this work better. Maybe Grafana could rewrite relative links in the readme files depending on the context? That way links would be valid URLs while still working on instances with no external internet access.

**Comment by MatinF** [comment]
@marcusolsson is there a rough ETA on this merge? We have a lot of users that are dependent on this feature. Thanks for your work!

**Comment by MatinF** [comment]
Any updates on this would be really great

**Comment by marcusolsson** [comment]
Hi @MatinF,

This plugin is currently at the top of plugins waiting to be reviewed. We'll start reviewing this as soon as we clear up some of the ones that are currently in review. You can see the pipeline on the [project board](https://github.com/grafana/grafana-plugin-repository/projects/2).

**Review by briangann — APPROVED** [review]
looks good, was able to load up plugin with sample data, tested against v7.5.2

**Comment by briangann** [comment]
published!

**Pull request merged**
