### PR TITLE
Add vertica-grafana-datasource plugin

### PR DESCRIPTION
**Pull request by tanvipise**
Hello Grafana team,
Vertica has created a new datasource plugin with an updated framework and SDK. This plugin allows users to query and visualize data from a Vertica database.

### CODE REVIEW

**Comment by briangann** [comment]
I've updated your signature type to commercial, so you can sign it during your build process.

Can you update this PR with the zip file and new md5?  Looks like you had a release at the end of June, so you might want to make a v1.0.1 just for the new signature so existing installs will see this version.

**Comment by tanvipise** [comment]
Hi Brian, I commited the updated repo.json and it shows that the 'check-repo-update' has failed. Could you help with that? Thanks

**Comment by briangann** [comment]
you can ignore the circleci error, it's unrelated as you mentioned. i'll fix that in another pr though.

**Comment by briangann** [comment]
@tanvipise looks like the backend is using the datasource "URL" instead of the jsonData.URL parameter, and can't be provisioned from the config editor.  Using a provisioning file works, but it won't be configurable to a new install.

A provisioning file like this lets the backend connect:

```YAML
datasources:
  - name: Vertica
    version: 1
    type: vertica-grafana-datasource
    url: vertica:5433
    jsonData:
      url: vertica:5433
```

but configuring a new datasource with the config editor ends up with provisioning info like this:
```YAML
datasources:
  - name: Vertica
    version: 1
    type: vertica-grafana-datasource
    url: ""
    jsonData:
      url: vertica:5433
```

**Review by briangann — APPROVED** [review]
lgtm, datasource testing is working

**Comment by briangann** [comment]
note: the logo.svg is not visible up on grafana.com since the fill color is set to #fff (white), and in grafana light theme it is very faint

light theme:

image

dark theme:

image

**Pull request merged**
