### PR TITLE
Update innius-video-panel plugin

### PR DESCRIPTION
**Pull request by loredanaPopescu**
Hello,

I've updated my video plugin to allow iFrames with geolocation. 

Thank you :)

### CODE REVIEW

**Comment by marcusolsson** [comment]
Could you please update your PR to the [following format](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson):

```
{
  "id": "briangann-gauge-panel",
  "type": "panel",
  "url": "https://github.com/briangann/grafana-gauge-panel",
  "versions": [
    {
      "version": "0.0.8",
      "url": "https://github.com/briangann/grafana-gauge-panel",
      "download": {
        "any": {
          "url": "https://github.com/briangann/grafana-gauge-panel/releases/download/v0.0.8/briangann-gauge-panel-0.0.8.zip",
          "md5": "782c973460f330287b7efca5486aa015"
        }
      }
    }
  ]
}
```

Once you've updated your PR, make sure you paste the URL to the ZIP archive into the [plugin validator](https://plugin-validator.grafana.net) to make sure it's ready for review.

**Comment by loredanaPopescu** [comment]
Done @marcusolsson 

Thank you!

**Comment by marcusolsson** [comment]
It appears that the plugin is unsigned. Starting with 7.3 we now require all plugins to be signed before publishing them. You can read more on how to sign your plugin in the [docs](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/).

**Comment by loredanaPopescu** [comment]
Hello @marcusolsson,

I'm trying to sign the plugin but I have an error:

`> grafana-toolkit plugin:sign

  Building manifest...
  Signing manifest...
  Error: Error signing manifest: Field is required: rootUrls
      at Object.<anonymous> (\grafana-video-panel\node_modules\@grafana\toolkit\src\plugins\manifest.js:165:31)
      at step \grafana-video-panel\node_modules\@grafana\toolkit\node_modules\tslib\tslib.js:140:27)
      at Object.throw (\grafana-video-panel\node_modules\@grafana\toolkit\node_modules\tslib\tslib.js:121:57)
      at rejected (\grafana-video-panel\node_modules\@grafana\toolkit\node_modules\tslib\tslib.js:112:69)`
      
 Could you help me?
 
 Thank you!

**Comment by marcusolsson** [comment]
I can see that the plugin has been configured to be signed. Can you confirm that the API key you're using is generated from the `innius` org?

**Pull request closed without merging**
