### PR TITLE
MQTT panel plugin v0.3.1

### PR DESCRIPTION
**Pull request by ghost**
This plugin communicates with a MQTT broker through websocket to transmit and receive data.

It's used to get real time data from equipment, but can be used with anything that can send data to an MQTT broker.

### CODE REVIEW

**Comment by daniellee** [comment]
Hi @oklk 

The plugin works fine but there a few changes that need to be done before publishing.

- The README should describe the purpose of the plugin and contain steps on how to get started.
- The README should mention that this only works for websockets and that your MQTT server needs to be configured correctly to enable that.
- In the dropdown for Mqtt Mode, the receive option is spelled incorrectly
- I couldn't easily figure out how to use the Gauge mode - what format should the data from MQTT have for the gauge display?

**Comment by daniellee** [comment]
The linting error is due to the github url for the plugin having the `.git` extension.

**Comment by daniellee** [comment]
Hi @oklk any update on this?

**Comment by oklk** [comment]
Sorry, has been a little busy.
I'll check it tomorrow.

**Comment by oklk** [comment]
`Failed to fetch README.md from GitHub: NotFoundError: Couldn't load https://api.github.com/repos/gapitio/grafana-mqtt-panel/contents/src/README.md
`
Not sure why it searches for it in /src

**Comment by marcusolsson** [comment]
Looking at the commit, there doesn't seem to be a `dist` directory. This is ignored by default, but is needed to publish the plugin.

The easiest way to do this is to run:

```
yarn build
git add -f dist
git commit -m "Release v0.2.0"
```

**Comment by marcusolsson** [comment]
Hi @oklk! Since we reviewed your plugin last time, we've been developing a [tool to validate plugins](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/). Turns out we missed a few issues. Would you mind fixing the issues reported for your plugin (enter the URL to this pull request)?

**Comment by marcusolsson** [comment]
Thank you for your patience while waiting for us to review your plugin. 

We're working hard at improving the plugin experience for both users and authors. I'd like to share some important information on how to package and publish plugins going forward.

Since Grafana 7.3, we require all plugins to be _signed_. By signing your plugin, users can guarantee the integrity of the plugin and that the plugin version they've installed hasn't been modified since it was released. For more information on how to sign your plugin, refer to [Sign a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/).

With this, we now require plugins to be _packaged_ before we publish them. This means that instead of a commit containing a `dist` directory, you will need to submit a link to a ZIP archive containing your plugin. For more information on how to package your plugin, refer to [Package a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/).

Once you've packaged your plugin, you'll need to update your entry to `repo.json` to the new format. You can read more on how to do this under [Add a plugin to repo.json](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson).

To summarize, to publish your plugin, make sure that you:

1. [Sign your plugin](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/)
2. [Package your plugin](https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/)
3. Create a new GitHub release and upload the packaged plugin as a release asset
4. [Update your repo.json entry](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson)

Here's an [example](https://github.com/marcusolsson/grafana-jsonapi-datasource/releases/tag/v0.6.0) of a properly packaged plugin. In the same repository, you can find a [GitHub Action](https://github.com/marcusolsson/grafana-jsonapi-datasource/blob/master/.github/workflows/main.yml) that signs, packages, and releases the plugin whenever you create a new tag.

Once you've created a GitHub release with the packaged plugin, you can right-click the release asset, copy the link, and validate it using [the plugin validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app). 

Finally, in the November [community call](https://groups.google.com/g/grafana-developers/c/ps2vzCXRDCM/m/i7uAK1u9AQAJ), I'll be walking through the steps needed to sign and package your plugin. A recording will be made available on our [YouTube account](https://www.youtube.com/playlist?list=PLDGkOdUX1Ujo0OyE5HFffHE9GJVvaVXGs), in case you can't make it.

**Comment by ZuperZee** [comment]
Hello @marcusolsson.
Repo has been archived as it was no longer maintained and will not get any more updates.

**Comment by marcusolsson** [comment]
@ZuperZee Thank you for the update. Would you still like for this submission to be published or would you like to cancel it?

**Comment by ZuperZee** [comment]
@marcusolsson
Cancel it.

**Pull request closed without merging**
