### PR TITLE
scatter plot panel plugin - Initial release 1.0.0

### PR DESCRIPTION
**Pull request by michaeldmoore**
Ready for release, this (finally) signed, community plugin for table-formatted query data

### CODE REVIEW

**Comment by marcusolsson** [comment]
Great to see! 

With the new plugin signing process, we've updated the format for the pull request. Instead of a commit SHA, I'll have to ask you to update your PR to include a URL to a zipped archive of the built plugin. Like [this](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson):

```
{
  "id": "briangann-gauge-panel",
  "type": "panel",
  "url": "https://github.com/briangann/grafana-gauge-panel",
  "versions": [
    {
      "version": "0.0.8",
      "url": "https://github.com/briangann/grafana-gauge-panel",
      "download": {
        "any": {
          "url": "https://github.com/briangann/grafana-gauge-panel/releases/download/v0.0.8/briangann-gauge-panel-0.0.8.zip",
          "md5": "782c973460f330287b7efca5486aa015"
        }
      }
    }
  ]
}
```

Once you've created the zipped archived, you can run it through the [plugin validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/). You can also run the validator as a [CLI tool](https://github.com/grafana/plugin-validator) on your local machine.

Since this is a new plugin, I highly recommend that you look into the GitHub workflows for building, testing, signing, and packaging Grafana plugins. You can find them at [github.com/grafana/plugin-workflows](https://github.com/grafana/plugin-workflows). If you want an example on a plugin using the workflow, you can check out the [Treemap](https://github.com/marcusolsson/grafana-treemap-panel/) (or any of my other plugins).

Let me know if you run into trouble!

**Comment by michaeldmoore** [comment]
Thanks for this, I'll follow the process later today or tomorrow, so keep a
look out.

One thing I'm not sure about (the docs will probably explain this anyway)
but is this a zip file of the whole project or just the dist folder?

**Comment by marcusolsson** [comment]
Packaging a plugin consists of two commands:

```
mv dist/ michaeldmoore-scatter-panel
zip michaeldmoore-scatter-panel-1.0.0.zip michaeldmoore-scatter-panel -r
```

You can also find the instructions explained in [Package a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/).

**Comment by ryantxu** [comment]
Nice!  also check:  https://github.com/grafana/grafana/tree/master/public/app/plugins/panel/xychart

this is 'alpha' in v7.4, but will be a key feature in 8 -- currently it is not really "scatter" since the x axis gets sorted (if drawn as points it looks the same though!)

**Comment by michaeldmoore** [comment]
OK, here goes.

I got the CI workflow going (eventually, sorting out the eslint exceptions for the toolkit generated scaffolding was a bitch)
I setup the API key as a repository secret (I think I got this right), but can't figure out how to trigger the release workflow - maybe it runs whenever I checkin a new entry to the release.md?  or when the package.json version changes?  Such a mystery.  Anyway, it hasn't run yet so I signed it manually and uploaded the zip file in a closed issue (the same one I use to store the images for my readme.md).  It looks good to me.

I ran the online plugin validator, but nothing seems to happen. Rats...

Let's see how this works though, here is the json whatnot you asked for...

{
  "id": "michaeldmoore-scatter-panel",
  "type": "panel",
  "url": "https://github.com/michaeldmoore/michaeldmoore-scatter-panel",
  "versions": [
    {
      "version": "1.0.0",
      "url": "https://github.com/michaeldmoore/michaeldmoore-scatter-panel",
      "download": {
        "any": {
          "url": "https://github.com/michaeldmoore/michaeldmoore-scatter-panel/files/5860362/michaeldmoore-scatter-panel-1.0.0.zip",
          "md5": "95B6004DA7CC25D4DFFCD2E18111E333"
        }
      }
    }
  ]
}

**Comment by michaeldmoore** [comment]
Update.  I installed the plugin validator locally, and it now runs.  First issue it pointed out - I need to manually add the plugin.json to the dist folder (before renaming and zipping etc.).  The yarn build script from the toolkit scaffolding does not copy plugin.json to the dist folder.

The plugin validator still fails (see below).  I guess this is a windows and/or permissions issue.  Maybe I should just give up releasing this from a windows machine - I suspect no-one is testing any of these processes under windows.

```
C:\Users\mdmoo\Downloads\plugin-validator-master\cmd\plugincheck>plugincheck C:\grafana-plugins\michaeldmoore-scatter-panel\michaeldmoore-scatter-panel-1.0.0.zip
parse "file://C:\\Users\\mdmoo\\AppData\\Local\\Temp\\plugin_699407475.schema.json": invalid port ":\\Users\\mdmoo\\AppData\\Local\\Temp\\plugin_699407475.schema.json" after host
```

Anyway, I've uploaded the new zip file (with the plugin.json) and modified the json request (not sure what to call this)
```
{
  "id": "michaeldmoore-scatter-panel",
  "type": "panel",
  "url": "https://github.com/michaeldmoore/michaeldmoore-scatter-panel",
  "versions": [
    {
      "version": "1.0.0",
      "url": "https://github.com/michaeldmoore/michaeldmoore-scatter-panel",
      "download": {
        "any": {
          "url": "https://github.com/michaeldmoore/michaeldmoore-scatter-panel/files/5860422/michaeldmoore-scatter-panel-1.0.0.zip",
          "md5": "13D29CE14B89942303FC71F75D76F387"
        }
      }
    }
  ]
}

```

**Comment by michaeldmoore** [comment]
I've just released the update PR for my annunciator panel too - and learned
a few things in the process.

First off - I figured out how the Release action gets triggered and after a
few attempts, this seems to be working like a charm

Second - I still can't get the online plugin validator to do anything with
my zip files - I pointed it to the zip file created on github by the
release action and it still appears to do nothing.  (I will be running
ubuntu on a virtual PC later on and see if I can run the validator in house
from a unix platform.  Wish me luck)

Third - The github release action signed and zipped the plugin
successfully, and then seems to have passed the plugin validator process -
so, maybe I don't need to worry about doing that myself anymore.  Looks
good.



Now I understand how it works, I'll go back and do the same with the new
scatter plugin, so you should see an updated zip file reference and ssa
hash there soon.

I'm adding some features to Multistat, so it will be a few days before I
can release that one using this process too.

Thanks for your help.
Michael Moore

**Comment by michaeldmoore** [comment]
Closing (withdrawing) this PR in favor of the revised PR838, generated using the github release workflow

**Comment by michaeldmoore** [comment]
This for Ryan McKinley.
Your xyChart looks very interesting, and impressively concise - so little
code.  As a user though, I couldn't figure out how to add it to a dashboard
to try it out.

Unlike all the other React-based panels I've seen, xyChart is the first
I've seen that includes structured objects in the panel options.  And I
think there is a bug in Grafana concerning this that I'm running into with
my Scatter plugin which also uses options with objects.

The problem I find is that when I load a dashboard with more than one copy
of Scatter, each panel's options are loaded as expected EXCEPT any objects
take on values corresponding to the last loaded panel.  Seems like there is
a missing deepClone operation somewhere in Grafana, if only I could find it.

I've put in a logging step in the panel render function and I can see the
object all values get the same values, even though the sqlite3 database
shows each panel having differently defined option objects.

If you can, try adding two copies of xyChart on a single dashboard, with
distinct values for the dims object.  If I'm right, after saving and
reloading, you'll find they both will have the same values.

Alternatively, point me to some documentation showing how I can add an
xyChart panel to a dashboard, so I can demonstrate this myself.

Regards,
Michael Moore

**Pull request closed without merging**
