### PR TITLE
Grafana Monitoring Art datasource

### PR DESCRIPTION
**Pull request by jangaraj**

### CODE REVIEW

**Comment by daniellee** [comment]
What a creative idea for a plugin! I'll get back to you with feedback in the next day or so and hopefully get it published before GrafanaCon week starts.

**Comment by daniellee** [comment]
Hi Jan,

I obviously didn't get round to looking at this before GrafanaCon :-) But now GrafanaCon is over since yesterday.

The plugin itself works fine but there are a few things to fix in the meta data.

- The plugin id in the plugin.json file needs to follow the convention \<org\>-\<plugin name\>-\<plugin type\>. So maybe `monitoringartist-monitoringart-datasource`?
- [There is a trailing comma in the plugin.json](https://github.com/monitoringartist/grafana-monitoring-art/blob/master/src/plugin.json#L26) that Grafana doesn't like.
- The links to the images in the README.md need to be absolute or the links will be broken on Grafana.net (you can use https://raw.githubusercontent.com/monitoringartist/grafana-monitoring-art/master/ to make them absolute)

If you can get those fixed then I will publish this straight away!

**Comment by jangaraj** [comment]
Hi Daniel,

Thank you for your feedback - fixed in PR https://github.com/monitoringartist/grafana-monitoring-art/pull/1/files
I've found the problem https://github.com/monitoringartist/grafana-monitoring-art/blob/master/src/datasource.js#L147 How to return "always success" from `testDatasource` function?

**Comment by daniellee** [comment]
Getting some broken links for the screenshots:

https://github.com/monitoringartist/grafana-monitoring-art/blob/master/src/plugin.json#L23-L26

The relative links have to work from the dist directory. I'm getting a 404 for this url:

`https://raw.githubusercontent.com/monitoringartist/grafana-monitoring-art/558d9d634a94424b387cf5a7d58128ae6907c196/dist/doc/grafana-monitoring-art-monitoring-artist-logo.png:`

**Comment by jangaraj** [comment]
Thx, screenshots in plugin.json have been fixed https://github.com/monitoringartist/grafana-monitoring-art/pull/2/files

**Comment by daniellee** [comment]
Thanks for your patience! Merged and published: https://grafana.net/plugins/monitoringartist-monitoringart-datasource

**Comment by jangaraj** [comment]
Thank you. Do you have any doc, which markdown is supported in grafana.net?

**Pull request closed without merging**
