### PR TITLE
Anodot - minor readme updates

### PR DESCRIPTION
**Pull request by gooduling**
@briangann Please see the fixes to Readme

### CODE REVIEW

**Comment by briangann** [comment]
You'll need to bump the version for the panel vs changing the zip file/md5, it's already out there and there's no easy way to replace an existing release.

**Comment by gooduling** [comment]
@briangann Oh, I was sure it's fine because nothing changed except the readme and dependency. Will fix it in 5 mins

**Comment by gooduling** [comment]
@briangann Have bumped the version to 1.0.4, please see

**Review by briangann — APPROVED** [review]
lgtm

**Pull request merged**
