### PR TITLE
Update KubeGraf version to v1.5.0 

### PR DESCRIPTION
**Pull request by SergeiSporyshev**
### New Features 
* Indicate when limits or requests are not setup for application
* Add cpu/memory limits of containers to Nodes' overview page
* Indicate cpu/memory usage of pod depending on the requests & limits on Nodes' overview page
* Add cpu/memory limits of containers to deployments/statefulsets/daemonsets/pods dashboards
* Hide empty namespaces on deployments/statefulsets/daemonsets dashboards
* Add NAMESPACE for k8s-manifests [#44](https://github.com/devopsprodigy/kubegraf/issues/44)  
* Sort alerts via priority  
* Little navigations improvements
* Add hide-button for alerts' table

### Bug Fixes
* Compatibility with Grafana >= 7.3.* [#48](https://github.com/devopsprodigy/kubegraf/issues/48)
* Show memory/cpu usage of pod on pod's dashboard [#41](https://github.com/devopsprodigy/kubegraf/pull/41)
* Fix white theme on new versions of Grafana
* Fix legends on all dashboards

### CODE REVIEW

**Comment by marcusolsson** [comment]
The [plugin validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/?url=https://github.com/devopsprodigy/kubegraf/releases/download/v1.5.0.2/devopsprodigy-kubegraf-app-1.5.0.zip) reports that the plugin.json is invalid. 

It looks like the dependencies property is incorrectly placed under `info` rather than at root-level. Could you look into this?

**Comment by SergeiSporyshev** [comment]
Hi, @marcusolsson .
Ok, thanks. I'll check it asap

**Comment by SergeiSporyshev** [comment]
@marcusolsson fixed!
[new version](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/?url=https://github.com/devopsprodigy/kubegraf/releases/download/v1.5.0.2/devopsprodigy-kubegraf-app-1.5.0.zip)

**Comment by marcusolsson** [comment]
Looks good! Moving this the review queue! You can follow the progress on the [project board](https://github.com/grafana/grafana-plugin-repository/projects/2).

**Comment by SergeiSporyshev** [comment]
Thanks, @marcusolsson .
Waiting for publish!

**Comment by SergeiSporyshev** [comment]
Hi, @marcusolsson 
I found bug in your validator
In my new [case](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/?url=https://github.com/devopsprodigy/kubegraf/releases/download/v1.5.0.4/devopsprodigy-kubegraf-app-1.5.0.zip) i have message: dependencies.plugins.0: Invalid type. Expected: string, given: object
But [documentation](https://grafana.com/docs/grafana/latest/developers/plugins/metadata/#plugins) says, that it should be object

**Comment by marcusolsson** [comment]
The documentation is correct. I'm not sure why you're getting this error, as the validator web app should download the latest schema when you run it.

FYI the validator is also available as a CLI in case you want to run it on your local machine:

https://github.com/grafana/plugin-validator

I think we can ignore this error for now. Thanks for reporting this!

**Comment by marcusolsson** [comment]
[Published](https://grafana.com/grafana/plugins/devopsprodigy-kubegraf-app?version=1.5.0)! 🎉

**Pull request merged**
