### PR TITLE
add cinek810-icingaweb2-panel plugin for integration with icinga web2

### PR DESCRIPTION
**Pull request by cinek810**

### CODE REVIEW

**Comment by daniellee** [comment]
Just noticed a small thing:

The version in this PR (0.0.3) and the version (0.0.2) in the plugin.json file don't seem to match up.

**Comment by cinek810** [comment]
sorry.. should be fixed now

**Comment by daniellee** [comment]
Sorry for the long delay - Grafana 5.0 has taken up all my time the last two months. But now it is released so I will be reviewing all the plugins in the review queue now. There are links to images in the plugin.json that do not exist in the dist directory. Grafana only cares about what is in the dist directory.

- src/img/icon.svg
- src/img/icinga-logo-big.svg
- src/img/servicesList.png
- src/img/editorTab.png

If you move your plugin.json out of the root and into the src directory then the urls can be made simpler - for example: `img/editorTab.png`

**Comment by cinek810** [comment]
commited images in dist. How can I solve failing CI checks?

**Comment by daniellee** [comment]
Ignore the CI error - it's due to the merge conflict (which I will fix when I merge).

**Comment by daniellee** [comment]
My feedback so far:

## Metadata

The metadata and readme look fine.

## Plugin

- The plugin does not work when running from the dist directory (Grafana will always load the dist subdirectory if it exists and will ignore everything else in root except for the README.md file). I get a 404 error for the module.html page as it is not included in the dist. By manually copying the src/partials directory into the dist directory I could get it work.

- The options tab is neat and tidy.

- The `Icinga web2 address` field is a bit confusing. It expects an address without http/https. When I wrote `http://localhost:8009`, I did not get an error instead a call was made to: `https://http://localhost:8009`. It should also be made clear in the readme that only https is supported.

I stopped reviewing at this point as I am testing in with this docker image: https://hub.docker.com/r/jordan/icinga2/ and I will have to figure out how to enable SSL (shouldn't be too hard.)

**Comment by daniellee** [comment]
Closing this PR as there has been no response for a long time - let me know if it should be reopened.

**Pull request closed without merging**
