### PR TITLE
Add perfcurve-panel v1.3.0

### PR DESCRIPTION
**Pull request by SSKGo**
Please review perfcurve-panel plugin.
If you have any questions, please let me know it.
- Initial release to register the plugin.
- Perfcurve panel plugin allow users to plot rotating machine operation point on a performance curve.
- The validation results by the plugin validator is as below.

image

### CODE REVIEW

**Comment by marcusolsson** [comment]
Thank you for your patience while waiting for us to review your plugin. 

We're working hard at improving the plugin experience for both users and authors. I'd like to share some important information on how to package and publish plugins going forward.

Since Grafana 7.3, we require all plugins to be _signed_. By signing your plugin, users can guarantee the integrity of the plugin and that the plugin version they've installed hasn't been modified since it was released. For more information on how to sign your plugin, refer to [Sign a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/).

With this, we now require plugins to be _packaged_ before we publish them. This means that instead of a commit containing a `dist` directory, you will need to submit a link to a ZIP archive containing your plugin. For more information on how to package your plugin, refer to [Package a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/).

Once you've packaged your plugin, you'll need to update your entry to `repo.json` to the new format. You can read more on how to do this under [Add a plugin to repo.json](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson).

To summarize, to publish your plugin, make sure that you:

1. [Sign your plugin](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/)
2. [Package your plugin](https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/)
3. Create a new GitHub release and upload the packaged plugin as a release asset
4. [Update your repo.json entry](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson)

Here's an [example](https://github.com/marcusolsson/grafana-jsonapi-datasource/releases/tag/v0.6.0) of a properly packaged plugin. In the same repository, you can find a [GitHub Action](https://github.com/marcusolsson/grafana-jsonapi-datasource/blob/master/.github/workflows/main.yml) that signs, packages, and releases the plugin whenever you create a new tag.

Once you've created a GitHub release with the packaged plugin, you can right-click the release asset, copy the link, and validate it using [the plugin validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app). 

Finally, in the November [community call](https://groups.google.com/g/grafana-developers/c/ps2vzCXRDCM/m/i7uAK1u9AQAJ), I'll be walking through the steps needed to sign and package your plugin. A recording will be made available on our [YouTube account](https://www.youtube.com/playlist?list=PLDGkOdUX1Ujo0OyE5HFffHE9GJVvaVXGs), in case you can't make it.

**Comment by SSKGo** [comment]
I updated my plugin repository in accordance with the instruction.
Version 1.3.0 was released because I added MANIFEST.txt file in dist directory.
You can see the new version has passed the plugin validator in the attached file.

Additionally I resolved the conflict to merge this pull request.

If you have any questions or requests, please let me know it.

image

**Comment by marcusolsson** [comment]
Looks great! 🎉

**Comment by marcusolsson** [comment]
I took your plugin for a spin. I'm not familiar with the use case the plugin is trying to solve, so I've focused mostly on the UI/UX parts.

- The performance curve seems to work as expected, but I can't seem to plot the data from the data source. Neither as operations points or for the dynamic performance curve. I'm using the name of the fields in the data frame. Could you give me some hints where I've messed it up? :)

Screen Shot 2021-01-07 at 14 38 02

These are some thoughts I had when using it. No deal-breakers, but I think they would improve the plugin, I'll leave it up to you whether you want to address these (if any):

- Can you have both static and dynamic performance curves? If not, maybe use a radio button to hide the one that's not being used.
- I think it would make sense to put the performance curve options in their own category (similiar to Canvas setting and Plot setting)
- I think you don't need to add "Setting" to the category. They're all settings(?) so it feels a bit redundant.
- Grafana uses sentence case rather than title case for capitalization. I recommend that you adjust configuration names and headings to match this. For example:
  - "Performance curve" instead of "Performance Curve"
  - "Remove line group" instead of "Remove Line Group"
- Would it make more sense to rename the categories to be more specific? For example, instead of "Canvas Setting" and "Plot Setting", you would have "Axes", "Performance curve", "Operation points"?
- I would probably have used the Trash icon only instead of the red Remove button.

**Comment by SSKGo** [comment]
Thank you for your review.

> * The performance curve seems to work as expected, but I can't seem to plot the data from the data source. Neither as operations points or for the dynamic performance curve. I'm using the name of the fields in the data frame. Could you give me some hints where I've messed it up? :)

I guess the dataframe structure you used is not time series. That's why it doesn't work. Otherwise, it is because field names are not set in  dataframe due to no alias input.  
I attached snapshot of the example with TestData DB data source, which anyone can use as default. Could you try this example? I hope you can get the idea.   
image

image


> These are some thoughts I had when using it. No deal-breakers, but I think they would improve the plugin, I'll leave it up to you whether you want to address these (if any):

Thank you for helpful  comments.  
I will update the plugin and the pull request.

> * Can you have both static and dynamic performance curves? If not, maybe use a radio button to hide the one that's not being used.

The panel can have both static and dynamic. You can see it in the above attached snapshot.  
So I will not add a radio button.

> * I think it would make sense to put the performance curve options in their own category (similiar to Canvas setting and Plot setting)

I will update it. Your idea is probably more user-friendly.

> * I think you don't need to add "Setting" to the category. They're all settings(?) so it feels a bit redundant.

I agree. I will update it.

> * Grafana uses sentence case rather than title case for capitalization. I recommend that you adjust configuration names and headings to match this. For example:
>   
>   * "Performance curve" instead of "Performance Curve"
>   * "Remove line group" instead of "Remove Line Group"

I will update it. I would like to follow Grafana's philosophy as much as possible.

> * Would it make more sense to rename the categories to be more specific? For example, instead of "Canvas Setting" and "Plot Setting", you would have "Axes", "Performance curve", "Operation points"?

I will update it. Thank you for the advice.

> * I would probably have used the Trash icon only instead of the red Remove button.

I will update it.

**Comment by SSKGo** [comment]
I have updated the plugin based on the given comments above and released v1.3.1.  
Please kindly review my plugin.

image

**Comment by marcusolsson** [comment]
[Published](https://grafana.com/grafana/plugins/sskgo-perfcurve-panel)! 🎉  Thank you for your submission!

**Pull request merged**
