### PR TITLE
patch version to citilogics-geoloop-panel

### PR DESCRIPTION
**Pull request by samhatchett**
the commit hash was wrong for the v1.1.1

### CODE REVIEW

**Comment by daniellee** [comment]
The published version is the incorrect commit. If you want everyone to get the latest then you need to increase the version number. Otherwise, existing users will not get the latest version - plugins are only upgraded when the version number changes. 

What do you want to do? I can update v1.1.1 (only new users will get the update) or I could publish v1.1.2 so that everyone gets the change.

**Comment by samhatchett** [comment]
👍 thanks, @daniellee - I didn't understand that nuance, but I got it now. appreciate your attention to detail.

**Comment by daniellee** [comment]
@samhatchett you'll need to update the version number in the [plugin.json](https://github.com/CitiLogics/citilogics-geoloop-panel/blob/master/dist/plugin.json#L26) to 1.1.2 as well and then update the commit here in the plugin repo to be the latest commit.

**Comment by samhatchett** [comment]
hmm. I thought i did, above. can you squash, or do you need a single clean commit from me?

**Comment by daniellee** [comment]
Let me know when you have updated the version number in the plugin.json in the geoloop repo and then I can publish 1.1.2.

**Comment by samhatchett** [comment]
Um, right. Now I really really understand how this works (sad trombone 🎺). I believe everything is good to go now.

**Comment by daniellee** [comment]
Hi Sam,

The version is still incorrect in the [plugin.json in the dist folder](https://github.com/CitiLogics/citilogics-geoloop-panel/blob/master/dist/plugin.json#L26). (Grafana loads the dist folder if it is exists and then ignores the src folder so the plugin.json in the dist folder is the important one).

**Comment by samhatchett** [comment]
thanks for sticking with me here - i think i finally got it.

**Comment by daniellee** [comment]
Sorry for the delay. When I installed this and tried to add a new Geoloop panel then I got a JavaScript error:

```
Plugin component error Error: [$injector:unpr] Unknown provider: ctxSrvProvider <- ctxSrv
```
Is `ctxSrv` correct [here](https://github.com/CitiLogics/citilogics-geoloop-panel/blob/master/src/geoloop_ctrl.js#L56)? Shouldn't it be `contextSrv`?

Seems it got changed in [this commit](https://github.com/CitiLogics/citilogics-geoloop-panel/commit/9700601f5e52c4964896eac702320b04ab9be121).

**Comment by daniellee** [comment]
@samhatchett did you find time to look at this?

**Comment by samhatchett** [comment]
sorry @daniellee - got bogged down! I'm thinking I'll just do some more major cleanup for the next release. Closing for now. Thanks for all your guidance!

**Pull request closed without merging**
