### PR TITLE
add plugin weathermap

### PR DESCRIPTION
**Pull request by hellosct1**
Inspired by the WeatherMap plugin for Cacti, WeatherMap Panel Plugin for Grafana.

### CODE REVIEW

**Comment by briangann** [comment]
can you update the plugin id to be: `atosorigin-weathermap-panel`

**Comment by hellosct1** [comment]
the update has been made
a new version is scheduled for release today

thanks

**Comment by hellosct1** [comment]
hi,

A new version is disponibled (new PR)

**Comment by hellosct1** [comment]
Hi,

I'd like to know when you're gonna do the review

thanks

**Comment by daniellee** [comment]
Hi, can you update the version numbers to the format Grafana expects. The version field should be in the form: `x.x.x` for example: `1.0.0` or `0.4.1`.

**Comment by hellosct1** [comment]
> Hi, can you update the version numbers to the format Grafana expects. The version field should be in the form: `x.x.x` for example: `1.0.0` or `0.4.1`.

I've made the correction and I pushed-in a new version which is available

best regard

**Comment by daniellee** [comment]
@hellosct1 thanks for the quick fix. I'm having problems getting the plugin to work. I tried installing the latest version: https://github.com/atosorigin/grafana-weathermap-panel/tree/5ec54e9057da93a7dc493dcb233e3d89675b9c6d but it is missing the dist files.

I also tried cloning the repo and building the plugin but I get a lot of errors - something to do with prettier and tabs. Example error:

```
Replace `↹` with `··`
```

**Comment by hellosct1** [comment]
Hi @daniellee 

the point you are talking about concerns the plug in and not the repository procedure to the plugins page of Grafana.
Can you create an issue on the project. https://github.com/atosorigin/grafana-weathermap-panel/issues

Thanks

**Comment by daniellee** [comment]
The plugin is failing the linting check:

```
Linting atosorigin-weathermap-panel version 0.3.6
https://github.com/atosorigin/grafana-weathermap 5ec54e9057da93a7dc493dcb233e3d89675b9c6d
Error
Failed to fetch README.md from GitHub: NotFoundError: Couldn't load https://api.github.com/repos/atosorigin/grafana-weathermap/contents/src/README.md?ref=5ec54e9057da93a7dc493dcb233e3d89675b9c6d: 404 {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/contents/#get-contents"}
It seems, plugin isn't built properly: plugin.json found in src/ only

Failed linting plugins update
```

This is due to the dist folder not being committed so Grafana can't load the plugin javascript and the README.md. I tried to build the plugin to be able to give you feedback but that didn't work either. I can open an issue for the build problems.

**Comment by daniellee** [comment]
Created an issue here about the build problems: https://github.com/atosorigin/grafana-weathermap-panel/issues/4

**Comment by hellosct1** [comment]
Hi @daniellee 

I just deployed a new version
and with all the information you requested

thanks

**Comment by hellosct1** [comment]
Hi @daniellee

I just deployed a new version

thanks

**Comment by daniellee** [comment]
Thanks - I could install it now and the metadata looks good. I will get back to you soon with a review.

**Comment by hellosct1** [comment]
Hi

New release

thanks

**Comment by daniellee** [comment]
# Plugin Review

Basing the review on an earlier version, 0.4.4 as the most recent commit for 0.4.6 doesn't seem to exist: https://github.com/atosorigin/grafana-weathermap-panel/commit/83c2dbaf0f0c184f941627fd35c4bd70d27e1e5e

The earlier version:  https://github.com/atosorigin/grafana-weathermap-panel/commit/2e749a79e8fae1d3f81f01fe8848d2e0a59edb69

## Plugin Metadata
- The metadata looks correct (for version 4.4)
- The README is used as the starting page both for the Grafana plugins page (for example: http://localhost:3000/plugins/atosorigin-weathermap-panel/) and on the grafana.com site. The instructions are mostly about building the plugin but they do link to the documentation.

### Documentation
The documentation is still in draft so that doesn't block publishing the plugin. It's great that you have written so much documentation, however I found some issues.
- Found some broken links:
  - https://github.com/atosorigin/grafana-weathermap-panel/blob/master/docs/resource/README.md
  - https://github.com/atosorigin/grafana-weathermap-panel/blob/master/docs/docs/EN/demo/tutorial1.md
  - https://github.com/atosorigin/grafana-weathermap-panel/blob/master/docs/docs/EN/demo/tutorial2.md
- This page is in French: https://github.com/atosorigin/grafana-weathermap-panel/blob/master/docs/EN/appendix/svg.md

## Query Editor Review

### Import Files
- To start I tried importing a local file. First I downloaded the demo file (https://github.com/atosorigin/grafana-weathermap-panel/blob/master/docs/resource/demo2-background.svg) but I got CORS errors when trying to upload it.
    ```
    Uncaught Error: A cross-origin error was thrown. React doesn't have access to the 
    actual error object in development. See https://fb.me/react-crossorigin-error for more 
    information.
    at Object.invokeGuardedCallbackDev (react-dom.development.js:396)
    at invokeGuardedCallback (react-dom.development.js:440)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:454)
    at executeDispatch (react-dom.development.js:584)
    at executeDispatchesInOrder (react-dom.development.js:609)
    at executeDispatchesAndRelease (react-dom.development.js:713)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:722)
    at forEachAccumulated (react-dom.development.js:694)
    at runEventsInBatch (react-dom.development.js:739)
    at runExtractedPluginEventsInBatch (react-dom.development.js:880)
    ```
  - There is a test button but not sure what that is for - it doesn't say anything about it in the documentation either.
- I tried importing files for regions and points. The points file worked but got a CORS error again with a region file but I didn't investigate why exactly. 

### Display
- Then I tried using the GitHub raw url for the same image (https://raw.githubusercontent.com/atosorigin/grafana-weathermap-panel/master/docs/resource/demo2-background.svg) on the Display tab and that worked better.
- There are four switches (Bold, Italic, Underline and Use SVG but they don't have labels in the UI on the latest master:
    image
- The Lower Limit switches have the same problem:
    image
- Spelling mistake: `Unit of mesure (if metric)`
- `Digital formatting (if metric)` is a little hard to understand. Maybe `Decimals` or `Decimal places` would easier to understand?
- I followed the tutorial: https://github.com/atosorigin/grafana-weathermap-panel/blob/master/docs/EN/demo/tutorial2.md and it looks like the timestamp is being used as the value. I am getting a value like `1586795640000`:
- It seems to not be possible to changes some values or I have to regularly save and refresh the page. Which brings me to the biggest question, why do I have to refresh the page when I make changes and why do I have to save changes using a Load button? Usually in Grafana you can see the change as soon as you make it.

I can test again with the latest version if you can fix the commit for version 0.4.6.

**Comment by hellosct1** [comment]
hi,

thank you for the message
I'll make the corrections.
I'll let you know when the new version is testable.

**Comment by hellosct1** [comment]
hi @daniellee 

a new version "0.4.8" is available with the corrections that you can check

this is an intermediate version

thanks

**Comment by hellosct1** [comment]
plugin compatibilite Grafana 6.6.x or 6.7.x

**Comment by hellosct1** [comment]
hi @daniellee 

can check version 0.5.0 for validation ?

thanks

**Comment by marcusolsson** [comment]
Hi @hellosct1! Since we last reviewed your plugin, we've developed a [tool to validate plugins](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/), and it turns out we missed a few things last time we looked at this. Would you mind fixing the issues reported for your plugin (enter the URL to this pull request and press Enter)?

**Comment by hellosct1** [comment]
a new version has been made with new features and demo
I validated the plugin with the tool plugin (@marcusolsson )
thank you for the validation @daniellee

**Comment by marcusolsson** [comment]
Thank you for your patience while waiting for us to review your plugin. 

We're working hard at improving the plugin experience for both users and authors. I'd like to share some important information on how to package and publish plugins going forward.

Since Grafana 7.3, we require all plugins to be _signed_. By signing your plugin, users can guarantee the integrity of the plugin and that the plugin version they've installed hasn't been modified since it was released. For more information on how to sign your plugin, refer to [Sign a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/).

With this, we now require plugins to be _packaged_ before we publish them. This means that instead of a commit containing a `dist` directory, you will need to submit a link to a ZIP archive containing your plugin. For more information on how to package your plugin, refer to [Package a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/).

Once you've packaged your plugin, you'll need to update your entry to `repo.json` to the new format. You can read more on how to do this under [Add a plugin to repo.json](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson).

To summarize, to publish your plugin, make sure that you:

1. [Sign your plugin](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/)
2. [Package your plugin](https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/)
3. Create a new GitHub release and upload the packaged plugin as a release asset
4. [Update your repo.json entry](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson)

Here's an [example](https://github.com/marcusolsson/grafana-jsonapi-datasource/releases/tag/v0.6.0) of a properly packaged plugin. In the same repository, you can find a [GitHub Action](https://github.com/marcusolsson/grafana-jsonapi-datasource/blob/master/.github/workflows/main.yml) that signs, packages, and releases the plugin whenever you create a new tag.

Once you've created a GitHub release with the packaged plugin, you can right-click the release asset, copy the link, and validate it using [the plugin validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app). 

Finally, in the November [community call](https://groups.google.com/g/grafana-developers/c/ps2vzCXRDCM/m/i7uAK1u9AQAJ), I'll be walking through the steps needed to sign and package your plugin. A recording will be made available on our [YouTube account](https://www.youtube.com/playlist?list=PLDGkOdUX1Ujo0OyE5HFffHE9GJVvaVXGs), in case you can't make it.

**Comment by marcusolsson** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
