### PR TITLE
gnocchi: release version 1.5.3

### PR DESCRIPTION
**Pull request by sileht**

### CODE REVIEW

**Comment by sileht** [comment]
Pull-request updated, HEAD is now 7e4e9138c08ce6aed0a86c62825f65974329bc99

**Comment by sileht** [comment]
Pull-request updated, HEAD is now a39063d19300423006bbd74e4cb9af1a7cc0648c

**Comment by daniellee** [comment]
The [docker compose](https://github.com/gnocchixyz/gnocchi-docker) file you created is great. Also great to see how much work is going into this plugin. Version 1.5.3 is now published.

I have a couple of follow-up questions about the query editor:
- Is it possible to create dropdowns for the Resource Name, Metric and Granularity fields rather than the user having to know the values in advance and type them in?
- Is it possible to filter out Aggregators that there are no metrics for? To avoid this error:
    image

**Comment by sileht** [comment]
Thanks for merging it !

Resource Name and Metric have already suggestion when it's possible.

I have opened issues for the two other points:
* https://github.com/gnocchixyz/grafana-gnocchi-datasource/issues/34
* https://github.com/gnocchixyz/grafana-gnocchi-datasource/issues/35

**Pull request merged**
