### PR TITLE
added consul-datasource plugin v0.1.5

### PR DESCRIPTION
**Pull request by sbueringer**
Hi,

I'm not sure what an iditomatic plugin-id would be, so I just chose `consul-datasource`. Test environment should be more or less `npm run testcoverage` and `npm run go-testcoverage` (there is also a .travis.yml file).

Please let me now if I missed something ;)

### CODE REVIEW

**Comment by sbueringer** [comment]
So `sbueringer-consul-datasource` would be a correct plugin-id right?

**Comment by sbueringer** [comment]
I changed the id to `sbueringer-consul-datasource`

**Comment by daniellee** [comment]
Thanks for submitting this. Here's my feedback so far:

- The config page could be improved with some instructions on which form the url should be in (or a link to instructions) and also how to create a token.
- The epoch that is returned in the time series data is not in the right format. It works in Singlestats and Tables but not in the Graph panel.

    The time field looks like this: `1538261136661525800` which is in microseconds. The graph panel expects millisecond precision e.g. 1538261269000

- Is it possible to get any sort of intellisense/autocomplete for the key values?

- This plugin is using an alpha feature of Grafana - backend plugins. The backend plugin works fine. The problem is with the distribution of the plugin which we have not worked on or solved yet. For example, when I installed this plugin I had to set the permissions of the `grafana-consul-plugin_linux_amd64` manually to get it to work. Not sure what to do about this - will discuss it with the team.

**Comment by sbueringer** [comment]
Thanks for the review!

* I updated the config page with some additional instructions. 
* I fixed the precision of the timestamps to milliseconds. 
* Where are you missing the autocomplete? It should be there in the query editor
* I'm not sure if it helps during the installation of the plugin, but I've changed the build so the go binary is executable after the build.

**Comment by daniellee** [comment]
Thanks for the fixes. Will get back to you next week.

**Comment by sbueringer** [comment]
@daniellee Regrading the executable bit of the backend plugin:
Is this already fixed in some newer Grafana version or is there an issue in the Grafana repositories which I can subscribe to?

**Pull request merged**
