### PR TITLE
riemann datasource plugin 0.1.3

### PR DESCRIPTION
**Pull request by faxm0dem**
Sent from the 19/11 community call ;-)

### CODE REVIEW

**Comment by marcusolsson** [comment]
Nicely done! 😄 I'll hope to review this tomorrow, otherwise early next week! Thanks for joining the call!

**Comment by faxm0dem** [comment]
Thanks for taking the time to talk to a handful of opensource develpers, it really makes a difference!
If you want to test my plugin, you probably don't need riemann, you can just set up a dummy websocket server sending some events

**Comment by marcusolsson** [comment]
I've been looking for a reason to learn more about Riemann, so I don't mind setting it up!

While I'm reading up on it, do you have a suggestion on a `riemann.config` that would facilitate testing?

**Comment by faxm0dem** [comment]
I just realised I used tabs in the json, so I force pushed using spaces

**Comment by faxm0dem** [comment]
Yeah, so the minimal config you'll need for proper testing is the following:

```
; this will let you see if riemann starts up all right
(logging/init {:file "/var/log/riemann/riemann.log"})
; this will enable internal riemann instrumentation events at 1s interval, so you don't need to generate events yourself
(instrumentation {:interval 1 :enabled? true})
; this will enable the insecure we server on localhost:5556
(ws-server {:host "127.0.0.1" :port 5556})
```

**Comment by marcusolsson** [comment]
Thanks for the config! 

I'm having some trouble connecting to the web socket it seems. I'm setting up a Docker Compose environment (so I can save it for future versions of the plugin) based on the example on their website. But I'm getting an error when connecting to it in Grafana:

Screen Shot 2020-11-20 at 10 03 17

Here's the Compose file I'm using:

```yaml
version: "3"
services:
  grafana:
    image: grafana/grafana:7.3.2
    ports:
      - 3000:3000
  riemann:
    image: riemannio/riemann:latest
    ports:
      - "5555:5555"
      - "5555:5555/udp"
      - "5556:5556"
    volumes:
      - ./riemann.config:/etc/riemann.config
```

Riemann seems to be running as it should:

```
riemann_1  | INFO [2020-11-20 09:01:45,040] main - riemann.bin - Loading /etc/riemann.config
riemann_1  | INFO [2020-11-20 09:01:45,099] main - riemann.bin - PID 1
riemann_1  | INFO [2020-11-20 09:01:45,223] clojure-agent-send-off-pool-2 - riemann.transport.websockets - Websockets server 127.0.0.1 5556 online
riemann_1  | INFO [2020-11-20 09:01:45,224] main - riemann.core - Hyperspace core online
```

Probably an configuration issue on my end though, but I thought I'd keep you in the loop.

**Comment by faxm0dem** [comment]
I'm guessing you can't export a port listening on localhost. Try using this instead:
```clojure
(ws-server {:host "0.0.0.0" :port 5556})
```

**Comment by marcusolsson** [comment]
As I suspected, it was a configuration error on my part. Changing from `ws://riemann:5556` to `ws://localhost:5556` solved it. 

However, I can't seem to get any data from it? It keeps spinning without returning anything. I suspect that my query is wrong, but could you verify?

Screen Shot 2020-11-20 at 10 56 21

I'm not sure if it helps, but I get an exception in the Riemann logs:

```
riemann_1  | clj_antlr.ParseError: no viable alternative at input '<EOF>'
riemann_1  |    at clj_antlr.common$parse_error.invokeStatic(common.clj:146)
riemann_1  |    at clj_antlr.common$parse_error.invoke(common.clj:141)
riemann_1  |    at clj_antlr.interpreted.SinglethreadedParser.parse(interpreted.clj:100)
riemann_1  |    at clj_antlr.interpreted.ThreadLocalParser.parse(interpreted.clj:122)
riemann_1  |    at clj_antlr.core.ParserWrapper.parse(core.clj:13)
riemann_1  |    at clj_antlr.core$parse_STAR_.invokeStatic(core.clj:28)
riemann_1  |    at clj_antlr.core$parse_STAR_.invoke(core.clj:19)
riemann_1  |    at clj_antlr.core$parse.invokeStatic(core.clj:35)
riemann_1  |    at clj_antlr.core$parse.invoke(core.clj:30)
riemann_1  |    at clj_antlr.core.ParserWrapper.invoke(core.clj:17)
riemann_1  |    at riemann.query$ast.invokeStatic(query.clj:118)
riemann_1  |    at riemann.query$ast.invoke(query.clj:115)
riemann_1  |    at riemann.transport.websockets$ws_index_handler.invokeStatic(websockets.clj:75)
riemann_1  |    at riemann.transport.websockets$ws_index_handler.invoke(websockets.clj:66)
riemann_1  |    at riemann.transport.websockets$ws_handler$handle__13860$fn__13861.invoke(websockets.clj:158)
riemann_1  |    at riemann.transport.websockets$ws_handler$handle__13860.invoke(websockets.clj:140)
riemann_1  |    at org.httpkit.server.HttpHandler.run(RingHandler.java:91)
riemann_1  |    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
riemann_1  |    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
riemann_1  |    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
riemann_1  |    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
riemann_1  |    at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by faxm0dem** [comment]
Upon running the query you should see the following message on the riemann log:

```
New websocket subscription to index : tagged \"riemann\"
```

**Comment by faxm0dem** [comment]
Here is a very short go code that will let you connect to the riemann websocket, just to check your riemann is working:
https://gist.github.com/faxm0dem/ff9f9cb11e1574c478f7fe9f3a1a3a7c

**Comment by faxm0dem** [comment]
Are you sure you mustn't listen on `0.0.0.0` for docker to be able to export the riemann port 5556 ?

**Comment by marcusolsson** [comment]
I get the log about a new websocket subscription to index. The Go code runs but doesn't output anything, so I assume there are no events being emitted? How can I verify that the instrumentation part of the config works?

```
(instrumentation {:interval 1 :enabled? true})
```

**Comment by faxm0dem** [comment]
> I get the log about a new websocket subscription to index. 

Yeah so I forgot to add the `(index)` to the riemann config. I updated the comment above. With it it should now work

**Comment by marcusolsson** [comment]
Other than some UX improvements, I think this is ready to be published!

I've created a [pull request](https://github.com/faxm0dem/grafana-riemann-websocket-datasource/pull/3) to fix a few of them. 

Also, I see that you've set `"grafanaDependency": "7.3.x"`. This means that your plugin can only be installed on 7.3.x installations, meaning when 7.4 is released, grafana-cli won't install it (though they can still install the plugin explicitly). I recommend that you set a range like `>=7.3.0` instead. But I'll leave that up to you!

**Comment by faxm0dem** [comment]
I rolled a new release with your patches and suggestions.
I'm not sure why the checks are failing

**Comment by marcusolsson** [comment]
[Published](https://grafana.com/grafana/plugins/ccin2p3-riemann-datasource)! 🎉

**Pull request merged**
