### PR TITLE
add cloudwatch-logs-datasource

### PR DESCRIPTION
**Pull request by digitalkaoz**
installation: ```grafana-cli install mtanda-aws-cloudwatch-logs-datasource```

### CODE REVIEW

**Comment by alexanderzobnin** [comment]
@digitalkaoz I'm trying to test this datasource, but can't configure it - there's no credentials config:

Screenshot from 2019-07-26 13-55-57

I see the changes in the master, so could you update this PR or give me some instructions?

**Comment by digitalkaoz** [comment]
@alexanderzobnin you should address this to the original author @mtanda

**Comment by daniellee** [comment]
Cloudwatch Logs support is being added to the Cloudwatch data source in Grafana so closing this PR. But if Mtanda wants to publish his then he can open a PR.

**Comment by mtanda** [comment]
Grafana officially support CloudWatch Logs!
It is good news!! Thanks for core team works.

**Pull request closed without merging**
