### PR TITLE
Add rockset datasource plugin

### PR DESCRIPTION
**Pull request by raguiar2**
Added rockset datasource to grafana. Full documentation is available at https://github.com/rockset/rockset-grafana, or the docs page at https://docs.rockset.com/grafana/

### CODE REVIEW

**Comment by raguiar2** [comment]
@alexanderzobnin PTAL

**Comment by raguiar2** [comment]
Also @daniellee or any other maintainers

**Comment by raguiar2** [comment]
@briangann done and bumped version number, ptal.

**Comment by raguiar2** [comment]
Is this ok to be merged?

**Comment by raguiar2** [comment]
@briangann  Is there anything else I need to do here, or can this be merged? Thanks!

**Comment by briangann** [comment]
you'll also need to create an account on grafana.com as "rockset" so it can be published.  this lets us associate the account with you.

**Comment by foxish** [comment]
@briangann, I just created an account with the username "rockset" on grafana.com.

**Comment by foxish** [comment]
ping @briangann, is there any further action required from my end?

cc @alexanderzobnin @daniellee

**Comment by dhruba** [comment]
@briangann Hi, we would like to get the rockset plugin published on the hosted service. Please advise on what we can do from our end to make this happen.

**Pull request merged**
