### PR TITLE
update sni-pnp-datasource to v1.0.8

### PR DESCRIPTION
**Pull request by sni**
```
1.0.8  2021-01-04
    - sign plugin
    - switch package builds to yarn
```

### CODE REVIEW

**Comment by marcusolsson** [comment]
Could you please update your PR to the [following format](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson):

```
{
  "id": "briangann-gauge-panel",
  "type": "panel",
  "url": "https://github.com/briangann/grafana-gauge-panel",
  "versions": [
    {
      "version": "0.0.8",
      "url": "https://github.com/briangann/grafana-gauge-panel",
      "download": {
        "any": {
          "url": "https://github.com/briangann/grafana-gauge-panel/releases/download/v0.0.8/briangann-gauge-panel-0.0.8.zip",
          "md5": "782c973460f330287b7efca5486aa015"
        }
      }
    }
  ]
}
```

Once you've updated your PR, make sure you paste the URL to the ZIP archive into the [plugin validator](https://plugin-validator.grafana.net/) to make sure it's ready for review.

**Comment by marcusolsson** [comment]
Closing this as it seems like there hasn't been any activity on this submission in a while.

If you'd like to submit the plugin again, I'd like to invite you to use our new submission flow inside Grafana Cloud. For more information and instructions, check out the [README](https://github.com/grafana/grafana-plugin-repository).

**Comment by sni** [comment]
yeah sorry, i'll dig into the new process when i find some time.

**Comment by marcusolsson** [comment]
No worries. If you have any questions, you can reach us on `plugin-reviews@grafana.com`.

**Pull request closed without merging**
