### PR TITLE
Add new panel: larona-epict-panel

### PR DESCRIPTION
**Pull request by LucasArona**
proposal to add my plugin

### CODE REVIEW

**Comment by daniellee** [comment]
Thanks for submitting your plugin.

Just a quick thing to fix: the version numbers in this PR and the [plugin.json](https://github.com/LucasArona/larona-epict-panel/blob/master/plugin.json#L21) do not match (1.0.0 and 0.0.1).

**Comment by LucasArona** [comment]
Oh, yes, sorry :) I just fixed it.

**Comment by LucasArona** [comment]
Thank you for your feedback.
I fixed the link to the licence, added more info in the readme and replaced `ctrl.render()` by `ctrl.refresh()` as you pointed out.

**Comment by daniellee** [comment]
Looks good! Merged and published: https://grafana.com/plugins/larona-epict-panel

**Pull request merged**
