### PR TITLE
Release v0.2.6 simpod-json-datasource

### PR DESCRIPTION
**Pull request by simPod**

### CODE REVIEW

**Comment by simPod** [comment]
hi, your linting does not support redirects https://app.circleci.com/pipelines/github/grafana/grafana-plugin-repository/1331/workflows/cff787b9-1868-49ac-8d3e-e01545d89c51/jobs/3924

**Comment by simPod** [comment]
ok it's broken 🤷🏾‍♀️

**Comment by marcusolsson** [comment]
Looks like the URL has an extra `h` in `https` which might break the CI.

Also, it looks like this plugin is unsigned. Are you having trouble generating a signature?

**Comment by simPod** [comment]
Oh I see now, thanks!

**Comment by simPod** [comment]
@marcusolsson can you release? Thanks

**Comment by simPod** [comment]
cc @briangann

**Comment by marcusolsson** [comment]
Thanks, I'm able to successfully validate the plugin now. Unfortunately, I won't be able to publish the plugin until it has a valid signature. You can read more on how to sign your plugin here: 

https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/

Let me know if you have any questions on how to sign the plugin!

**Comment by simPod** [comment]
Ok, I signed again and validation passes.

**Comment by marcusolsson** [comment]
Thank you! 🙏  Moving to review queue.

**Comment by marcusolsson** [comment]
Published! 🎉

**Pull request merged**
