### PR TITLE
Add pue-solr-datasource to grafana plugin repository

### PR DESCRIPTION
**Pull request by ishtartec**
This plugin provides an advanced datasource for querying Solr server >= 4. This datasource also provides support for the Solr version bundled with Cloudera CDH 5.X.

### CODE REVIEW

**Comment by crapufish** [comment]
+1

**Comment by daniellee** [comment]
@ishtartec Could you provide some steps for setting up a simple solr server (with docker preferably)?

I tried using the solr docker hub image: https://hub.docker.com/_/solr/ but it did not work so well with the datasource.

## Feedback so far

### Metadata

- The plugin.json looks good.
- The README is mostly fine but could do with some more help on the setup phase - which url to connect to, any settings that need to be enabled for the solr server etc.

## Config Page

- There is no suggest url for the http URL ( See guidelines [here](http://docs.grafana.org/plugins/developing/plugin-review-guidelines/#config-page-guidelines))

- On the config page, it says that the connection works if I use the url `http://localhost:8983/solr/` ( which I think is wrong):

    image

    but looking at the response in the network tab:

    image

    Using `http://localhost:8983` or a similar url then I get a CORS error - maybe that's a docker problem though:

    image

## Query Editor

- The query for collections in the query editor did not work for me due to this error:

    ```json
    {
      "responseHeader":{
        "status":400,
        "QTime":0},
      "error":{
        "metadata":[
          "error-class","org.apache.solr.common.SolrException",
          "root-error-class","org.apache.solr.common.SolrException"],
        "msg":"Solr instance is not running in SolrCloud mode.",
        "code":400}}
    ```

    Is this a setting that needs to be enabled and that should be added to the readme?

- The query editor needs a little bit of styling. The fields are not lined up in columns:
    image

    Here is an example using the Grafana css classes for query editors:

    image

    It uses the `width-x` css classes to set a fixed width for the labels and fields to get them to line up.

It looks like a good start - I think most of my problems are due to not getting the solr server set up correctly.

**Comment by daniellee** [comment]
@ishtartec did you see my review above?

**Comment by ishtartec** [comment]
Yes @daniellee!. We have updated the plugin with all your comments. We are currently working on the documentation for the steps needed to test the plugin with a simple Solr instance in docker.

**Comment by alexanderzobnin** [comment]
@ishtartec any updates?

**Comment by ishtartec** [comment]
Yes @alexanderzobnin, the plugin has been updated with @daniellee comments and can be tested with both Solr Cloud and Solr single instance. It also works with Solr 4.x and 7.x which is the latest version. Should I fill another PR?

**Comment by alexanderzobnin** [comment]
@ishtartec it's not necessary to push new PR, please update this one.

**Comment by OskarsPakers** [comment]
@ishtartec will you proceed with this? Do you need assistance?

**Comment by ishtartec** [comment]
@OskarsPakers, I have updated the PR to continue with this.

**Comment by daniellee** [comment]
Published version 1.0.2: https://grafana.com/grafana/plugins/pue-solr-datasource

**Comment by daniellee** [comment]
This branch was a bit messed up so merged manually: https://github.com/grafana/grafana-plugin-repository/commit/7701ffc1209927ed116aa048aa1a7c8aa4a6b1c6

**Pull request closed without merging**
