### PR TITLE
Clickhouse Datasource plugin version update to 2.1.0

### PR DESCRIPTION
**Pull request by Slach**
# 2.1.0 (2020-08-13)

## Enhancement:
* add "Skip comments" checkbox to query editor to pass SQL comments to server, fix https://github.com/Vertamedia/clickhouse-grafana/issues/265
* add setup notes for Grafana 7.x to README
* improve alerts query processing for use case when `query(query_name, from, to)` time range is less than visible dashboard time range, see https://github.com/Vertamedia/clickhouse-grafana/issues/237
* improve alerts json parsing in golang part for case when we have string fields in response which interprets as series name, see https://github.com/Vertamedia/clickhouse-grafana/issues/230
* properly parsing POST queries in golang part of plugin, https://github.com/Vertamedia/clickhouse-grafana/pull/228, thanks @it1804

## Fixes:
* fix corner cases for $macro + subquery, see https://github.com/Vertamedia/clickhouse-grafana/issues/276 and https://github.com/Vertamedia/clickhouse-grafana/issues/277  
* fix parallel query execution, see https://github.com/Vertamedia/clickhouse-grafana/pull/273
* fix identifiers quotes, see https://github.com/Vertamedia/clickhouse-grafana/issues/276, https://github.com/Vertamedia/clickhouse-grafana/issues/277
* fix plugin.json for pass `grafana-plugin-repository` plugin validator
* fix multi-value variables behavior - https://github.com/Vertamedia/clickhouse-grafana/issues/252
* add Vagrantfile for statefull environment and allow to upgrade scenario like  grafana 7.1.0 + grafana-cli upgrade-all
  * fix https://github.com/Vertamedia/clickhouse-grafana/issues/244
  * fix https://github.com/Vertamedia/clickhouse-grafana/issues/243
* add multiple dashboard examples for github issues:
  * fix https://github.com/Vertamedia/clickhouse-grafana/issues/240 
  * fix https://github.com/Vertamedia/clickhouse-grafana/issues/135 
  * fix https://github.com/Vertamedia/clickhouse-grafana/issues/245 
  * fix https://github.com/Vertamedia/clickhouse-grafana/issues/238   
  * fix https://github.com/Vertamedia/clickhouse-grafana/issues/232
  * fix https://github.com/Vertamedia/clickhouse-grafana/issues/127
  * fix https://github.com/Vertamedia/clickhouse-grafana/issues/141

### CODE REVIEW

**Comment by Slach** [comment]
Hi @daniellee could you look this PR?

**Comment by marcusolsson** [comment]
Thanks for considering contributing your plugin! 

Before we can start reviewing your plugin, would you mind fixing the issues found by the [plugin checker](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/?url=Vertamedia/clickhouse-grafana@f340426c950b954dfe34a1f20f5fc0f24f7cf927)?

**Comment by Slach** [comment]
@marcusolsson please look to https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/?url=Vertamedia/clickhouse-grafana@552d9d798203bb6cbc068c8f3ffd973558e7ea60

what mean "Invalid plugin.json
dependencies: grafanaDependency is required"?

I'm looking to https://grafana.com/docs/grafana/latest/developers/plugins/metadata/#dependencies and don't see any tag with this name
also, I try to found it on `grep -r grafanaDepencency /usr/share/grafana/public/app/plugins/` on grafana:latest docker image and found nothing

according to
https://github.com/Vertamedia/clickhouse-grafana/commit/552d9d798203bb6cbc068c8f3ffd973558e7ea60
could you explain what exactly I should change to pass plugin validator?
could you explain

**Comment by Slach** [comment]
@marcusolsson please check https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/?url=Vertamedia/clickhouse-grafana@3bc06edb0e86e08378ab9bfed70f6a65e8ba1a02, and approve this PR

**Comment by Slach** [comment]
@marcusolsson could you look to this PR again?

**Comment by marcusolsson** [comment]
There's multiple versions in this PR. Could you change so the PR only contains a single version to publish. I assume 2.0.7? I'll publish this as soon as you've updated the PR!

**Comment by Slach** [comment]
@marcusolsson I squash multiple releases to one, please merge release

**Comment by marcusolsson** [comment]
[Published](https://grafana.com/grafana/plugins/vertamedia-clickhouse-datasource?version=2.1.0)!

Thanks!

**Pull request merged**
