### PR TITLE
add xcomponent-ac2-panel plugin in repo.json file

### PR DESCRIPTION
**Pull request by mbarekh**

### CODE REVIEW

**Comment by daniellee** [comment]
Looks like the plugin id is misspelled in the [plugin json](https://github.com/xcomponent/grafana-plugin-ac2/blob/master/dist/plugin.json#L4):

`xcomponet-ac2-panel`

I'm guessing it should be `xcomponent-ac2-panel` ?

**Comment by mbarekh** [comment]
@daniellee you are right. I misspelled the plugin name. The fix has been done.

**Comment by alexanderzobnin** [comment]
@mbarekh did you push your fix? I still get
```
Warning
Plugin id in repo.json (xcomponent-ac2-panel) doesn't match plugin.json (xcomponet-ac2-panel)
```

**Comment by marcusolsson** [comment]
Closing due to inactivity.

**Pull request closed without merging**
