### PR TITLE
alexanderzobnin-zabbix-app - fixed link to latest version.

### PR DESCRIPTION
**Pull request by alexanderzobnin**

### CODE REVIEW

**Comment by daniellee** [comment]
Hi @alexanderzobnin did you forget to push ac9b4d249d7a2e9c3799c6c095d2d7d9da9f54d6 to master on GitHub or am I missing something?

**Comment by alexanderzobnin** [comment]
I have pushed it. See latest commit.

**Comment by alexanderzobnin** [comment]
Wow, sorry. It's commit to main repo, not for grafana.net. I'll fixed it.

**Comment by daniellee** [comment]
Great! Merged and published.

**Pull request merged**
