### PR TITLE
Added mx's separator panel

### PR DESCRIPTION
**Pull request by mxswat**
[Mx's Separator](https://github.com/mxswat/grafana-separator-panel) Is a simple panel that I use as a vertical and horizontal separator.

It becomes transparent after you add it and It becomes visible on hover after 300ms with a 150ms transition.

Example GIF

### CODE REVIEW

**Comment by daniellee** [comment]
Just discovered that we have a 3 character minimum for the org part of the plugin id (which I will add to the documentation and lint script). Could you change the plugin id to be `mxswat-separator-panel` instead? Thanks!

**Comment by mxswat** [comment]
No problem I'll come home tomorrow and do the change

Il 31 dic 2018 12:10 AM, "Daniel Lee" <notifications@github.com> ha scritto:

**Comment by mxswat** [comment]
As requested I made the changes, also, Happy new year Grafana team.

**Comment by mxswat** [comment]
@daniellee  Should I be fixing this merge conflict?

**Comment by alexanderzobnin** [comment]
@mxswat Please, update plugin id in repo.json (`mx-separator-panel`), because it doesn't match plugin.json (`mxswat-separator-panel`).

**Comment by daniellee** [comment]
Merged manually and published. Sorry for the delay.

https://grafana.com/plugins/mxswat-separator-panel

**Pull request merged**
