### PR TITLE
Adding Scrutinizer Datasource

### PR DESCRIPTION
**Pull request by briandav22**
Plixer manufacturers a metadata collection and analysis solution called Scrutinizer. I would like to add a Scrutinizer Datasource to your supported plugins. 
**REMOVE THE TEXT ABOVE BEFORE CREATING THE PULL REQUEST**

### CODE REVIEW

**Comment by alexanderzobnin** [comment]
@briandav22 Hi! Thanks for your contribution! Could you provide some instructions, how to set up and configure Scrutinizer?

**Comment by briandav22** [comment]
> @briandav22 Hi! Thanks for your contribution! Could you provide some instructions, how to set up and configure Scrutinizer?
@alexanderzobnin 
Hi Alexander, 

Are you looking for a deployment guide for the Scrutinizer Flow Collector (the product Plixer makes), or a guide for setting up the Scrutinizer-Datasource I wrote? 

For the data source, I created a read the docs which can be found here: https://grafana-docs.readthedocs.io/en/latest/ds_gettingstarted.html

For deploying our netflow collector, we typically include a deployment guide when the product is downloaded from www.plixer.com. We also have a configuration manual at https://docs.plixer.com.

I'm happy to provide further instructions as needed, just looking to make sure I understand what your asking and what format you would like it in. 

Thanks for the help.

**Comment by alexanderzobnin** [comment]
@briandav22 Does the plugin work with free version of Scrutinizer? If not, it seems you need a commercial subscription.

**Comment by briandav22** [comment]
> @briandav22 Does the plugin work with free version of Scrutinizer? If not, it seems you need a commercial subscription.

Hey Alex, This would work with the free version of Scrutinizer, licensing Scrutinizer would just give you the ability to trend the data out for longer periods of time. In the free mode, you only have 5 hours worth of data.

**Comment by alexanderzobnin** [comment]
@briandav22 Looks like Free edition of Scrutinizer doesn't meet the [open source plugin requirements](https://grafana.com/terms), so you need plugin subscription for publishing it.

**Comment by briandav22** [comment]
> @briandav22 Looks like Free edition of Scrutinizer doesn't meet the [open source plugin requirements](https://grafana.com/terms), so you need plugin subscription for publishing it.

Hey Alex, 

Understood, thanks for taking the time to work through this with me. I'll see if I can get funding from my organization for this. 

Could you have someone from sales email me at briand@plixer.com with some cost estimates for the licensing? 

Thanks,

Brian

**Comment by daniellee** [comment]
@briandav22  as this is a plugin for a commercial service, you need to purchase a plugin subscription to be published. See terms here: https://grafana.com/terms/

Closing this PR as it has been open for a long time and you haven't purchased a subscription but let me know if I should you put you in contact with anyone from our commercial team.

**Pull request closed without merging**
