### PR TITLE
Add hawkular datasource

### PR DESCRIPTION
**Pull request by jotak**

### CODE REVIEW

**Comment by daniellee** [comment]
Hi @jotak,

Two small problems:

- The [plugin.json](https://github.com/hawkular/hawkular-grafana-datasource/blob/0d3a8ac2724b303e5178b9252284a17cc77dfda2/dist/plugin.json) file in the dist directory is out of sync for that commit. It should be version 1.0.4.

- The README.md file is also missing from the dist directory.

Otherwise it works fine having a release branch.

**Comment by jotak** [comment]
Hi @daniellee , I've changed the commit (and bumped to 1.0.5) - our gruntfile did not correctly manage plugin.json, it should be ok now.

**Comment by daniellee** [comment]
@jotak one last problem! All the image links in the readme are broken on Grafana.net. Relative links won't work, you need to use the raw GitHub links.

Now you have relative links like this:

`docs/images/query-for-metrics.png`

They need to look like this:

`https://github.com/hawkular/hawkular-grafana-datasource/raw/master/docs/images/query-for-metrics.png`

or like this:

`https://raw.githubusercontent.com/hawkular/hawkular-grafana-datasource/master/docs/images/query-for-metrics.png`

**Comment by jotak** [comment]
@daniellee fixed: https://github.com/hawkular/hawkular-grafana-datasource/commit/714bcbb42dfad8adfed2931dc38fc1c504f49dfd

I hope it's the good one :-)

**Comment by daniellee** [comment]
Published: https://grafana.net/plugins/hawkular-datasource

Thanks for your patience!

**Comment by jotak** [comment]
Thank you!

**Pull request merged**
