### PR TITLE
Adding Sensu Go data source

### PR DESCRIPTION
**Pull request by mariusoe**
Hi Grafana-Team,

this PR is adding a data source for [Sensu Go](https://sensu.io/).

You can easily create an environment for testing the data source by the following steps using Sensu Go's Docker components (it's basically a copy of the test setup described on its website):

1. Install Sensu Go (backend and an agent in order to get some data)
```
$ sudo docker network create sensu
$ sudo docker volume create sensu-backend-data
$ sudo docker run -d --rm --name sensu-backend \
  --network sensu -p 8080:8080 -p 3000:3000 \
  -v sensu-backend-data:/var/lib/sensu \
  sensu/sensu:6.0.0 sensu-backend start
11bbb27c3
$ sudo docker run -d --rm --network sensu -p :3030 \
  sensu/sensu:6.0.0 sensu-agent start \
  --backend-url ws://sensu-backend:8081 --deregister \
  --keepalive-interval=5 --keepalive-warning-timeout=10 --subscriptions linux
$ curl -s http://localhost:8080/version
{"etcd":{"etcdserver":"3.3.13","etcdcluster":"3.3.0"},"sensu_backend":"6.0.0"}
$ _
```

2. Install the Sensu Go CLI (required for adding some sample check which we'll see in Grafana)
```
$ curl -LO https://s3-us-west-2.amazonaws.com/sensu.io/sensu-go/6.0.0/sensu-go_6.0.0_linux_amd64.tar.gz
$ sudo tar -xzf sensu-go_6.0.0_linux_amd64.tar.gz -C /usr/local/bin/
$ sensuctl configure -n --url http://127.0.0.1:8080 \
  --username admin \
  --password "P@ssw0rd!" \
  --namespace default
$ sensuctl cluster health
ID                NAME     ERROR   HEALTHY
8927110dc66458af  default          true
$ sensuctl cluster id
sensu cluster id: "227b26eb-26c4-46b2-bc7c-8c080b072e6b"
$ _
```

3. Configure a monitor
```
$ sensuctl asset add sensu/monitoring-plugins:2.2.0-1
fetching bonsai asset: sensu/monitoring-plugins:2.2.0-1
added asset: sensu/monitoring-plugins:2.2.0-1
$ sensuctl check create ntp \
  --runtime-assets "sensu/monitoring-plugins" \
  --command "check_ntp_time -H time.nist.gov --warn 0.5 --critical 1.0" \
  --output-metric-format nagios_perfdata \
  --publish="true" --interval 30 --timeout 10 --subscriptions linux
$ sensuctl event list
ENTITY        CHECK      OUTPUT                                                                    STATUS  SILENCED   TIMESTAMP
a749e3a10d86  keepalive  Keepalive last sent from a749e3a10d86 at 2019-09-11 15:34:25 +0000 UTC    0       false      2019-09-11 08:34:25 -0700 PDT
a749e3a10d86  ntp        NTP OK: Offset -0.03375908732 secs|offset=-0.033759s;0.500000;1.000000;   0       false      2019-09-11 08:34:22 -0700 PDT
$ _
```

### CODE REVIEW

**Comment by mariusoe** [comment]
fyi @mariomann @AlexanderWert

**Comment by rgarcia89** [comment]
any update on this?

**Comment by marcusolsson** [comment]
Thank you for your patience while waiting for us to review your plugin. 

We're working hard at improving the plugin experience for both users and authors. I'd like to share some important information on how to package and publish plugins going forward.

Since Grafana 7.3, we require all plugins to be _signed_. By signing your plugin, users can guarantee the integrity of the plugin and that the plugin version they've installed hasn't been modified since it was released. For more information on how to sign your plugin, refer to [Sign a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/).

With this, we now require plugins to be _packaged_ before we publish them. This means that instead of a commit containing a `dist` directory, you will need to submit a link to a ZIP archive containing your plugin. For more information on how to package your plugin, refer to [Package a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/).

Once you've packaged your plugin, you'll need to update your entry to `repo.json` to the new format. You can read more on how to do this under [Add a plugin to repo.json](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson).

To summarize, to publish your plugin, make sure that you:

1. [Sign your plugin](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/)
2. [Package your plugin](https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/)
3. Create a new GitHub release and upload the packaged plugin as a release asset
4. [Update your repo.json entry](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson)

Here's an [example](https://github.com/marcusolsson/grafana-jsonapi-datasource/releases/tag/v0.6.0) of a properly packaged plugin. In the same repository, you can find a [GitHub Action](https://github.com/marcusolsson/grafana-jsonapi-datasource/blob/master/.github/workflows/main.yml) that signs, packages, and releases the plugin whenever you create a new tag.

Once you've created a GitHub release with the packaged plugin, you can right-click the release asset, copy the link, and validate it using [the plugin validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app). 

Finally, in the November [community call](https://groups.google.com/g/grafana-developers/c/ps2vzCXRDCM/m/i7uAK1u9AQAJ), I'll be walking through the steps needed to sign and package your plugin. A recording will be made available on our [YouTube account](https://www.youtube.com/playlist?list=PLDGkOdUX1Ujo0OyE5HFffHE9GJVvaVXGs), in case you can't make it.

**Comment by anatolijd** [comment]
hi, 
can you look at this merge request once again, please ?

**Comment by marcusolsson** [comment]
Hi @anatolijd,

Could you please update the PR to the [following format](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson)?:

```
{
  "id": "briangann-gauge-panel",
  "type": "panel",
  "url": "https://github.com/briangann/grafana-gauge-panel",
  "versions": [
    {
      "version": "0.0.8",
      "url": "https://github.com/briangann/grafana-gauge-panel",
      "download": {
        "any": {
          "url": "https://github.com/briangann/grafana-gauge-panel/releases/download/v0.0.8/briangann-gauge-panel-0.0.8.zip",
          "md5": "782c973460f330287b7efca5486aa015"
        }
      }
    }
  ]
}
```

**Comment by tan-tony** [comment]
hi,
@mariusoe any update on this pr?

**Comment by johntdyer** [comment]
@anatolijd  looks like this can move forward if you update the registry file to their new format....

**Comment by marcusolsson** [comment]
Closing this as it seems like there hasn't been any activity on this submission in a while.

If you'd like to submit the plugin again, I'd like to invite you to use our new submission flow inside Grafana Cloud. For more information and instructions, check out the [README](https://github.com/grafana/grafana-plugin-repository).

**Pull request closed without merging**
