### PR TITLE
Contrail Analytics datasource plugin

### PR DESCRIPTION
**Pull request by eeishaan**

### CODE REVIEW

**Comment by daniellee** [comment]
Hi @eeishaan if I want to run Contrail in docker to be able to test this plugin, where would I find instructions to do that? Are these the latest instructions: https://github.com/Juniper/contrail-docker/wiki/How-to-run-contrail-docker-containers

**Comment by eeishaan** [comment]
Hey @daniellee. Yes, these seem to be the latest instructions. Some of the commands may not work as they mention internal IP addresses. I would recommend that you follow the [official documentation](https://www.juniper.net/documentation/en_US/contrail4.1/topics/concept/install-containers-single-multi-node.html) on Juniper's site as well.

**Comment by daniellee** [comment]
It looks like a lot of steps to get some test data - is there a test server I could connect to instead to test the plugin? Otherwise, I will try and set it up with the official instructions.

**Comment by eeishaan** [comment]
@daniellee  There is no test server, but you can request a sandbox environment with contrail installed [here](https://www.juniper.net/us/en/cloud-software/trial/). This would be valid for 12 hours. You will have install grafana from the tar file as the provided user won't have superuser privilege.

**Comment by alexanderzobnin** [comment]
@eeishaan Sorry for delay, but could you rebase your PR?

**Comment by eeishaan** [comment]
@alexanderzobnin Done

**Comment by marcusolsson** [comment]
Closing due to old age and lack of activity.

**Pull request closed without merging**
