### PR TITLE
Update Flowcharting panel 0.3.0

### PR DESCRIPTION
**Pull request by algenty**
# New banner pannel
Banner

# Changelog

### Added
  /!\ Possible breaking change with 0.2.0 and 0.2.5 but it will compatible with next release.  
  - Full documentation at https://algenty.github.io/flowcharting-repository/
  - Migration process for next release.
  - Dynamic documentation/Examples on popover (thx SCHKN)
  - Params link option, add params of dashboard to link.
  - Full review of code (ES6 Class mode)
  - Unit test with jest to increase quality
  - Fill/text/stoke rules on the same object is possible.
  - Mapping selector helper (chain in mapping)
  - Icon overlay state (display icon warning when NOK)
  - Implemented the conditions to display text according to the states.
  - new inspect Tab with :
    - Renamer ID (double click on ID)
    - State status
    - Debug mode
  - Custom Link Mapping overrite.  
  
### Fixed
  - Substring replace on text (Issue #8)
  - Editor object not found Exception (Issue #1)
  - Original Link (Issue #9)
  - Fixed Change the colors (Issue #14)
  - Fixed Unit (Issue #12)

### CODE REVIEW

**Comment by algenty** [comment]
Hi briangann,
How do you do ?
any news for this pulls ?

BR
Arnaud

**Comment by algenty** [comment]
Any news ?, I have issues fixed in this release.

**Comment by briangann** [comment]
i'm checking it out now, will publish within the next 2 hours.

**Comment by briangann** [comment]
published!

**Comment by algenty** [comment]
Thx !

**Pull request merged**
