### PR TITLE
Add frser-sqlite-datasource

### PR DESCRIPTION
**Pull request by fr-ser**
This is the first version of the SQLite plugin.
There is a working (docker based) test environment in the source repo.

As this is my first plugin I am happy to answer questions and adjust the plugin itself

### CODE REVIEW

**Comment by fr-ser** [comment]
I rebase my fork to get rid of conflicts and to update the plugin version to 0.1.2

**Comment by fr-ser** [comment]
I rebased and updated to the current version of 0.1.3. If the rebases or version updates are a problem/delay for the review process let me know and I will adjust my workflow

**Comment by marcusolsson** [comment]
Thank you for your patience while waiting for us to review your plugin. 

We're working hard at improving the plugin experience for both users and authors. I'd like to share some important information on how to package and publish plugins going forward.

Since Grafana 7.3, we require all plugins to be _signed_. By signing your plugin, users can guarantee the integrity of the plugin and that the plugin version they've installed hasn't been modified since it was released. For more information on how to sign your plugin, refer to [Sign a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/).

With this, we now require plugins to be _packaged_ before we publish them. This means that instead of a commit containing a `dist` directory, you will need to submit a link to a ZIP archive containing your plugin. For more information on how to package your plugin, refer to [Package a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/).

Once you've packaged your plugin, you'll need to update your entry to `repo.json` to the new format. You can read more on how to do this under [Add a plugin to repo.json](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson).

To summarize, to publish your plugin, make sure that you:

1. [Sign your plugin](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/)
2. [Package your plugin](https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/)
3. Create a new GitHub release and upload the packaged plugin as a release asset
4. [Update your repo.json entry](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson)

Here's an [example](https://github.com/marcusolsson/grafana-jsonapi-datasource/releases/tag/v0.6.0) of a properly packaged plugin. In the same repository, you can find a [GitHub Action](https://github.com/marcusolsson/grafana-jsonapi-datasource/blob/master/.github/workflows/main.yml) that signs, packages, and releases the plugin whenever you create a new tag.

Once you've created a GitHub release with the packaged plugin, you can right-click the release asset, copy the link, and validate it using [the plugin validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app). 

Finally, in the November [community call](https://groups.google.com/g/grafana-developers/c/ps2vzCXRDCM/m/i7uAK1u9AQAJ), I'll be walking through the steps needed to sign and package your plugin. A recording will be made available on our [YouTube account](https://www.youtube.com/playlist?list=PLDGkOdUX1Ujo0OyE5HFffHE9GJVvaVXGs), in case you can't make it.

**Comment by fr-ser** [comment]
Rebased and added the assets. If there is anything else missing, let me know :ok_hand:

**Comment by marcusolsson** [comment]
Awesome! I'm running your plugin through the [plugin validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/?url=https://github.com/fr-ser/grafana-sqlite-datasource/archive/v0.2.1.zip), and it seems like the archives contains the entire repository rather than only the dist directory.

If you want to validate the packaged plugin locally, you can use the [command-line tool](https://github.com/grafana/plugin-validator).

**Comment by fr-ser** [comment]
Updated to the newest instruction with v7.3. I hope there are not more changes to the release process during my release process :laughing:

**Comment by marcusolsson** [comment]
Thank you for your patience! 🙏 Looks like we're ready to start reviewing the plugin!

Just to make sure, do you wish to publish all the listed versions (it will take longer to review)? Since it's a new plugin, and users will get the latest version when they install, I'll focus on frser-sqlite-datasource-0.2.2 first.

**Comment by fr-ser** [comment]
v0.1.x is potentially more compatible with Grafana v7.0.0 (the other one uses toolkits for v7.3.3).
If it does not take much longer (are we talking days, weeks or months?), I would prefer publishing both.

**Comment by marcusolsson** [comment]
Gotcha! Then I'll review both 0.1.5 and 0.2.2. Could you remove 0.2.1 from the PR? We're currently working out a few kinks with the publishing process, but I'll let you know once I've started review this.

**Comment by fr-ser** [comment]
v0.2.1 is removed. It should have been removed anyway, as it does not follow the new packaging guidelines. Sorry about that!

And thank you very much for your quick responses and helpful comments!

**Comment by marcusolsson** [comment]
Happy new year! 🎉  I'm back from the holidays and will be reviewing your plugin during the day!

**Comment by marcusolsson** [comment]
Published! 🎉 

Some suggestions for the next version. 

- Update the name from `sqlite-datasource` to the more user friendly `SQLite`
- I believe if you add `"category": "sql"` to your plugin.json, it will be grouped with the rest of other SQL databases
- Consider using the QueryField for the SQL input. It can even give you syntax highlighting for SQL. Here's an example: https://github.com/marcusolsson/grafana-json-datasource/blob/9aad631ec7e2b15b4f3a504e34e06b96c8f8fa7c/src/components/JsonPathQueryField.tsx#L27-L34

**Comment by fr-ser** [comment]
Thank you very much for your input. I will consider all suggestions and come with an update soon!

Just one question regarding the `QueryField`. It looks like a nice addition (syntax highlighting), but I could not get it working (and lost resizability on the way) with the below snipped. Where can I find more documentation or where is the best place to ask? The Grafana community board? Grafana github?

```jsx
        <QueryField
          additionalPlugins={[
            BracesPlugin(),
            SlatePrism({
              onlyIn: (node: any) => node.type === 'code_block',
              getSyntax: (node: any) => 'SQL',
            }),
          ]}
          portalOrigin="sqlite"
          query={rawQueryText}
          onRunQuery={() => props.onRunQuery()}
          onChange={onQueryFieldChange}
        />
```

**Pull request merged**
