### PR TITLE
Added diagram panel plugin

### PR DESCRIPTION
**Pull request by jdbranham**

### CODE REVIEW

**Comment by daniellee** [comment]
Hi,

Thanks for submitting this, it looks like it will be fantastic! 

I'm having a couple of issues, not sure if it's something I'm doing wrong.

It renders fine the 1st time when I add it as a new panel but after that I get this mermaid error if I haven't saved the dashboard:

mermaiderror

If I make a change, then I have to save and refresh the page otherwise I get the same error again.

I have a graphite query that looks like this:

image

and mermaid definition like this:

image

The end result looks great:

image

But the workflow of Edit -> Back to dashboard -> Save -> Refresh page is not ideal. Do you think you can fix it so that it works when I press the refresh data button (top right corner) or when I leave the Definition field:

image

**Comment by Dieterbe** [comment]
Whoa this looks neat for describing infra and showing its state.maybe can be integrated with alerting as well.

**Comment by RichiH** [comment]
This goes strongly into the direction of weathermaps.
Also see https://github.com/grafana/grafana/issues/188

**Comment by jdbranham** [comment]
Ah yes, I see the bug.

I need to clean up the SVG on the refresh.

I'll patch it up.


Thanks for checking it out!




________________________________

**Comment by jdbranham** [comment]
I've fixed the refresh bug and styled the diagram a bit

**Comment by RichiH** [comment]
@jdbranham are you planning to keep expanding this, i.e. will you take feature requests?

**Comment by daniellee** [comment]
That was fast! Works great with the refresh now. Merged and published: https://grafana.net/plugins/jdbranham-diagram-panel

I think you are going to get a million feature requests pretty soon :-) A network weathermap might be possible with this plugin: https://network-weathermap.com/manual/0.98/images/weathermap-example.png

Here are a couple of feature requests from me:

- Make it clearer in the documentation that the id of the diagram node matches the alias of the time serie by giving a few examples of a query and the matching mermaid syntax. Based on my experience, you are going to get a lot of questions about how do I do this with InfluxDB, Elasticsearch, OpenTSDB etc.

- Make it clearer in the documentation what you can match by id. It seems like only nodes can be matched and not links? Does it work with Sequence diagrams and Gantt charts?

- More examples of diagrams. A real world example dashboard -> something like Haproxy load balancers that you could upload to: https://grafana.net/dashboards . Also, more examples showing off the Mermaid lib -> subgraphs etc.

- Show the values in the diagram nodes. Maybe with mermaid syntax but that means you would have to parse the mermaid text e.g. `A => SE{Sweden [value] connections}`


And I will send a PR for these two changes:
- Add a link to the GitHub repo in the plugin.json
- Refresh when you leave the Diagram Definition field instead of having to click on refresh.

**Comment by jdbranham** [comment]
Thanks Daniel -

I've merged the PR and will add your feature requests.

It's great to finally be able to contribute back to the Grafana community. It's made my job much easier, and saved my employer many dollars.


I'll try to knockout as many feature requests as possible. My day job keeps me pretty busy too =]


________________________________

**Comment by RichiH** [comment]
@jdbranham Very good to hear that :)

Do you need any more input on what makes a weathermap a weathermap? I suspect not, but wanted to make sure either way.

The most important part: Thank you! :)

**Comment by jdbranham** [comment]
@RichiH Any input is welcome!
I have some ideas about the weathermap functionality, like making the links between the diagram nodes styled by metric queries.
As long as I can prove the value of this plugin to my employer, I should be able to commit lots of time!

**Comment by RichiH** [comment]
@jdbranham Random dump of properties of a weathermap

* Dual-direction links with to/from
* Width of links configurable; either fixed value or as result of a query
* Global colour scheme of relative congestion per link
* Nodes ideally with the ability to also colour-code parts of the node for CPU, memory, etc
* Mouse-over on link/node pops up more info with historic graph, name, etc
* Fixed placement of nodes
* Optionally the ability to create curved links instead of direct links
* Clicking on the links/nodes should allow to jump to drill-down links

As to the usefulness: What kind of business are you running? I am sure there's a few arguments to be found... :)

**Comment by jdbranham** [comment]
Thanks @RichiH 
I'm in telecommunications, mainly dealing with knowledge delivery and EAI. 
One area I'm hoping to use this is API request/response health over each traversed node.

I've just committed a change that adds series overrides for threshold values and value calculation.
https://github.com/jdbranham/grafana-diagram/commit/ca0b4ed7489e7066fe6ea188a669ba137e8d4320

I've got to run for a bit, but I'll create a PR for update on Grafana.net later today.

**Comment by jdbranham** [comment]
Had a few minutes to spare.
https://github.com/grafana/grafana-plugin-repository/pull/44

**Comment by RichiH** [comment]
@jdbranham Yah, what I need for networking, you need for your API endpoints. If you have a load-balanced endpoint somewhere, and you probably do, you can pretty much use everything I wrote above. And it will be generic enough to use for both, and more, use cases :)

I couldn't build master yet, so I have to ask: Does this fully support Prometheus data sources?

**Comment by jdbranham** [comment]
@RichiH 
I cant say for sure.
I'm downloading Prometheus now to test. Feel free to open an issue for tracking -
https://github.com/jdbranham/grafana-diagram/issues/

**Pull request merged**
