### PR TITLE
Added jancho-heatmap-plugin

### PR DESCRIPTION
**Pull request by Janchorizo**
First working version of a heatmap generator panel plugin.

### CODE REVIEW

**Comment by daniellee** [comment]
Before I review this, can you fix the version number both here in the PR and in the [plugin.json](https://github.com/Janchorizo/jancho-heatmap-panel/blob/master/src/plugin.json#L12) to be in the format: `x.x.x` (1.1.0 for example).

More details on review guidelines for the plugin.json file here: http://docs.grafana.org/plugins/developing/plugin-review-guidelines/#plugin-json

**Comment by daniellee** [comment]
@Janchorizo did you see my comment above? Let me know when you have fixed the version number.

**Comment by daniellee** [comment]
@Janchorizo did you make a change? It looks like the version number is still incorrect?

**Comment by alexanderzobnin** [comment]
@Janchorizo version in `plugin.json` is still incorrect (`1.0`).

**Comment by daniellee** [comment]
There has been no response for a long time so closing this PR. Open a new PR if you have time to update the plugin in the future.

**Pull request closed without merging**
