### PR TITLE
update histogram/heatmap panel

### PR DESCRIPTION
**Pull request by mtanda**
I update plugin documents.
https://github.com/mtanda/grafana-histogram-panel/issues/19
https://github.com/mtanda/grafana-heatmap-epoch-panel/issues/8

And fix some of heatmap-epoch panel bug.

### CODE REVIEW

**Comment by mtanda** [comment]
@torkelo Would you check the document again?
I add CHANGELOG to README.

**Comment by torkelo** [comment]
great!

**Comment by mtanda** [comment]
Thanks!

**Comment by mtanda** [comment]
@torkelo @daniellee 
The document is not update on grafana.net...
https://grafana.net/plugins/mtanda-histogram-panel

And I can't find heatmap-epoch panel in my user page.
https://grafana.net/mtanda

Did I do something wrong?

**Comment by daniellee** [comment]
Now its published: https://grafana.net/plugins/mtanda-histogram-panel

**Comment by mtanda** [comment]
@daniellee Thanks.

@torkelo 
> For histogram panel, we will need to test it a bit before making it available on grafana.net again.

You talk about heatmap-epoch panel?

**Comment by torkelo** [comment]
sorry, yes, got them confused, I meant heatmap panel

**Comment by mtanda** [comment]
I got it.
If some bug block the test process, please notify me.

**Comment by daniellee** [comment]
Hi @mtanda sorry for the long delay. I reviewed it and it seems fine now. I am publishing it as version 0.1.7 with the latest commit: e1ec956e86e55d9a3d06554df03641773c146fa9.

**Pull request merged**
