### PR TITLE
[Vertica]Bug fixes and query editor support

### PR DESCRIPTION
**Pull request by rajsameer**
Fixed bug in variable queries, previously would throw error if no result was returned from backend.
Moved to Code mirror 6 for editor support.
Added lines and gutter to query editor.

### CODE REVIEW

**Comment by marcusolsson** [comment]
Hey! I'm having some trouble getting Vertica running so that I can test this:

```
vertica_1  | Starting up
vertica_1  | Fixing filesystem permissions
vertica_1  | Creating database
vertica_1  | Database with 1 or 2 nodes cannot be k-safe and it may lose data if it crashes
vertica_1  | Distributing changes to cluster.
vertica_1  |    Creating database vdb
vertica_1  |    Starting bootstrap node v_vdb_node0001 (127.0.0.1)
vertica_1  |    Starting nodes: 
vertica_1  |            v_vdb_node0001 (127.0.0.1)
vertica_1  |    Starting Vertica on all nodes. Please wait, databases with a large catalog may take a while to initialize.
vertica_1  |    Node Status: v_vdb_node0001: (DOWN) 
vertica_1  |    Node Status: v_vdb_node0001: (DOWN) 
vertica_1  |    Node Status: v_vdb_node0001: (DOWN) 
vertica_1  |    Node Status: v_vdb_node0001: (DOWN) 
vertica_1  |    Node Status: v_vdb_node0001: (DOWN) 
vertica_1  |    Node Status: v_vdb_node0001: (DOWN) 
vertica_1  |    Node Status: v_vdb_node0001: (DOWN) 
vertica_1  |    Node Status: v_vdb_node0001: (DOWN) 
vertica_1  |    Node Status: v_vdb_node0001: (DOWN) 
vertica_1  |    Node Status: v_vdb_node0001: (DOWN) 
vertica_1  | ERROR:  Database did not start cleanly on initiator node!
vertica_1  |         Stopping all nodes
vertica_1  | Could not connect to database (EOF received)vsql: could not connect to server: Connection refused
vertica_1  |    Is the server running on host "127.0.0.1" and accepting
vertica_1  |    TCP/IP connections on port 5433?
vertica_1  | 
vertica_1  | Error: Database did not start cleanly on initiator node!  Stopping all nodes
```

I'm using the following Docker Compose:

```yaml
version: "3"
services:
  grafana:
    image: grafana/grafana:8.0.4
    ports:
      - 3000:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 1
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_INSTALL_PLUGINS: https://github.com/rajsameer/vertica-datasource/releases/download/v1.0.8/rajsameer-vertica-datasource-1.0.8.zip;rajsameer-vertica-datasource
    volumes:
      - ./provisioning:/etc/grafana/provisioning
    depends_on:
      - vertica

  vertica:
    image: jbfavre/vertica:9.2.0-7_debian-8
    environment:
      DATABASE_NAME: vdb
      DATABASE_PASSWORD: dbadmin
    ports:
      - 5433:5433
```

Any ideas on what might be wrong?

**Comment by rajsameer** [comment]
Hi, I use the following docker, i think you are missing capabilities for Vertica in your docker compose.
Below is the docker compose which works for me.
`version: '2.1'
services:
  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    #   GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s/grafana/"
    volumes:
      - ./dist:/var/lib/grafana/plugins/rajsameer-vertica-datasource
      - ./datasource:/etc/grafana/provisioning/datasources
      - ./dashboards:/etc/grafana/provisioning/dashboards
      - ./dashboard:/var/lib/grafana/dashboards
    ports:
      - "3007:3000"
  vertica:
    image: jbfavre/vertica:9.2.0-7_debian-8
    cap_add:
      - SYS_NICE
      - SYS_RESOURCE
      - SYS_PTRACE
    environment:
      - DATABASE_NAME=vdb
      - DATABASE_PASSWORD=dbadmin
    expose:
      - "5433/tcp"

`

**Comment by marcusolsson** [comment]
Thank you! Unfortunately that didn't help (but I'll keep it there anyways). I'll do some more troubleshooting this week.

**Comment by rajsameer** [comment]
Just in case you missed, you will need to elevate the privilege's of the user running the docker command. or try it with sudo.

**Comment by marcusolsson** [comment]
That worked!

FYI this is the final Docker Compose I'm running for testing:

```yaml
version: "3"
services:
  grafana:
    image: grafana/grafana:8.0.5
    ports:
      - 3000:3000
    environment:
      GF_INSTALL_PLUGINS: https://github.com/rajsameer/vertica-datasource/releases/download/v1.0.8/rajsameer-vertica-datasource-1.0.8.zip;rajsameer-vertica-datasource
    volumes:
      - ./provisioning:/etc/grafana/provisioning
    depends_on:
      - vertica

  vertica:
    image: jbfavre/vertica:9.2.0-7_debian-8
    privileged: true
    cap_add:
      - SYS_NICE
      - SYS_RESOURCE
      - SYS_PTRACE
    environment:
      DATABASE_NAME: vdb
      DATABASE_PASSWORD: dbadmin
    ports:
      - 5433:5433
```

**Comment by marcusolsson** [comment]
Published! 🎉

**Pull request merged**
