### PR TITLE
Added Diagram v1.4.5

### PR DESCRIPTION
**Pull request by jdbranham**
Let's try this again!
I fixed build script so we won't forget files in the dist folder anymore.

### CODE REVIEW

**Comment by torkelo** [comment]
The panel sets the height of the outer panel element in a way that it should not:
https://github.com/jdbranham/grafana-diagram/blob/master/src/diagramControl.js#L631 

ctrl.height is max height available for inner elements. You should not touch the outer panel element as this mess with the panel container. 

image

Resizing a panel does also not any effect on the diagram dimensions.

**Comment by torkelo** [comment]
seems to be related to this https://github.com/jdbranham/grafana-diagram/issues/87

**Comment by midnightconman** [comment]
@torkelo Can you give us more information on the issue? I have verified this plugin with grafana 5.4.2

**Comment by torkelo** [comment]
It does not respect its height and set it’s height in a wrong way. The v5 support issue is also still open

**Comment by jdbranham** [comment]
thanks @torkelo I updated the css line you referenced, and closed a few issues. Grafana v5 compatibility is also ready.

**Comment by midnightconman** [comment]
@torkelo Can you take a look at this? Some people are eager to see this upgrade available via grafana plugin distribution.

**Comment by torkelo** [comment]
It's a bit better maybe, but still does not adapt the panel height, like most panels. 

Is there a reason it's fixed height? you can use ctrl.height (on the panel controller) to get the available panel height. Use use flex box css layout to autmatically size the diagram and legend components. 

But it's ok to publish, not at least it does not change grafana panel container dimensions.

**Comment by alexanderzobnin** [comment]
@jdbranham grafana.com/plugins now supports change log, so you can add all notable changes into `CHANGELOG.md` in the root of repo in order to tell other people what's new.

**Comment by midnightconman** [comment]
Thank you :smile:

Maybe in 1.4.6 we can look at the enhancements you listed.

**Pull request merged**
