### PR TITLE
Update Consul datasource plugin to v0.2.1

### PR DESCRIPTION
**Pull request by sbueringer**
Hi,

I would like to submit an update for the [Consul datasource plugin](https://grafana.com/grafana/plugins/sbueringer-consul-datasource).

Changes are listed here: https://github.com/sbueringer/grafana-consul-datasource/blob/master/CHANGELOG.md

Looking forward to the merge.
Thanks!

### CODE REVIEW

**Comment by marcusolsson** [comment]
Great to see that you managed to get this signed and packaged!

I'll get started reviewing this. In the meantime, could you have a look at the issues reported by [the plugin validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/?url=https://github.com/sbueringer/grafana-consul-datasource/releases/download/v0.2.0/sbueringer-consul-datasource-0.2.0.zip)?

Can I ask where `info.build` property comes from? It's not documented and I'm trying to determine whether it's deprecated, or whether the documentation should be updated.

**Comment by sbueringer** [comment]
@marcusolsson 
Thx for reviewing :)

I've opened a PR to fix some (2 of 3) of the findings of the plugin validator: https://github.com/sbueringer/grafana-consul-datasource/pull/16
I would wait with the merge until we know what to do with the 3rd one.

Regarding `info.build` (which is the 3rd one):
* I'm building the plugin via Github actions with: `grafana-toolkit plugin:ci-package`
* looks like this task adds the `build.info` here: https://github.com/grafana/grafana/blob/a9ef0f84b8d58b78a5034f7be5bae1875ef8a8f2/packages/grafana-toolkit/src/cli/tasks/plugin.ci.ts#L156

I would guess it's just a mismatch between the validator and the `ci-package` task, wdyt?

**Comment by marcusolsson** [comment]
Thank you for the quick reply! The plugin validator uses the [official schema](https://grafana.com/docs/grafana/latest/developers/plugins/metadata/). It seems that `build` is missing from the schema. I'll continue to dig around so we can get it documented. Thanks for the info 👍 

You can ignore that one for now :)

**Comment by sbueringer** [comment]
@marcusolsson 
Okay :+1:
I merged the PR I linked above and changed this PR to reference to 0.2.1 version.

**Comment by marcusolsson** [comment]
[Published](https://grafana.com/grafana/plugins/sbueringer-consul-datasource?version=0.2.1)! 🎉 

Note that the Time series/Table data format has been superseded by the [data frame](https://grafana.com/docs/grafana/latest/developers/plugins/data-frames/) format. Meaning, there's no need to select between Time series and Table in the the query editor anymore.

Thank you for contributing! :)

**Comment by sbueringer** [comment]
> [Published](https://grafana.com/grafana/plugins/sbueringer-consul-datasource?version=0.2.1)! 
> 
> Note that the Time series/Table data format has been superseded by the [data frame](https://grafana.com/docs/grafana/latest/developers/plugins/data-frames/) format. Meaning, there's no need to select between Time series and Table in the the query editor anymore.
> 
> Thank you for contributing! :)

Thx and thx for the info :)

**Comment by sbueringer** [comment]
@marcusolsson One question, what do I have to do to get the Changelog.md visible here: https://grafana.com/grafana/plugins/sbueringer-consul-datasource?version=0.2.1 ?

**Comment by marcusolsson** [comment]
It will show up if there's a CHANGELOG.md in the packaged plugin. It should've be added as part of the build so it's weird that it's not there. I'll check if something's changed on our side.

**Comment by marcusolsson** [comment]
I've confirmed that this is a bug, which has been fixed in the latest version. Could you try updating to version 7.3.3 of grafana-toolkit and try again?

Here's the [issue](https://github.com/grafana/grafana/issues/28523) for more information.

**Comment by sbueringer** [comment]
@marcusolsson Thank you. Works with 7.3.3. Had it locked to 7.3.0 via yarn.lock. I'll then just include it in the next release

**Pull request merged**
