### PR TITLE
updated commit version to include new icon and sequence diagram css fix

### PR DESCRIPTION
**Pull request by jdbranham**

### CODE REVIEW

**Comment by DanCech** [comment]
In general we don't change released versions once they've been published, you're welcome to release 1.2.2 though

**Comment by DanCech** [comment]
Ah, I see 1.2.1 was broken anyway, I'll make an exception this time

**Comment by jdbranham** [comment]
cool, thanks Dan!
I'll double check the plugin.json next time!

**Comment by DanCech** [comment]
I'd also suggest tweaking the headings in your README.md to have a space between the hashes and the text, github will render them as headings but the markdown parser we use (remarkable) doesn't recognize it without the space.

**Comment by jdbranham** [comment]
thanks. will do.

**Pull request merged**
