### PR TITLE
Update williamvenner-timepickerbuttons-panel to 4.1.1

### PR DESCRIPTION
**Pull request by WilliamVenner**
Updates [williamvenner-timepickerbuttons-panel](https://github.com/WilliamVenner/grafana-timepicker-buttons) to version 4.1.1

Changes, thanks to @jburgess:

- Added new button stylings
- Added dropdown timepicking
- Added the ability to configure the mapping fields
- Added Ability to consume multiple 'rows' in a series
- Added the ability to use transformations on the button columns

Thanks for the CI pipeline by the way, it's very useful 👍🏻

### CODE REVIEW

**Comment by marcusolsson** [comment]
Hey, and thanks! 

It looks like you're using an older version of the pipeline that unfortunately prints the URL to the draft release asset rather than the published release asset. 

The Release pipeline creates a draft release that allows you to write release notes before publishing it. I can see that there's a 4.1.1 release, but I don't see the packaged plugin ZIP as a release asset. Could you please have a look and make sure the URL points to the ZIP archive that contains the plugin?

**Comment by WilliamVenner** [comment]
@marcusolsson Would this be the correct URL?:

https://github.com/WilliamVenner/grafana-timepicker-buttons/releases/download/v4.1.1/williamvenner-timepickerbuttons-panel-4.1.1.zip

If so I will update the URL in this PR.

**Comment by marcusolsson** [comment]
Yes, that seems to work for me!

**Comment by marcusolsson** [comment]
Published! 🎉

**Pull request merged**
