### PR TITLE
Bump Annunciator panel plugin to v1.1.0

### PR DESCRIPTION
**Pull request by michaeldmoore**
This is the first attempt using the new toolkit workflow, so let's hope I got this right.

```
{
  "id": "michaeldmoore-annunciator-panel",
  "type": "panel",
  "url": "https://github.com/michaeldmoore/michaeldmoore-annunciator-panel",
  "versions": [
    {
      "version": "1.1.0",
      "commit": "43d1cf3a687ec1f2e59e52044f96ef66d4a85960",
      "url": "https://github.com/michaeldmoore/michaeldmoore-annunciator-panel",
      "download": {
        "any": {
          "url": "https://github.com/michaeldmoore/michaeldmoore-annunciator-panel/releases/download/untagged-27ef6f822e34e578f271/michaeldmoore-annunciator-panel-1.1.0.zip",
          "md5": "2f974f20029a10990a67b7da347b5cd5"
        }
      }
    }
  ]
}
```

### CODE REVIEW

**Comment by marcusolsson** [comment]
I see that you're using the GitHub workflow, awesome!

The GitHub workflow creates a draft release, so that you can make any last changes to it before you publish it. It looks like you might not yet have published the release. Once you do, you can right-click the zip file in the list of release assets and update the URL for this version.

From what I can see, the JSON entry in your description looks good to me. Could you update the repo.json from:

```
{
  "version": "1.1.0",
  "commit": "43d1cf3a687ec1f2e59e52044f96ef66d4a85960",
  "url": "https://github.com/michaeldmoore/michaeldmoore-annunciator-panel"
}
```

to 

```
{
  "version": "1.1.0",
  "commit": "43d1cf3a687ec1f2e59e52044f96ef66d4a85960",
  "url": "https://github.com/michaeldmoore/michaeldmoore-annunciator-panel",
  "download": {
    "any": {
      "url": "<UPDATED_URL>/michaeldmoore-annunciator-panel-1.1.0.zip",
      "md5": "2f974f20029a10990a67b7da347b5cd5"
    }
  }
}
```

Let me know if you run into any issues!

**Comment by michaeldmoore** [comment]
Marcus (or whoever)

Re.  Multistat, Annunciator and Scatter panel plugins

All 3 of my community-signed panel plugins have been stuck in
review/metadata holding hell for over 3 weeks.  Any chance I can get some
attention on these?

We last discussed this when you suggested supporting the new github release
workflow action, which I added.  The repo.json file was updated to use the
new format and as far as i can see, they are ready to go.

Regards,
Michael Moore

**Comment by marcusolsson** [comment]
Hi, and thank you for your patience on this 🙏 

The URL in this pull request seems to point to a zipped archive of the repository rather than the packaged plugin. I can see that the GitHub workflow has finished, but I can't see the release created by the workflow. Note that the workflow creates a _draft_ release that you need to manually publish when you feel it's ready for the prime time.

I believe the steps needed are:

1. Go to [Releases](https://github.com/michaeldmoore/michaeldmoore-annunciator-panel/releases) and verify whether there's a release created by the **github-actions** user
2. If there is, click the release, then **Edit release**, and choose to publish it
3. If there isn't a release in there, try and create a new tag and check again once the workflow has finished
4. The release should have a release asset called `michaeldmoore-annunciator-panel-1.1.0.zip`. Right-click it and copy the link. Update the pull request with the new link (and MD5).

I'll move your submissions to Waiting for Review to prioritize them.

**Comment by michaeldmoore** [comment]
OK - this time I think I've got it working.  All three PRs have been
updated to use the proper zip files which make perfect sense.

Something seems bizarre though.

When creating the initial tags, github insists on creating a release,
containing the zipped up source files.

This triggers the release workflow, creating - as you said - a
draft release of the 'ready to use' package.  But pointing to the same
tag.  It won't allow the draft release to be published while there is this
duplicate tag.

The only way I've been able to make this work is to then go back and delete
the initial release (the one generated by the initial tagging operation),
and then manually publishing the draft.  Weird.  What's more, the release
generated by the workflow always seems to have the title of the previous
version - Somehow, this doesn't seem to matter, but it bothers me.
[image: image.png]

Multistat, Annunciator and Scatter - all ready for review.

Thanks again
Michael Moore

**Comment by marcusolsson** [comment]
Tested and it looks good now!

I see that you've removed the previous versions of the plugin in your PR. I assume you don't mean to unpublish them? If not, could you add them back (it's fine to use the previous format for older releases).

I went ahead and published the plugin, but I'll leave the PR open until you've addressed my previous point. 

As for your other comments, did you create a tag from the GitHub UI or did you push a tag from your local machine? 

This is what I run on my local machine to trigger the release workflow:

```
git tag -a v0.10.1 -m "Release v0.10.1" && git push origin v0.10.1
```

The version in the name of the release asset is extracted from the plugin json. If it has the previous version, check the version `package.json` and make sure it's the same version.

**Comment by michaeldmoore** [comment]
Awesome, thanks!

And yes, I created the tag and promoted it to a release using the github UI.

Net time, I'll try doing it in my local repo.

I'll re-add the old references soon and drop you a note in the PR.
Thanks again

**Comment by michaeldmoore** [comment]
I re-added the old Annunciator references, as requested

**Pull request merged**
