### PR TITLE
ClickHouse Database datasource plugin update to 2.3.1

### PR DESCRIPTION
**Pull request by Slach**
# 2.3.1 (2021-04-23)
## Breaking changes

* On latest Grafana 7.x releases, template variables SQL queries shall return only scalar types of values, see https://github.com/Vertamedia/clickhouse-grafana/issues/328

## Enhancement:

* add support Apple M1 ;)
* switch to new grafana plugin Golang SDK, thanks to @bmanth60 and @valeriakononenko for help
* add BasicAuth support for alerts, see https://github.com/Vertamedia/clickhouse-grafana/issues/267

## Fixes:

* fix github actions backend build
* fix UNION ALL parsing, see https://github.com/Vertamedia/clickhouse-grafana/issues/319
* fix many issues with alerting
  * https://github.com/Vertamedia/clickhouse-grafana/issues/305
  * https://github.com/Vertamedia/clickhouse-grafana/issues/327
  * https://github.com/Vertamedia/clickhouse-grafana/issues/334
  * https://github.com/Vertamedia/clickhouse-grafana/issues/335

Signed-off-by: Eugene Klimov <eklimov@altinity.com>

### CODE REVIEW

**Comment by Slach** [comment]
@marcusolsson could you look to this PR ?
why PR still not merged? why process so complicated and continue more than 1 month?

**Comment by daniellee** [comment]
I have a question about the Yandex.Cloud authorization headers. The X-ClickHouse-Key field is saved in jsonData (clear text) and it is easy to see the value for it in the network request. Is this a credential that should be saved in secureJsonData and added as a header on the backend instead?

It is used on the backend here: https://github.com/Vertamedia/clickhouse-grafana/blob/master/pkg/client.go#L52 but also on the frontend: https://github.com/Vertamedia/clickhouse-grafana/blob/master/src/datasource.ts#L84

**Comment by Slach** [comment]
@daniellee feel free make pull request on : https://github.com/Vertamedia/clickhouse-grafana/

**Comment by Slach** [comment]
@marcusolsson could you look to PR?

**Comment by Slach** [comment]
oh, sorry, @daniellee ok. I can prepare secureJson PR with different release
is it required to merge PR?

**Comment by daniellee** [comment]
Sounds like a plan as this is not part of this change and was introduced a long time ago. Will merge this and then you can follow up with the fix.

**Comment by Slach** [comment]
@daniellee thanks a lot, I promise a next release will try to use `secureJSON` for `X-Auth-Key` and `X-ClickHouse-User` on frontend and backend part

**Review by daniellee — APPROVED** [review]
Lots of changes in this release. The new authentication changes look good. While going through the code noticed that the frontend does not handle the Yandex API key in a secure way and that will need to be fixed in the near future.

**Pull request merged**
