### PR TITLE
Added traffic-light plugin

### PR DESCRIPTION
**Pull request by vmanilo**

### CODE REVIEW

**Comment by daniellee** [comment]
Could you make this image a bit smaller: https://github.com/smartmakers/grafana-trafficlight/blob/master/dist/img/view.png

Either with Image Magick - something like this:

`mogrify -resize 80% src/img/view.png` 

or some other tool like [pnggauntlet](https://pnggauntlet.com).

**Comment by vmanilo** [comment]
Hey, @daniellee, thanks for suggestion, I downsized this image

**Comment by vmanilo** [comment]
Do I need to change commit hash in repo.json?

**Comment by daniellee** [comment]
@vmanilo yes, please.

**Comment by vmanilo** [comment]
@daniellee done

**Comment by daniellee** [comment]
Merged and published: https://grafana.com/plugins/smartmakers-trafficlight-panel

## Plugin Feedback

Everything works as it should and the readme looks fine. 

There is one thing that could be improved and that is that the values returned from the query must be 1, 2 or 3. Some sort of threshold management would make this plugin more accessible so that a user could assign a range of values to be red/amber/green -> 0-100 == red, 101-200 == amber,  201+ == green

We are redoing the threshold function in the singlestat and other similar panels so we could export that as a lib that you and other plugin authors could use. That will be released in August or September.

**Comment by vmanilo** [comment]
@daniellee I appreciate your help 👍

**Pull request merged**
