### PR TITLE
Adding a vertica data source plugin

### PR DESCRIPTION
**Pull request by rajsameer**
This pull request adds a new Vertica data source. This is a backend plugin , as of now I have been using a private sing method to sign my plugin. I would need a new signature level to make it a public sign.

### CODE REVIEW

**Comment by rajsameer** [comment]
@marcusolsson , I have not received any comments regarding the plugin. Will review take more time?

**Comment by marcusolsson** [comment]
Hi @rajsameer,

You can see the review pipeline on the [project board](https://github.com/grafana/grafana-plugin-repository/projects/2). We currently can't offer estimates, but at least you can see your place in the review queue.

Thank you for your patience,
Marcus

**Comment by rajsameer** [comment]
update: In order to test this plugin, we will provide a docker compose of vertica and grafana. Along with a dashboard to test features.

**Comment by rajsameer** [comment]
@marcusolsson , I have added the docker compose, data source and dashboard for testing.

**Comment by marcusolsson** [comment]
Published! 🎉

Please allow for some time before it becomes available on the marketplace. Thanks for the help on getting the test environment up and running 🙏

**Comment by rajsameer** [comment]
Hi Marcus,

Thanks for the assistance.

Regards
Sameer

**Pull request merged**
