### PR TITLE
Included video panel

### PR DESCRIPTION
**Pull request by loredanaPopescu**
Add Video Panel plugin - a panel to display video from a URL, YouTube ID, or an iFrame.

### CODE REVIEW

**Comment by marcusolsson** [comment]
Hey @loredanaPopescu, and thanks for considering contributing your plugin!

I've reviewed your plugin, and can confirm that it seems to be working as intended.

I have a few minor comments:

- Would it make sense for "URL" say "File" instead to describe what the URL is referencing?
- Should use the correct capitalization of YouTube (not "Youtube").
- I think HTML tags should be kept lowercase, i.e. "iframe", not "Iframe".

Screen Shot 2020-09-29 at 14 05 11

- Use the field description and placeholders to help the user figure out what to put in the input field. Here are some suggestions, on top of my head (feel free to change it to whatever you think makes sense):



Screen Shot 2020-09-29 at 14 07 49

Screen Shot 2020-09-29 at 14 10 54

These are all minor comments, and I'd be happy to publish this as is, though I think the suggested changes would make your panel more accessible and easier to use. Let me know if you want to make the changes before I publish!

**Comment by loredanaPopescu** [comment]
Hey @marcusolsson,

Thanks for reviewing the plugin. I will send an updated version shortly addressing your suggestions :)

**Comment by loredanaPopescu** [comment]
Hi @marcusolsson ,

I've updated the plugin and the PR. Feel free to merge it when you can.

Thanks!

**Comment by marcusolsson** [comment]
That was fast! Looks great! 🎉 

I ran into some trouble while trying to publish the plugin. Currently, we don't allow files larger than 1 MB, and 
[examples.png](https://github.com/innius/grafana-video-panel/blob/master/src/img/examples.png) is 1.86 MB. 

Would you mind reducing the file size of the image and updating your PR? 🙏

**Comment by loredanaPopescu** [comment]
Hi @marcusolsson ,

I've updated the plugin and the PR with a new image for example.png.

Thanks!

**Comment by marcusolsson** [comment]
It seems that the old image is still causing trouble. Do you mind removing it? 

https://github.com/innius/grafana-video-panel/blob/40cd3f25bb1555d4a325dd5807b8e2441aeaf744/dist/img/examples.png

**Comment by loredanaPopescu** [comment]
Fixed @marcusolsson 

Thank you :)

**Comment by marcusolsson** [comment]
[Published](https://grafana.com/grafana/plugins/innius-video-panel)! 🎉 

Thank you! This is a really cool plugin. Do you mind if I tweet about this? If ok, do you have a username you want me to mention? :)

**Comment by loredanaPopescu** [comment]
Hey @marcusolsson, I don't have a twitter account you can mention, but feel free to tweet about it if you want 😃 👍

**Pull request merged**
