### PR TITLE
Update linksmart-sensorthings to v1.4.0

### PR DESCRIPTION
**Pull request by farshidtz**
Hi,

I would like to submit an update for [SensorThings](https://grafana.com/plugins/linksmart-sensorthings-datasource) plugin. Changelog is [here](https://github.com/linksmart/grafana-sensorthings-datasource/blob/master/CHANGELOG.md).

Instructions to start a SensorThings server with dummy data to test the plugin: https://github.com/linksmart/sensorthings-faker

Looking forward to the merge.
Thanks!

### CODE REVIEW

**Comment by marcusolsson** [comment]
Thank you for your patience while waiting for us to review your plugin. 

We're working hard at improving the plugin experience for both users and authors. I'd like to share some important information on how to package and publish plugins going forward.

Since Grafana 7.3, we require all plugins to be _signed_. By signing your plugin, users can guarantee the integrity of the plugin and that the plugin version they've installed hasn't been modified since it was released. For more information on how to sign your plugin, refer to [Sign a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/).

With this, we now require plugins to be _packaged_ before we publish them. This means that instead of a commit containing a `dist` directory, you will need to submit a link to a ZIP archive containing your plugin. For more information on how to package your plugin, refer to [Package a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/).

Once you've packaged your plugin, you'll need to update your entry to `repo.json` to the new format. You can read more on how to do this under [Add a plugin to repo.json](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson).

To summarize, to publish your plugin, make sure that you:

1. [Sign your plugin](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/)
2. [Package your plugin](https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/)
3. Create a new GitHub release and upload the packaged plugin as a release asset
4. [Update your repo.json entry](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson)

Here's an [example](https://github.com/marcusolsson/grafana-jsonapi-datasource/releases/tag/v0.6.0) of a properly packaged plugin. In the same repository, you can find a [GitHub Action](https://github.com/marcusolsson/grafana-jsonapi-datasource/blob/master/.github/workflows/main.yml) that signs, packages, and releases the plugin whenever you create a new tag.

Once you've created a GitHub release with the packaged plugin, you can right-click the release asset, copy the link, and validate it using [the plugin validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app). 

Finally, in the November [community call](https://groups.google.com/g/grafana-developers/c/ps2vzCXRDCM/m/i7uAK1u9AQAJ), I'll be walking through the steps needed to sign and package your plugin. A recording will be made available on our [YouTube account](https://www.youtube.com/playlist?list=PLDGkOdUX1Ujo0OyE5HFffHE9GJVvaVXGs), in case you can't make it.

**Comment by marcusolsson** [comment]
Closing due to lack of activity.

**Comment by farshidtz** [comment]
After spending much time and failing to sign, we decided not to publish the update. The latest version has many improvements and would be available via Github.

**Comment by marcusolsson** [comment]
I'm sorry to hear that you had problems while signing. If you want to give it another shot, I'd be happy to help you out. If it's easier for you, we can also hop into a video call. You can book a time slot [here](https://calendly.com/marcusolsson/plugin-development).

From Grafana 8.0, unsigned plugins won't load by default so you might hear from users who can no longer load the plugin after they upgrade. They can explicitly allow loading unsigned plugins by listing the plugin ID in `GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS`.

**Comment by farshidtz** [comment]
Thanks for the offer. I'm afraid we don't have the resources to continue the development of this plugin at this point. We will come back to it as soon as possible.

**Pull request closed without merging**
