### PR TITLE
Update JSON datasource to v0.1.2

### PR DESCRIPTION
**Pull request by simPod**
We're adding support for variables processing in our Additional JSON Data field

### CODE REVIEW

**Comment by daniellee** [comment]
@simPod the version number is incorrect in the plugin.json in dist: https://github.com/simPod/grafana-json-datasource/blob/next/dist/plugin.json#L23

**Comment by simPod** [comment]
@daniellee Thanks! Fixed now

**Comment by alexanderzobnin** [comment]
@simPod You shouldn't rewrite version in `repo.json`. Intead of, you should add new one, like:
```json
      "url": "https://github.com/simPod/grafana-json-datasource",
      "versions": [
        {
          "version": "0.1.1",
          "commit": "f7c8f8d88e19abf4d60c58bba5fee60cf79aec55",
          "url": "https://github.com/simPod/grafana-json-datasource"
        },
        {
          "version": "0.1.2",
          "commit": "008125de3ae103a67cdc53092363233e3833e6cf",
          "url": "https://github.com/simPod/grafana-json-datasource"
        }
      ]
```

**Comment by simPod** [comment]
Fixed, thanks

**Comment by alexanderzobnin** [comment]
@simPod version in `dist/` still `0.1.1`, it seems, plugin wasn't rebuilt:
https://github.com/simPod/grafana-json-datasource/blob/008125de3ae103a67cdc53092363233e3833e6cf/dist/plugin.json#L23

**Comment by simPod** [comment]
@alexanderzobnin wrong commit hash. Uff, very challenging. Updated, thanks!

**Comment by alexanderzobnin** [comment]
Yea, I'm working on CI for plugin, now if you push a PR, it will be checked automatically by CircleCI for these kinds of errors (wrong version, missing build, etc). You can test it by rebasing your PR against a master branch.

**Comment by simPod** [comment]
Cool. I'm green

**Comment by alexanderzobnin** [comment]
@simPod Could you add `author` section in `plugin.json`? It doesn't look well without it:

screenshot from 2019-02-28 11-46-32

I've added this check to linter as well.

**Comment by simPod** [comment]
@alexanderzobnin updated. Thanks

**Comment by alexanderzobnin** [comment]
@simPod We don't think "Grafana Friends" is an appropriate author name. It may mislead people. Please, change it to the real name/company name.

**Comment by simPod** [comment]
I have made another change. The code was originally developed by Grafana Project, than we took over because there was no activity from Grafana anymore. But it was not just me who did the work so I don't want to attribute it all to myself. Also, there's no company behind it. Hope it's fine now.

The build fails on
> Error: Updated version should be greater than previous: 1.0.2 < 1.1.0 (plugin: michaeldmoore-multistat-panel)
I think that's a bug in CI tool

**Comment by alexanderzobnin** [comment]
@simPod Build fails due to outdated branch, so nevermind.

**Comment by simPod** [comment]
@alexanderzobnin thanks!

I guess it reads author from github and not json file tho ;)

image

**Comment by alexanderzobnin** [comment]
@simPod yes, but for the plugins list inside grafana author should be set in `plugin.json`.

**Comment by zak-b2c2** [comment]
Is this published?

**Comment by alexanderzobnin** [comment]
@zak-b2c2 yes https://grafana.com/plugins/simpod-json-datasource?version=0.1.2

**Pull request merged**
