### PR TITLE
update Belugacdn app to 1.1.1

### PR DESCRIPTION
**Pull request by 140am**
- update company logo

https://github.com/belugacdn/grafana-belugacdn-app/compare/v1.1.0...v1.1.1

### CODE REVIEW

**Comment by DanCech** [comment]
Please add the new version above the old one rather than replacing it.

**Comment by 140am** [comment]
@DanCech I have added the update as a new `versions` entry and also added the original 1.0.0 reference from https://github.com/grafana/grafana-plugin-repository/pull/69.

**Comment by DanCech** [comment]
You need to update the version in plugin.json to 1.1.1 before grafana-net will accept it

**Comment by 140am** [comment]
Forgot about that :( This will result in a new commit hash - should i open a pull request for an updated 1.1.1 `versions` entry afterwards or tag it as 1.1.2 ?

**Comment by daniellee** [comment]
Hi @140am 

I messed up when publishing this at GrafanaCon and missed that the plugin id is incorrect. Currently it is  `grafana-belugacdn-app'  but it should be just 'belugacdn-app'. The grafana part means the app got published under the Grafana org as the convention for the plugin id is org-name-type or org-type.

This is going to be a problem for people who have already installed the app. When the plugin id is changed they won't get any upgrade notifications when you release a new version. 40-50 users have it installed currently according to our stats.

I really apologise for this and for any inconvenience to your users. Do you have any way of contacting them easily? Our stats are anonymous so we only know how many not who.

Regards,
Daniel

**Comment by 140am** [comment]
@daniellee updating the package.json right now with the new `id` and will create a pull request under a 1.2.0 tag shortly. is it ok if i remove/replace the just added 1.1.1 tag with the new 1.2.0 as this only introduced the logo update or prefer a new addition and keep the 1.1.1 entry? we unfortunately do not have a way to contact users specifically but will emphasis the new installation ID on upcoming future announcements.

**Comment by daniellee** [comment]
It's fine to remove 1.1.1 as it is not published.

Let us know if we can do anything to help - maybe a tweet from the Grafana account?

**Comment by 140am** [comment]
@daniellee i created a new pull request with the requested changes.

thank you for the generous offer and prompt help - we would love a tweet from your side about our plugin. we are working on some announcements around using grafana together with our plugin for infrastructure monitoring where we will mention the new plugin id. once we will do a bigger plugin update we will highlight that a new installation with `belugacdn-app` as id will be required to address existing users.

**Pull request merged**
