### PR TITLE
Publishing V1.0.1

### PR DESCRIPTION
**Pull request by abhijeet-teli**
Doc Updates
Added Sample Dashboards
Few minor fixes

### CODE REVIEW

**Comment by briangann** [comment]
There are extra files inside the zip that were not included during signing, you'll need to re-run the release process to include all of the files in the final zip file before signing.  The `MANIFEST.txt` file should have all files listed.

These are the files:
```
bmchelix-ade-datasource/dashboards/events_dashboard.json
bmchelix-ade-datasource/dashboards/metrics_dashboard.json
```

Grafana disables the plugin if the signature is modified (detected when the content of the zip does not exactly match the manifest file)

**Review by briangann — CHANGES_REQUESTED** [review]
see comment above, the plugin needs to be repackaged and signed

**Comment by abhijeet-teli** [comment]
Thanks Brian,
Changes committed as requested

**Comment by briangann** [comment]
this looks good now.

if you want to allow user to be able to import sample dashboards you can include them in the src/plugin.json file like this:

```
"includes": [
   { "type": "dashboard", "name": "BMC Events Example", "path": "dashboards/events_dashboard.json" },
   { "type": "dashboard", "name": "BMC Metrics Example", "path": "dashboards/metrics_dashboard.json" }
 ],
```

and if you want to enable alerting, add:

```
  "alerting": true,
```

**Review by briangann — APPROVED** [review]

**Comment by abhijeet-teli** [comment]
> this looks good now.
> 
> if you want to allow user to be able to import sample dashboards you can include them in the src/plugin.json file like this:
> 
> ```
> "includes": [
>    { "type": "dashboard", "name": "BMC Events Example", "path": "dashboards/events_dashboard.json" },
>    { "type": "dashboard", "name": "BMC Metrics Example", "path": "dashboards/metrics_dashboard.json" }
>  ],
> ```
> 
> and if you want to enable alerting, add:
> 
> ```
>   "alerting": true,
> ```

Hi Brian,

Thanks for the pointers, We are planning to add few more sample dashboards in next monthly push, Will follow the suggested process. 

We are still making progress in alerting feature, once done & validated from our side will publish it.

**Pull request merged**
