### PR TITLE
Add a new app: GLPI

### PR DESCRIPTION
**Pull request by ddurieux**
Add a new app called 'glpi_app_grafana'. The goal is to get data in GLPI (asset management / servicedesk) and display them into Grafana ;)

### CODE REVIEW

**Comment by daniellee** [comment]
Thanks for submitting this. I just started looking at this. Most of the meta data looks good (especially the readme!) but I noticed that the plugin id in the plugin.json file does not follow the [convention](http://docs.grafana.org/plugins/developing/code-styleguide/#plugin-json-mandatory). It should be `ddurieux-glpi-app`.

I got GLPI up and running locally but got a bit stuck on the permissions for the rest api. I will try again tomorrow and get back to you with more feedback then.

**Comment by ddurieux** [comment]
Oh sorry, I missed the id convention :(
I will fix it in few hours

**Comment by daniellee** [comment]
I've gotten totally stuck on connecting to the api via Grafana. Have it working via postman but when I try to do in proxy mode in Grafana I keep getting IP filter errors saying IP address 127.0.0.1 is not allowed. Do you use proxy or direct? I can probably get it working with direct and changing the CORS headers in Apache but I'm wondering if that is the normal use case?

These are my api client settings (have tried a few different settings and ranges here):

image

**Comment by daniellee** [comment]
Nevermind, got it working with CORS headers.

**Comment by daniellee** [comment]
Thanks for your patience, here is my feedback:

### Metadata
- The readme is pretty good but maybe could include a few more details about how to enable the rest api and links to how to set CORS headers for apache/nginx.

### Plugin

For the query tab, is there anyway to abstract away the url? Starting here with "undefined", I'm not sure how I would build a query without the included dashboard:

 image

When I tried to copy and paste in queries it only worked sometimes. I don't have any good ideas on how to do it better as there seem to be a million possible parameters to include in a query. But maybe a few predefined common queries that the user can select from a dropdown would be a good start.

None of these are showstoppers and can be done in the next version.

Published: https://grafana.com/plugins/ddurieux-glpi-app

**Pull request merged**
