### PR TITLE
Add QuasarDB Grafana Datasource Plugin

### PR DESCRIPTION
**Pull request by kontrarian**
# QuasarDB Datasource

QuasarDB runs in insecure mode which allows for anonymous login, and secure mode which requires a username and secret key.

## Setting up

Please note this is just for demonstration purposes and not the recommended way to set up QuasarDB

A complete environment can be build with docker using the following command.

```
docker build -t qdb-grafana-example-docker https://github.com/kontrarian/qdb-grafana-example-docker.git
```

The updated `dist/` folder is included in the plugin git repository so it can be cloned directory to the grafana plugins directory to install it.

## Testing Anonymous Login

```
docker run -it -p 40080:40080 qdb-grafana-example-docker
```

This will start the QuasarDB db server and rest server in the background, log you into bash and print the server url to the console.

In the plugin configuration set the `URL` to `http://127.0.0.1:40080` and the `Access` to `Server`. Auth can be skipped and toggle off `Use Secured Cluster` under QuasarDB Details

## Testing Secure Login

```
docker run -it -p 40493:40493 --env QDB_SECURITY=true qdb-grafana-example-docker
```

This will start the QuasarDB db server and rest server in the background, log you into bash and print the server url and user credentials to the console.

In the plugin configuration set the `URL` to `https://127.0.0.1:40493` and the `Access` to `Server`. Under Auth ensure `Skip TLS Verify` is checked as this demo uses self-signed TLS certificates. Under QuasarDB Details toggle on `User Secured Cluster` and enter the `User name` and `User secret` that were printed to the console when you ran the docker container.

Please ping me if there is anything you need.

Kind regards,
Mike

### CODE REVIEW

**Comment by kontrarian** [comment]
Hey @briangann, I think my PR might have slipped through the cracks as I see some PRs that were open more recently are being reviewed.

Please let me know if there is anything else I can do to simplify testing the datasource. I'm happy to put in whatever legwork is necessary to make it as easy as possible to review the plugin.

**Comment by alexanderzobnin** [comment]
@kontrarian Sorry for delay, trying to review it now.

**Comment by alexanderzobnin** [comment]
@kontrarian I tested connection to database, it works, but I can't see any data in the DB and can't test queries. Could you point me to the example query I can execute against your test env? Also, plugin ID should be in form of `<user>-<plugin_name>-<datasource>`, but you pushed it as `qdb-grafana-datasource`. The proper ID is something like `kontrarian-quasardb-datasource`.

**Comment by kontrarian** [comment]
Hey @alexanderzobnin, thanks for taking the time to review the plugin. I'm away today but will update the docker image with some seed data early next week.

What is the correct naming scheme for companies? **quasardb-quasardb-datasource** seems a bit redundant, but we wouldn't want the plugin name associated with a particular user if possible

**Comment by alexanderzobnin** [comment]
@kontrarian `quasardb-quasardb-datasource` looks OK, we have similar examples, like `percona-percona-app`.

**Comment by daniellee** [comment]
@kontrarian `quasardb-datasource` is the more common form (but the longer form is also valid). From the [guidelines](https://grafana.com/docs/plugins/developing/plugin-review-guidelines/#plugin-json):

`Although if org and plugin name are the same then [plugin name]-[datasource|app|panel] is also valid`

**Comment by alexanderzobnin** [comment]
@daniellee good catch, missed this!

**Comment by kontrarian** [comment]
Hey @alexanderzobnin  and @daniellee ,

Thanks for you help with this. I've changed the plugin name to `quasardb-datasource` and updated the docker image to seed some bitcoin exchange data for 2019. 

You'll need to remove the `qdb-grafana-example-docker` image and any associated containers and then follow the instructions above again to get the updated container running.

The timeseries name is `btcusd` and it has the columns `open`, `close`, `high` and `low`. Here's an example test query:

```
select avg(low), max(high) from btcusd in $__range group by $__interval
```

Let me know if you run into any problems or if there is anything else I can do to help.

**Comment by alexanderzobnin** [comment]
Ok, looks good!

**Comment by alexanderzobnin** [comment]
@kontrarian I've merged your PR, but in order to publish it, I need to get organization `quasardb` exist at grafana.com. Please, create it and let me know.

**Comment by kontrarian** [comment]
Hi @alexanderzobnin,

I've set up the quasardb org on grafana.com. Please let me know when the plugin is published so that I can update our marketing team.

Thanks again for your help

**Comment by alexanderzobnin** [comment]
@kontrarian Now it's alive!
https://grafana.com/grafana/plugins/quasardb-datasource

**Pull request merged**
