### PR TITLE
Update fetzerch-sunandmoon-datasource plugin (v0.2.0)

### PR DESCRIPTION
**Pull request by fetzerch**
Fixed

* Glitches in graphs caused by out of order data. (#29, grafana/#28804)
* Annotations are no longer shown. (#31)
* A metric is now preselected when using the datasource on a new panel.

Added

* Location is now automatically configured.

Changed

* The plugin was migrated to the new plugin framework introduced in
  Grafana 7.0 and is no longer compatible with older versions of
  Grafana.

---
See the "dev-env" directory for how to setup a minimal docker environment for testing.

### CODE REVIEW

**Comment by marcusolsson** [comment]
Thank you for your patience while waiting for us to review your plugin. 

We're working hard at improving the plugin experience for both users and authors. I'd like to share some important information on how to package and publish plugins going forward.

Since Grafana 7.3, we require all plugins to be _signed_. By signing your plugin, users can guarantee the integrity of the plugin and that the plugin version they've installed hasn't been modified since it was released. For more information on how to sign your plugin, refer to [Sign a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/).

With this, we now require plugins to be _packaged_ before we publish them. This means that instead of a commit containing a `dist` directory, you will need to submit a link to a ZIP archive containing your plugin. For more information on how to package your plugin, refer to [Package a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/).

Once you've packaged your plugin, you'll need to update your entry to `repo.json` to the new format. You can read more on how to do this under [Add a plugin to repo.json](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson).

To summarize, to publish your plugin, make sure that you:

1. [Sign your plugin](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/)
2. [Package your plugin](https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/)
3. Create a new GitHub release and upload the packaged plugin as a release asset
4. [Update your repo.json entry](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson)

Here's an [example](https://github.com/marcusolsson/grafana-jsonapi-datasource/releases/tag/v0.6.0) of a properly packaged plugin. In the same repository, you can find a [GitHub Action](https://github.com/marcusolsson/grafana-jsonapi-datasource/blob/master/.github/workflows/main.yml) that signs, packages, and releases the plugin whenever you create a new tag.

Once you've created a GitHub release with the packaged plugin, you can right-click the release asset, copy the link, and validate it using [the plugin validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app). 

Finally, in the November [community call](https://groups.google.com/g/grafana-developers/c/ps2vzCXRDCM/m/i7uAK1u9AQAJ), I'll be walking through the steps needed to sign and package your plugin. A recording will be made available on our [YouTube account](https://www.youtube.com/playlist?list=PLDGkOdUX1Ujo0OyE5HFffHE9GJVvaVXGs), in case you can't make it.

**Comment by fetzerch** [comment]
@marcusolsson Thanks much for that detailed explanation. Regarding the signing, I've already sent an email a week ago to plugins@grafana.com to request the signature level.

**Comment by marcusolsson** [comment]
Thank you. Since then, we've set the plugin signature level on all plugins that have been published in the past. Only new plugins will require you to request a signature level. 

You should be able to sign you plugin now! If not, let me know!

**Comment by fetzerch** [comment]
Cheers, I've updated the PR.

**Comment by marcusolsson** [comment]
Really cool plugin that I haven't seen before 👍 I only have a few minor comments that I think would make the plugin a little easier to use. I don't mind publishing this as is though. Let me know if you'd like to hold off for another version!

- In the config editor, the long/lat text fields have inconsistent widths, ideally with enough space to hold a more exact coordinate
- The current placeholder merely repeats the label. What about changing the placeholders to be an actual position, to let people know what format the plugin expects?

Screen Shot 2020-11-19 at 14 35 29

Screen Shot 2020-11-19 at 14 40 11

- Screenshots should be updated for 7.x
- I would've liked some information about the units for each metric so that I can configure my axes correctly. Probably fine to just have it documented in the README.

**Comment by fetzerch** [comment]
Thanks for the valuable feedback! That helps a lot.

I've improved the config editor. Does this match your expectation? Also note that the plugin uses the browser's geolocation feature to fill the fields. Unfortunately that just works with https (or grafana running on localhost).

grafik

Regarding your last point, how about adding this as description to the query editor?

grafik

If that's ok, then I'll try to adapt the tests, automate the release generation and push a new release during the weekend.
Also I'll add the possibility to provide an alias in the query editor. That has been a feature request I got.

**Comment by marcusolsson** [comment]
That looks great! 👍 I'll give this another go today! 

Just an FYI regarding the Alias feature. We are slowly phasing that out from our plugins since you can now rename any field in Grafana using Transformations and/or Field options.

**Comment by fetzerch** [comment]
Thanks, I've just updated the release now.

Indeed, I didn't think of the transformations. Won't add the alias then.

**Comment by marcusolsson** [comment]
[Published](https://grafana.com/grafana/plugins/fetzerch-sunandmoon-datasource?version=0.2.0)! 🎉

**Pull request merged**
