### PR TITLE
0.2.5 uppdate flowcharting panel

### PR DESCRIPTION
**Pull request by algenty**
- Bugs fix
- Some optimizations
- Compress and uncompress button under xml source to optimize space in db
- editor of graph more stable
- Added mapping helper with icon link
- Added examples animated png/gif to explain mapping
- last release before all review code in 0.3

### CODE REVIEW

**Comment by briangann** [comment]
Hi @algenty this PR has more changes than just your update, can you sync with master then update the PR? (it's modifying other plugin versions)

**Comment by algenty** [comment]
Hi briangann,

How do you do ?
i hope i make no mistake, i dont master git : 

> git remote add --track master flowcharting https://github.com/grafana/grafana-plugin-repository
> git checkout flowcharting
> git fetch flowcharting
> git merge flowcharting/master
> git add repo.json
> git commit
> git push

Have a good day
Best reguards,
Arnaud

**Comment by algenty** [comment]
i pushed a little correction on text replace

**Comment by algenty** [comment]
Hi Brian,
 What is the frequency of publish ?
0.3 cooming soon and 0.2.5 is not published

**Pull request merged**
