### PR TITLE
Add Digiapulssi Organisations Panel

### PR DESCRIPTION
**Pull request by timyllym**
This panel displays all organisations that current user belongs to as navigable links (buttons).

### CODE REVIEW

**Comment by daniellee** [comment]
Great to see that you are contributing another new plugin!

Could you fix the plugin id: https://github.com/digiapulssi/grafana-organisations-panel/blob/master/dist/plugin.json#L4 to follow the [plugin id conventions](http://docs.grafana.org/plugins/developing/code-styleguide/#plugin-json-mandatory) and then update the PR with the new commit SHA. Thanks! (And remember it is the plugin.json in the dist directory that Grafana tries to read so that is the important file to update with the correct plugin id).

I think that `digiapulssi-organisations-panel` would be a suitable plugin id.

**Comment by timyllym** [comment]
Sure. I forgot to run grunt. it's now fixed.

**Comment by daniellee** [comment]
Merged and published: https://grafana.com/plugins/digiapulssi-organisations-panel

**Comment by timyllym** [comment]
Thanks! We have hidden the top bar from our users so there needs to be another way to navigate through organisations. We have custom home page that shows the organisations.

organisations-screenshot-light

**Comment by daniellee** [comment]
Nice! I'd recommend adding that screenshot to the readme.

**Pull request merged**
