### PR TITLE
Publish v1.0.0 of itrs-hub-datasource

### PR DESCRIPTION
**Pull request by rarandaitrs**

### CODE REVIEW

**Comment by marcusolsson** [comment]
Hi @rarandaitrs! Is this ready to be reviewed? I can't seem to be able to access the plugin on the URL specified in the pull request?

**Comment by rarandaitrs** [comment]
> Hi @rarandaitrs! Is this ready to be reviewed? I can't seem to be able to access the plugin on the URL specified in the pull request?

Hi @marcusolsson , the repo of the plugin is private but I can provide you access to it. Is there any other better way to provide access without making the repo public?

**Comment by marcusolsson** [comment]
If you could give me access to the repository, that would be enough. If you're not able to do so, we can also figure it out over email (you can reach me at `firstname.lastname (at) grafana.com`).

**Comment by rarandaitrs** [comment]
Sure thing, I have invited you to the repo, let me know if you can't access https://github.com/ITRS-Group/grafana-geneos-datasource/invitations

**Comment by briangann** [comment]
marcus is ooto, i'll take over review for this one, but i will need to be invited also (you can reach me at brian@grafana.com, or on slack)

**Comment by briangann** [comment]
noticed an update in the repo, can you update the md5 here also and the merge conflict?

**Comment by briangann** [comment]
@rarandaitrs the current zip file is reporting a modified signature, these files are not included in the manifest:

```LOG
grafana_1  | t=2021-07-28T17:17:25+0000 lvl=warn msg="The following files were not included in the signature" logger=plugins plugin=itrs-geneos-datasource files="[ITRS_logo_large.svg ITRS_logo_small.svg index.html]"
```

**Comment by rarandaitrs** [comment]
HI @briangann, how could I reproduce the issue? Are you using the latest version of the plugin? That log entry reflects the previous version before the renaming (i.e. the plugin id is now `itrs-hub-datasource` instead of the previous `itrs-geneos-datasource`)

**Comment by briangann** [comment]
this is from the zip file in the release `https://github.com/ITRS-Group/grafana-geneos-datasource/releases/download/v1.0.0/itrs-hub-datasource-1.0.0.zip`

**Comment by rarandaitrs** [comment]
I have just downloaded that zip file and when unzipping it and opening grafana I can load the plugin successfully
```sh
INFO[07-29|17:31:54] Profiler                                 logger=plugins.backend pluginId=itrs-hub-datasource enabled=false
INFO[07-29|17:31:54] Registering plugin                       logger=plugins id=itrs-hub-datasource
```
image

**Comment by briangann** [comment]
my mistake, i had the previous release zip file downloaded, taking a look now.

**Comment by briangann** [comment]
@rarandaitrs can you send provisioning information to brian@grafana.com, doesn't look like marcus shared that with me before he went on vacation, unless there's a local setup/doc i can use.

**Review by briangann — APPROVED** [review]
lgtm

**Pull request merged**
