### PR TITLE
Service Dependency Graph v2.3.0

### PR DESCRIPTION
**Pull request by mariomann**

### CODE REVIEW

**Comment by marcusolsson** [comment]
Hi @mariomann, and thank you for considering contributing your plugin!

Before we can start review your plugin, we'll need you to fix the issues reported by [the plugin validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/). You can enter the URL to this PR, or to a specific commit on GitHub.

**Comment by mariomann** [comment]
Hi @marcusolsson, thx for your response.

I did the changes reported by the plugin validator as mentioned.

Now, can you check the plugin again? Thx in advance.

**Comment by marcusolsson** [comment]
The `master` branch looks good! Could you please update this PR with the commit to the fixed version? I'll be able to test the plugin early next week! Looks really cool! 👍

**Comment by mariomann** [comment]
Hi @marcusolsson,
I updated the PR with the commit to the fixed version.

KR
Mario

**Comment by marcusolsson** [comment]
I tried testing the plugin, but it fails to loads for both Grafana 6.7 and 7.1.

**Grafana 6.7**

Screen Shot 2020-08-18 at 16 00 43

**Grafana 7.1**

Screen Shot 2020-08-18 at 15 59 26
 
Screen Shot 2020-08-18 at 15 58 40

What Grafana version have you used to develop the plugin?

**Comment by mariomann** [comment]
Hi @marcusolsson,
thx for the advise. Actually we found a mistake with the new ID and could solve this. I updated the changes and the commit id as well. Can you check the panel again please.

**Comment by marcusolsson** [comment]
Seems to work better now! However, I have some trouble figuring out how to create the table for the panel. I've set up the aggregationType variable and tried creating the table data as seen below, but nothing shows up. I'm probably misinterpreting the instructions. Could you please point me in the right direction?

Screen Shot 2020-08-19 at 21 23 44

**Comment by mariomann** [comment]
Hi @marcusolsson ,

I can understand that, I felt the same way when I used this plugin for the first time. Therefore we have now adapted the readme file, with an explanation that should make it easier to get started and use the panel.
Thanks for reviewing again.

**Comment by marcusolsson** [comment]
Looks good! 

Unfortunately, I had a problem while publishing the plugin. Due to the GitHub API not allowing blobs larger than 1 MB, the publish script fails on `img/service-dependency-graph-panel.gif` (3.62 MB). 

Changing this would require us rewriting the scripts to use the GitHub Data API, which is not something that's going to happen soon. For now, is there any way to reduce the size of the gif?

**Comment by mariomann** [comment]
Hi @marcusolsson,

we updated the repo again and removed the large gif. Hopefully it can publish now.

Cheers
Mario

**Comment by marcusolsson** [comment]
Thanks! 

It seems that you're still referencing the gif in your [plugin.json](https://github.com/NovatecConsulting/novatec-service-dependency-graph-panel/blob/9527da2de82492437e1f83d834140561aaaf9490/src/plugin.json#L34), which causes a 404. Could you please take a look?

**Comment by mariomann** [comment]
Now everything should be fine. Could you try again, please.

**Comment by marcusolsson** [comment]
I've [published](https://grafana.com/grafana/plugins/novatec-sdg-panel) your plugin! 🎉 

Thank you for contributing to Grafana! ❤️

**Pull request merged**
