### PR TITLE
Update flowcharting 0.6.0

### PR DESCRIPTION
**Pull request by algenty**
Hi Guys,
I think after 10 months of works and beta, the final version is not away.
For this version, big migration in typescript and grafana-toolkit.
Next version will be center to the doc.
I see many connections at this time on github, it's a success :)

### Added  
  - Experimental implementation for table type data (Mysql, Postgres, Zabbix, Streaming, loki and other ...)
  - PlaceHolder feature supported [see doc from draw.io](https://desk.draw.io/support/solutions/articles/16000051979)
  - Some optimization on : 
    - tooltips
    - States
  - Tooltip Graph :
    - Histogram ([See example](https://algenty.github.io/flowcharting-repository/images/histogram_ani.png))
  - Variables support in download input url ([See example](https://algenty.github.io/flowcharting-repository/images/url_download_variable_ani.png))
  - Add graduate animation when color changed ([See example](https://video.twimg.com/tweet_video/EISkJwdWwAAi5Qh.mp4))
  - New rule design in editor ([See example](https://algenty.github.io/flowcharting-repository/images/rule_design.png))
  - Typescript migration for best quality code.
  - Build migration to grafana-toolkit (thanks Dominik and Ryan).
  - New engine graph for best compatibility with draw.io.
  - Better Zoom for firefox and IE/edge.
  - Add checks/controls on edit mode for XML and URL.
  - Regular expression for String type values implemented to define level state.
### Fixed
  - Fix download url on first load.
  - Fix value null for string [(issue #65)](https://github.com/algenty/grafana-flowcharting/issues/65)
  - Fix bug "subways" Editor [(issue #73)](https://github.com/algenty/grafana-flowcharting/issues/73)
  - Fix date on 2 digit in tooltip [(issue #77)](https://github.com/algenty/grafana-flowcharting/issues/73)
  - Fix minors bug.

Build : 
 ```sh
$ git clone https://github.com/algenty/grafana-flowcharting
$ yarn build
$ # Make zip file plugin in archives dir
$ yarn archive
$ # for dev watching
$ yarn dev
```

## Class diagram
https://www.draw.io/?chrome=0&lightbox=1&url=https%3A%2F%2Fraw.githubusercontent.com%2Falgenty%2Fflowcharting-repository%2Fmaster%2Fgraphs%2FFlowcharting_carto.drawio

BR, 
Arnaud GENTY

### CODE REVIEW

**Comment by algenty** [comment]
Hi Brian,
I try but if have no change, the result of build is the same and Git doesn't add file
Tell me if is good now

Merry Christmas and happy new year.
Arnaud

**Comment by algenty** [comment]
It's done for you ?

**Comment by briangann** [comment]
merged and published!

**Comment by algenty** [comment]
thx a lot

**Comment by briangann** [comment]
thank you, this is very cool plugin!

**Pull request merged**
