### PR TITLE
Instana datasource plugin 3.3.0

### PR DESCRIPTION
**Pull request by schmidtl**
* fix display of error messages
* security fix

### CODE REVIEW

**Comment by daniellee** [comment]
Testing with Grafana 8.0 Beta 2 and there is a problem with the CSS on the data source configuration page:

image

I will check if we have broken something in the Checkbox control and if it should be fixed before the Grafana release on June 8th. Seems to be something to do with the height.

Otherwise everything looks fine.

**Comment by Dalje-et** [comment]
Is there anything we can do on our side to fix this?

**Comment by daniellee** [comment]
No need - fixed in Grafana instead: https://github.com/grafana/grafana/pull/35022 It was a bug we introduced when working on the Grafana themes and broke the vertical layout.

**Comment by daniellee** [comment]
@Dalje-et one tip I got from our frontend engineers is to wrap the `Checkbox` components with a `Field` component to get the right margins around each checkbox.

For example: https://github.com/grafana/grafana/blob/fix-checkbox-height/public/app/features/dashboard/components/LinksSettings/LinkSettingsEdit.tsx#L118-L141

**Review by daniellee — APPROVED** [review]
LGTM

**Comment by Dalje-et** [comment]
> @Dalje-et one tip I got from our frontend engineers is to wrap the Checkbox components with a Field component to get the right margins around each checkbox.

Thanks a lot @daniellee. Will keep this in mind when doing another update of the datasource.

**Pull request merged**
