### PR TITLE
Cloudflare Grafana App version 0.2.1

### PR DESCRIPTION
**Pull request by janik-cloudflare**
- Updated plugin to use new accounts endpoints
- Fixed legacy API keys being referred to as API tokens
- Added support for API tokens

### CODE REVIEW

**Comment by marcusolsson** [comment]
Hi @janik-cloudflare,

Could you please update the PR to the [following format](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson):

```
{
  "id": "briangann-gauge-panel",
  "type": "panel",
  "url": "https://github.com/briangann/grafana-gauge-panel",
  "versions": [
    {
      "version": "0.0.8",
      "url": "https://github.com/briangann/grafana-gauge-panel",
      "download": {
        "any": {
          "url": "https://github.com/briangann/grafana-gauge-panel/releases/download/v0.0.8/briangann-gauge-panel-0.0.8.zip",
          "md5": "782c973460f330287b7efca5486aa015"
        }
      }
    }
  ]
}
```

**Comment by janik-cloudflare** [comment]
Hi @marcusolsson, thank you for looking at this. I've updated the PR!

**Comment by marcusolsson** [comment]
Running the plugin through the [plugin validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/?url=https://github.com/cloudflare/cloudflare-grafana-app/releases/download/v0.2.0/cloudflare-grafana-app-0.2.0.zip), I'm getting a few issues:

Screen Shot 2021-01-07 at 09 08 30

Going forward, all plugins need to be _signed_. You can read more on how to sign your plugin here:

https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/

Once you've signed the plugin, make sure you [package your plugin](https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/) correctly.

Thanks!

**Comment by janik-cloudflare** [comment]
Thank you for looking at this. I've fixed the first two issues in v0.2.1 and requested access to sign the plugin. After that's done I'll run it through the validator and then post another comment here. Thanks again!

**Comment by janik-cloudflare** [comment]
Hi @marcusolsson, thanks for your patience! We've signed the plugin and it looks like v0.2.1 [passes the validation](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/?url=https://github.com/cloudflare/cloudflare-grafana-app/releases/download/v0.2.1/cloudflare-grafana-app-0.2.1.zip) now!

**Comment by Aaron-ML** [comment]
@marcusolsson  any chance this can get some eyes? I'd love to be able to automate this into my grafana deployments.

**Comment by marcusolsson** [comment]
I've moved this to Waiting for Review. You can follow the progress in the [project board](https://github.com/grafana/grafana-plugin-repository/projects/2). Thanks for your patience 🙏

**Comment by marcusolsson** [comment]
Published! 🎉

**Comment by janik-cloudflare** [comment]
Fantastic! Thank you! :smiley:

**Pull request merged**
