### PR TITLE
Add Rollbar Datasource Plugin v0.0.11

### PR DESCRIPTION
**Pull request by dovidgef**

### CODE REVIEW

**Comment by marcusolsson** [comment]
Hi @dovidgef,

I'm not familiar with Rollbar. To determine the right plugin signature level for the plugin, could you help me answer a few question?

- It looks like a commercial SaaS product, which would mean that you'd need a commercial plugin subscription to publish it. 
- Are you associated with Rollbar, or is this an unofficial plugin? 
- Is there a way to run Rollbar as an open source alternative?
- Also, what would be the best way to test the plugin?

**Comment by dovidgef** [comment]
> Hi @dovidgef,
> 
> I'm not familiar with Rollbar. To determine the right plugin signature level for the plugin, could you help me answer a few questions?
> 
> * It looks like a commercial SaaS product, which would mean that you'd need a commercial plugin subscription to publish it.
> * Are you associated with Rollbar, or is this an unofficial plugin?
> * Is there a way to run Rollbar as an open source alternative?
> * Also, what would be the best way to test the plugin?

Hi, it is a commercial service, but this is an unofficial plugin.
I have no connection to Rollbar, we use them for error tracking.

Rollbar has open source client libraries but their server is closed source.
So I dont think there is any way to run the server by yourself.

In order to test you would need to  create  a free account on their site.
Then you would need to create a test site that integrated their client.
Then you would need  to trigger some errors.

Thanks for your help

**Comment by dovidgef** [comment]
@marcusolsson would it help if I set up a test user/project for you?

**Comment by marcusolsson** [comment]
Closing due to lack of activity. If you'd like to submit it again, please use the new submission flow. For more information on how to submit using the new method, check out the [README](https://github.com/grafana/grafana-plugin-repository/blob/master/README.md).

**Pull request closed without merging**
