### PR TITLE
adding new plugin THREDDS panel

### PR DESCRIPTION
**Pull request by gresci**
This panel permits to map and query a WMS service from THREDDS DATA SERVER, no datasource is needed.
A default configuration is already provided (only mapbox api token is required), this is a first but working version

### CODE REVIEW

**Comment by marcusolsson** [comment]
Hi @gresci! Would you mind checking your plugin using [this plugin validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/) (you can enter the URL to this pull request)?

**Comment by gresci** [comment]
Hi @marcusolsson
thank you, I just fixed plugin (grafanaDependencies and absolute links) but the validator seems not to read the changes

> Hi @gresci! Would you mind checking your plugin using [this plugin validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/) (you can enter the URL to this pull request)?

**Comment by marcusolsson** [comment]
Thanks! I can see you've changed the files in the root directory, but the production build still has the old versions. Do a production build and check it the dist directory, and it should do the trick!

**Comment by gresci** [comment]
Thank you so much, I silly forgot to build it!
Now validator works, there are 2 "broken" links on README, but they will be fixed ASAP

**Comment by marcusolsson** [comment]
I've tested the plugin and I have a few comments.

- The panel currently seems to request data directly instead of reading data from a data source. This means that you're forced to set the credentials in the panel options, which are not stored securely. I recommend that you consider using a data source for retrieving the data.
- It looks like the play control in the top-left corner only shows times for today? I tried to change the time range but it didn't seem to change anything. Is this intended behavior?
- I assume that **Use Current** under **Map Options** is supposed to be a clickable button, but seems to be a label? How is it supposed to work?
- The instructions in the README don't really explain how to use the panel. Could you please add some more docs for the settings, and how to use them?
- The spectrum on the right side, draws outside the panel canvas. Either set `override: hidden`, or, even better, rescale the spectrum to the height of the panel.

Screen Shot 2020-08-12 at 10 34 53

**Comment by gresci** [comment]
Thank you @marcusolsson for your feedbacks and attention, I fixed some of the issues you suggested:

-  Added guide / options descriptions in README

- Changed "Use Current" to be displayed as a button (which it is)

- Improved color legend size on the left

The issues that I have not solved are the following:

- Client side requests: at the moment I preferred not to use a datasource but to make requests directly from the browser because THREDDS is an open source software that allows the reading of NetCDF files, used to allow access to historical and forecast open data, services are usually offered by research institutes and national agencies, and they are directly accessible to all. Mapbox in future versions will no longer be used for base maps and a public WMS service will be inserted, the token inserted at the moment is only a public key to view the background map.

- Time range issue: the plugin listens dashboard dates and tries to load the data for selected time range, but this data is not always available on THREDDS server, so it sometimes fails to load it. In the next release I will display a warning about it.

The plugin is still under development together with the THREDDS server which hosts the actual demo data (related to a marine project), I hope it can be publishable because other research institutes had also requested it for their dashboards.

> I've tested the plugin and I have a few comments.
> 
> * The panel currently seems to request data directly instead of reading data from a data source. This means that you're forced to set the credentials in the panel options, which are not stored securely. I recommend that you consider using a data source for retrieving the data.
> * It looks like the play control in the top-left corner only shows times for today? I tried to change the time range but it didn't seem to change anything. Is this intended behavior?
> * I assume that **Use Current** under **Map Options** is supposed to be a clickable button, but seems to be a label? How is it supposed to work?
> * The instructions in the README don't really explain how to use the panel. Could you please add some more docs for the settings, and how to use them?
> * The spectrum on the right side, draws outside the panel canvas. Either set `override: hidden`, or, even better, rescale the spectrum to the height of the panel.
>

**Comment by marcusolsson** [comment]
Thank you for your patience while waiting for us to review your plugin. 

We're working hard at improving the plugin experience for both users and authors. I'd like to share some important information on how to package and publish plugins going forward.

Since Grafana 7.3, we require all plugins to be _signed_. By signing your plugin, users can guarantee the integrity of the plugin and that the plugin version they've installed hasn't been modified since it was released. For more information on how to sign your plugin, refer to [Sign a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/).

With this, we now require plugins to be _packaged_ before we publish them. This means that instead of a commit containing a `dist` directory, you will need to submit a link to a ZIP archive containing your plugin. For more information on how to package your plugin, refer to [Package a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/).

Once you've packaged your plugin, you'll need to update your entry to `repo.json` to the new format. You can read more on how to do this under [Add a plugin to repo.json](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson).

To summarize, to publish your plugin, make sure that you:

1. [Sign your plugin](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/)
2. [Package your plugin](https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/)
3. Create a new GitHub release and upload the packaged plugin as a release asset
4. [Update your repo.json entry](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson)

Here's an [example](https://github.com/marcusolsson/grafana-jsonapi-datasource/releases/tag/v0.6.0) of a properly packaged plugin. In the same repository, you can find a [GitHub Action](https://github.com/marcusolsson/grafana-jsonapi-datasource/blob/master/.github/workflows/main.yml) that signs, packages, and releases the plugin whenever you create a new tag.

Once you've created a GitHub release with the packaged plugin, you can right-click the release asset, copy the link, and validate it using [the plugin validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app). 

Finally, in the November [community call](https://groups.google.com/g/grafana-developers/c/ps2vzCXRDCM/m/i7uAK1u9AQAJ), I'll be walking through the steps needed to sign and package your plugin. A recording will be made available on our [YouTube account](https://www.youtube.com/playlist?list=PLDGkOdUX1Ujo0OyE5HFffHE9GJVvaVXGs), in case you can't make it.

**Comment by marcusolsson** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
