### PR TITLE
Add Timepicker Buttons Panel plugin

### PR DESCRIPTION
**Pull request by WilliamVenner**

### CODE REVIEW

**Comment by briangann** [comment]
merge conflict is good now, will test the plugin real quick

**Comment by WilliamVenner** [comment]
@briangann All good?

**Comment by WilliamVenner** [comment]
@briangann Would you like me to do anything with this PR?

**Comment by daniellee** [comment]
@WilliamVenner sorry for the delay. You have a small mistake in your [plugin json](https://github.com/WilliamVenner/grafana-timepicker-buttons/blob/master/dist/plugin.json#L18-L19). For the screenshots, the field name should be `path` and not `url`. Here is an [example from the Zabbix plugin](https://github.com/alexanderzobnin/grafana-zabbix/blob/master/src/plugin.json#L22-L28).

**Comment by marcusolsson** [comment]
Hi @WilliamVenner! Could you please fix the issues reported by [this validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/) (enter the URL to this PR)?

**Comment by WilliamVenner** [comment]
This is becoming a mess of a PR and the validator is giving me new issues every time, I'm gonna go ahead and close this to make a new one when it's validated properly.

**Comment by marcusolsson** [comment]
Really sorry about this 😞 

The validator is the first step in improving the review experience for everyone, but it's still under development. I will keep adding more quality-focused checks in the future, but it should be relatively stable by now.

I'm looking forward to your next PR. Make sure you mention me and I'll prioritize it.

Thank you!

**Pull request closed without merging**
