### PR TITLE
Added Grafana datasource for openHistorian.

### PR DESCRIPTION
**Pull request by ritchiecarroll**
Pull request to add Grafana datasource for openHistorian.

### CODE REVIEW

**Comment by daniellee** [comment]
Hi,

Thanks for submitting this! I tested importing it to our test Grafana.net and the readme looks great. The installation as a new datasource was smooth (I liked that it suggested the correct http url!). I haven't tested against the openHistorian db but from what I could see the query editor looks simple and fine.

Just one little thing that needs to be fixed and then I can publish this. The plugin id convention is \<GitHub repo/Grafana.net username\>-\<name\>-\<type\> so the plugin id in the plugin.json needs to be changed from `grafana-openhistorian-datasource` to `gridprotectionalliance-openhistorian-datasource`.

**Comment by ritchiecarroll** [comment]
OK - I have now checked in an update for the plug-in ID...

**Comment by daniellee** [comment]
Great! It is now published on Grafana.net: https://grafana.net/plugins/gridprotectionalliance-openhistorian-datasource

If you want to publish a new version in the future then just open a new PR and I'll publish it for you.

**Comment by ritchiecarroll** [comment]
Thanks - to update mark down text published on Grafana.net I can simply change the commit SHA in the plug-in JSON and request another PR?

**Comment by DanCech** [comment]
Yes, you'll also need to bump the version number since the same content is distributed with the plugin and shown in grafana once it's installed.

**Pull request merged**
