### PR TITLE
grafana-button-panel v0.1.0

### PR DESCRIPTION
**Pull request by speakyourcode**

### CODE REVIEW

**Comment by speakyourcode** [comment]
can I just change it in the repo.json or do I have to make another release changing it also in my plugin.json?

**Comment by briangann** [comment]
it will need to be changed in your github repo also to match the published id.

**Comment by speakyourcode** [comment]
done, speakyourcode-button-panel v0.1.1

**Comment by speakyourcode** [comment]
I've added the new version of the plugin to this PR, hope that's ok

**Comment by marcusolsson** [comment]
Hi @speakyourcode, could you fix the issues reported by [this validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/)? Enter `speakyourcode/grafana-button-panel@24fee48d36fb9d33c41457c9bf6d3731aa05dba8` in the text field, and press Enter.

**Comment by speakyourcode** [comment]
Done!

**Comment by marcusolsson** [comment]
Looks like there's one failing check. You need to [sign up on Grafana.com](https://grafana.com/signup/starter/connect-account) to claim the `speakyourcode` username. Last thing, I promise!

**Comment by speakyourcode** [comment]
ok, I've logged in to Grafana.com with the github account, do I have to do anything else to claim the username?

**Comment by marcusolsson** [comment]
Yes, thank you! Your plugin has been published at https://grafana.com/grafana/plugins/speakyourcode-button-panel.

**Pull request merged**
