### PR TITLE
Instana datasource plugin 3.3.1

### PR DESCRIPTION
**Pull request by lucasInstana**
Adds a small fix to use newer Instana API payload and drop using deprecated payload.

### CODE REVIEW

**Comment by Dalje-et** [comment]
Hey Grafana team,

please do not merge this yet. We found a small bug in our datasource and want to include the fix in this version to avoid creating double work for you. Sorry for the inconvenience and thanks for your support!

**Comment by Dalje-et** [comment]
Hey there, 
I just updated the repo.json with the correct commit and its corresponding md5 sign. Please feel free to proceed with the review. 

Thanks a lot again.

**Comment by Dalje-et** [comment]
@briangann do you have any update on this? Grafana used to release our plugin within 2-3 days but this one is taking a while and we have customers waiting for it :( 

I know it's vacation season so no worries, I just wanted to push this a bit since this is a commercial plugin.

**Comment by schmidtl** [comment]
Hello, I just wanted to check the current status.
Thank you and best regards
Lars

**Comment by marcusolsson** [comment]
Published! 🎉

**Pull request merged**
