### PR TITLE
Update Service Dependency Graph Plugin

### PR DESCRIPTION
**Pull request by MariusBrill**
With this Pull Request, we would like to introduce the new Version of the [Service Dependency Graph Plugin](https://grafana.com/grafana/plugins/novatec-sdg-panel) (3.0.1) aswell as a not yet published version (3.0.0)

### CODE REVIEW

**Comment by marcusolsson** [comment]
Thank you for your patience while waiting for us to review your plugin. 

We're working hard at improving the plugin experience for both users and authors. I'd like to share some important information on how to package and publish plugins going forward.

Since Grafana 7.3, we require all plugins to be _signed_. By signing your plugin, users can guarantee the integrity of the plugin and that the plugin version they've installed hasn't been modified since it was released. For more information on how to sign your plugin, refer to [Sign a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/).

With this, we now require plugins to be _packaged_ before we publish them. This means that instead of a commit containing a `dist` directory, you will need to submit a link to a ZIP archive containing your plugin. For more information on how to package your plugin, refer to [Package a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/).

Once you've packaged your plugin, you'll need to update your entry to `repo.json` to the new format. You can read more on how to do this under [Add a plugin to repo.json](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson).

To summarize, to publish your plugin, make sure that you:

1. [Sign your plugin](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/)
2. [Package your plugin](https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/)
3. Create a new GitHub release and upload the packaged plugin as a release asset
4. [Update your repo.json entry](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson)

Here's an [example](https://github.com/marcusolsson/grafana-jsonapi-datasource/releases/tag/v0.6.0) of a properly packaged plugin. In the same repository, you can find a [GitHub Action](https://github.com/marcusolsson/grafana-jsonapi-datasource/blob/master/.github/workflows/main.yml) that signs, packages, and releases the plugin whenever you create a new tag.

Once you've created a GitHub release with the packaged plugin, you can right-click the release asset, copy the link, and validate it using [the plugin validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app). 

Finally, in the November [community call](https://groups.google.com/g/grafana-developers/c/ps2vzCXRDCM/m/i7uAK1u9AQAJ), I'll be walking through the steps needed to sign and package your plugin. A recording will be made available on our [YouTube account](https://www.youtube.com/playlist?list=PLDGkOdUX1Ujo0OyE5HFffHE9GJVvaVXGs), in case you can't make it.

**Comment by MariusBrill** [comment]
Hey @marcusolsson,

thanks for your reply! Does this also apply to older, already published versions of our plugin or do we only need to apply these changes to the latest versions?

Greetings 
Marius

**Comment by marcusolsson** [comment]
The new requirements only apply to plugin submissions going forward. Older versions will continue to be listed as unsigned, so please encourage your users to update a signed version of your plugin.

**Comment by MariusBrill** [comment]
Hi @marcusolsson ,

it's been a while. We decided to rework our panel to use react and just publish this new version 4.0.0.
Also we have added a few features:

- aggregationType is not needed as template variable anymore.
- Unit type of data now can be choosen.
- Tables of Incoming/Outgoing Statistics are now sortable.
- Settings needed for the dummy data to be displayed is now filled in automatically when dummy data is activated.
- Service Icons can now be customized for both Internal and External Services.

Greetings
Marius

**Comment by mariomann** [comment]
@marcusolsson any update for this pull request? When can we expect any feedback? The community is waiting for this version, it would be nice if Grafana sees this as well and becomes active here.

**Comment by marcusolsson** [comment]
I've started reviewing the updated plugin, but I'm running into some trouble with configuring it.

I've tried to use the mock data referenced in the README, but I don't think I'm seeing the intended outcome.

I've exported my test dashboard in a [gist](https://gist.github.com/marcusolsson/f4d64356cd7ed97f248761b69251f2ee). Could you try importing it and let me know where I've messed up? You'll first need to install the [Static data source](https://grafana.com/grafana/plugins/marcusolsson-static-datasource/) which is what we use to test panel plugins.

I tried to create a simpler dashboard, but I can't find the `aggregateType` setting as described by the README. Could you maybe help me create a minimal example with 2-3 nodes and connections maybe?

Appendix: This is what I'm seeing

Screenshot 2021-06-24 at 15 14 59@2x

**Comment by MariusBrill** [comment]
Hi @marcusolsson 

Please excuse the inconvenience! I have updated the latest release accordingly.

Greetings
Marius

**Comment by marcusolsson** [comment]
Thank you! Could you also remove the previous version from the pull request so that only v4.0.3 is included? I've reviewed the plugin and will publish as soon as you've updated the pull request.

**Comment by marcusolsson** [comment]
Nevermind. I was looking at a stale view :) Sorry for the noise. I've published the plugin 👍

**Pull request merged**
