### PR TITLE
Add xiaolinzhu-antvg6-panel plugin

### PR DESCRIPTION
**Pull request by XiaoLin1995**

### CODE REVIEW

**Comment by marcusolsson** [comment]
Could you please address the error reported by the [plugin validator](https://plugin-validator.grafana.net/?url=https://github.com/XiaoLin1995/antv-g6-panel/releases/download/1.0.0/xiaolin-antv-g6-panel-1.0.0.zip) and update your pull request?

**Comment by XiaoLin1995** [comment]
Hi, I have adressed the error reported, except for unsigned plugin errors.

**Comment by marcusolsson** [comment]
Hi @XiaoLin1995! I tried out your plugin and it seems to be working as expected. A few things though:

- I tried to configure the signature level for the plugin, but it seems like there's no Grafana Cloud account called `xiaolinzhu`. To claim ownership of the plugin (and to sign the plugin) you need to sign up for a (free) Grafana Cloud account.
- I can't find the license for the G6 logo. I tried to find it in the repository itself, but no luck. I assume that it's licensed under MIT as well, but could you point me to a license that shows it's ok to use for this plugin as well?

**Comment by marcusolsson** [comment]
Closing due to lack of activity. If you'd like to submit it again, please use the new submission flow. For more information on how to submit using the new method, check out the [README](https://github.com/grafana/grafana-plugin-repository/blob/master/README.md).

**Pull request closed without merging**
