### PR TITLE
add pnp4nagios datasource

### PR DESCRIPTION
**Pull request by sni**
This datasource connects to the pnp4nagios api and fetches rrd data from
nagios/naemon/icinga installations.

### CODE REVIEW

**Comment by daniellee** [comment]
Thanks for submitting this, I'll get back to you with feedback soon.

**Comment by daniellee** [comment]
This looks good, the data source page and the graph panel work well. It just needs one tweak to the meta data.

### Plugin.json

[The plugin id](http://docs.grafana.org/plugins/developing/code-styleguide/) convention:

> The convention for the plugin id is [github username/org]-[plugin name]-[datasource|app|panel] and it has to be unique.

Can you change the plugin id to:

`sni-pnp-datasource`

### Documentation

- I found a docker container for pnp4nagios and the instructions for connecting were fine but a bit more information about where to place the controller would have been helpful!

- The internal dashboard seems to work, maybe you should mention in the docs?

Great work! If you can fix the plugin id then I can publish it straight away.

**Comment by sni** [comment]
Thanks for the review. I update the documentation and change the id. I replaced the PR with a rebased new commit.

**Comment by daniellee** [comment]
Published: https://grafana.net/plugins/sni-pnp-datasource

Thank you for submitting this! Just out of curiosity, how popular is pnp4nagios? Are you expecting a lot of people to use this plugin?

**Comment by sni** [comment]
Great. Thanks. Thats hard to tell. I now have to convince Jörg of doing a new pnp release including the api which makes the installation of this datasource easier. The userbase of pnp is quite huge, so i think there is lot potential.
I just update the readme once more. I guess new releases should be updated by a new pull request, right?

**Comment by daniellee** [comment]
Yes, exactly. Just increment the version number in your plugin.json (Grafana reads the plugin.json in the dist folder) and then in the repo.json add the new version number and commit SHA to the repo.json and I will publish the new version.

**Pull request merged**
