### PR TITLE
add ammp plugin

### PR DESCRIPTION
**Pull request by peregrinius**

### CODE REVIEW

**Comment by DracoBlue** [comment]
@peregrinius please change the id of the plugin. it needs to be `yourorganizationname-ammp` and not `grafana-example-app`.

**Comment by peregrinius** [comment]
@DracoBlue thanks - I've updated the id. Is it ok to use ammp-app otherwise it will be ammp-ammp as both the organisation and the app are called ammp. Thanks.

**Comment by daniellee** [comment]
Hi,

`ammp-app` works fine. 

- Is ammpio an open source project or a commercial project? 
- How would I get started with setting up ammpio to test this plugin?

Thanks!

**Comment by peregrinius** [comment]
@daniellee sorry for taking my time to get back to you.

ammpio is currently closed source but will be released open source in the not too distant future. This plugin is to manage mini/off-grid assets which we will then use Grafana to produce dashboards for monitoring assets.

The process for setting up a new customer is quite manual at the moment. But we are working on a custom registration page.

Thanks.

**Comment by marcusolsson** [comment]
Closing this as it seems like there hasn't been any activity on this submission in a while.

If you'd like to submit the plugin again, I'd like to invite you to use our new submission flow inside Grafana Cloud. For more information and instructions, check out the [README](https://github.com/grafana/grafana-plugin-repository).

**Pull request closed without merging**
