### PR TITLE
Instana datasource plugin

### PR DESCRIPTION
**Pull request by JeroenSoeters**
Adding a datasource plugin that connects to an Instana backend for custom dashboards.

### CODE REVIEW

**Comment by briangann** [comment]
Here's a quick review of the datasource:

1) Is there an API key that can be used with the mock backend?  The docker-compose stands up another instance on port 8010 and 2525, but I don't see an API key that can be used with it.

2) In module.ts, there are two typos which may cause issues (has **InstnaDatasource** instead of **InstanaDatasource**).  The generated files from typescript to dist show no references to the correct name.
```
1: import InstnaDatasource from './datasource';
9: export {
10:  InstnaDatasource as Datasource,
```
3) Enabling tslint gives 1907 errors (mostly codestyle, with some == vs ===, and else blocks). 
Here's a patch you can use to enable it in package.json and Gruntfile.js:
```
diff --git a/Gruntfile.js b/Gruntfile.js
index e908230..4784c23 100644
--- a/Gruntfile.js
+++ b/Gruntfile.js
@@ -13,6 +13,7 @@ module.exports = function(grunt) {
   require('load-grunt-tasks')(grunt);

   grunt.loadNpmTasks('grunt-contrib-clean');
+  grunt.loadNpmTasks('grunt-tslint');
   grunt.loadNpmTasks('grunt-typescript');
   grunt.loadNpmTasks('grunt-contrib-watch');
   grunt.loadNpmTasks('grunt-karma');
@@ -57,6 +58,17 @@ module.exports = function(grunt) {
       }
     },

+    tslint: {
+      options: {
+        // Task-specific options go here.
+        configuration: "tslint.json"
+      },
+      files: {
+          // Target-specific file lists and/or options go here.
+          src: ['src/**/*.ts'],
+      },
+    },
+
     typescript: {
       build: {
         src: ['dist/**/*.ts', '!**/*.d.ts'],
@@ -130,6 +142,7 @@ module.exports = function(grunt) {
     'clean',
     'unit',
     'copy:dist_js',
+    'tslint',
     'typescript:build',
     'copy:dist_html',
     'copy:dist_css',
diff --git a/package.json b/package.json
index 456de56..f08b4ca 100644
--- a/package.json
+++ b/package.json
@@ -38,6 +38,7 @@
     "grunt-contrib-watch": "^1.0.0",
     "grunt-env": "^0.4.4",
     "grunt-run": "^0.8.0",
+    "grunt-tslint": "^5.0.1",
     "grunt-typescript": "^0.8.0",
     "karma": "^1.7.0",
     "karma-chrome-launcher": "^2.2.0",
@@ -48,6 +49,9 @@
     "karma-systemjs": "^0.16.0",
     "plugin-typescript": "^7.1.0",
     "sinon": "^3.2.1",
-    "systemjs-plugin-css": "^0.1.35"
+    "systemjs-plugin-css": "^0.1.35",
+    "tslint": "^5.9.1",
+    "typescript": "^2.7.2",
+    "typescript-formatter": "^7.1.0"
   }
 }
```
and a modification in the tslint.json:

```
diff --git a/tslint.json b/tslint.json
index 15e36cf..9d0c5d7 100644
--- a/tslint.json
+++ b/tslint.json
@@ -7,7 +7,6 @@
     "forin": false,
     "indent": [true, "spaces"],
     "label-position": true,
-    "label-undefined": true,
     "max-line-length": [true, 140],
     "member-access": false,
     "no-arg": true,
@@ -21,7 +20,6 @@
     ],
     "no-construct": true,
     "no-debugger": true,
-    "no-duplicate-key": true,
     "no-duplicate-variable": true,
     "no-empty": false,
     "no-eval": true,
@@ -32,8 +30,6 @@
     "no-trailing-whitespace": true,
     "no-unused-expression": false,
     "no-unused-variable": false,
-    "no-unreachable": true,
-    "no-use-before-declare": true,
     "no-var-keyword": false,
     "object-literal-sort-keys": false,
     "one-line": [true,
```

**Comment by JeroenSoeters** [comment]
Thanks for the feedback.

1. Sorry I should have documented this better. There is a file local.env with 2 environment variables that you should source, otherwise the functional (puppeteer) test will fail as well when running the startup task. This contains the url as well as API key for the mock server. Actually the functional tests already creates a working datasource for you. I use mountebank as a mockserver and in the /specs/mb/imposters/imposters.ejs file you see the mock that is set up (alternatively you can open localhost:2525 after starting the container as well). Right now it is set up that when you set the date range from 2018-01-01 00:00:00 to 2018-01-07 00:00:00 and you enter "filler" in the query field, select "process" from the entity type dropdown and virtual memory usage from the metric dropdown you get actual time series data back from the mock server.

2. Fixed

3. Added the linter to the Gruntfile and fixed all the errors.

**Comment by briangann** [comment]
I'm not seeing the data from the mock server, I do get back this for the "types" query:

image

snapshots, get back 200 OK, but no data:
image

context: get back 200 OK, but no data:
image


image

**Comment by briangann** [comment]
also, running "yarn run startup" I get a failure:
```
Running "run:waitForMountebank" (run) task
wait-for-it.sh: waiting 15 seconds for localhost:8010
wait-for-it.sh: localhost:8010 is available after 0 seconds

Running "run:waitForGrafana" (run) task
wait-for-it.sh: waiting 15 seconds for localhost:3000
wait-for-it.sh: localhost:3000 is available after 0 seconds

Running "run:functionalTests" (run) task
/Users/bgann/Documents/repos/instana-grafana-datasource/specs/add_datasource_specs.js:8
  it('should successfully connect to the Instana API', async () => {
                                                             ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at /Users/bgann/Documents/repos/instana-grafana-datasource/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/bgann/Documents/repos/instana-grafana-datasource/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/Users/bgann/Documents/repos/instana-grafana-datasource/node_modules/mocha/lib/mocha.js:536:10)
    at Object.<anonymous> (/Users/bgann/Documents/repos/instana-grafana-datasource/node_modules/mocha/bin/_mocha:573:18)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)
    at bootstrap_node.js:500:3
Warning: non-zero exit code 1 Use --force to continue.

Aborted due to warnings.
error An unexpected error occurred: "Command failed.

```

**Comment by JeroenSoeters** [comment]
Regarding the data not coming back: I think you might be trying this from a different timezone. The timestamps in your request for the snapshots and the context don't match the ones set up in the mock (http://localhost:8010/api/snapshots?from=1514782800000&to=1515301200000&q=filler%20AND%20entity.pluginId%3Aprocess, http://localhost:8010/api/snapshots/context?q=filler%20AND%20entity.pluginId%3Aprocess&time=1515301200000). 

Regarding the error in the functional test, which version of NodeJS are you running and are you OK upgrading? It looks like the async syntax is not recognized. This is only supported in Node 7.6.0 or later but it's the idiomatic way of writing puppeteer tests (https://github.com/GoogleChrome/puppeteer).

I added mocha to the dev dependencies and the grunt-mocha-cli plugin.

**Comment by briangann** [comment]
I've upgraded node 9.6, it doesn't fail on the async but it does fail with this (and doesn't create the datasource this time):
```
Running "run:waitForMountebank" (run) task
wait-for-it.sh: waiting 15 seconds for localhost:8010
wait-for-it.sh: localhost:8010 is available after 0 seconds

Running "run:waitForGrafana" (run) task
wait-for-it.sh: waiting 15 seconds for localhost:3000
wait-for-it.sh: localhost:3000 is available after 0 seconds

Running "run:functionalTests" (run) task


  When adding the Instana datasource to Grafana
    1) should successfully connect to the Instana API


  0 passing (5s)
  1 failing

  1) When adding the Instana datasource to Grafana
       should successfully connect to the Instana API:
     TypeError: text is not iterable
      at Keyboard.type (node_modules/puppeteer/lib/Input.js:168:24)
      at ElementHandle.type (node_modules/puppeteer/lib/ElementHandle.js:108:31)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:118:7)
```

Can you give me a query/uri that would return data, I tried changing to UTC with the same result (or what timezone should it be in?)

```
http://localhost:8010/api/snapshots?from=1514764800000&to=1515283200000&q=filler%20AND%20entity.pluginId%3Aprocess
```

```
http://localhost:8010/api/snapshots/context?q=filler%20AND%20entity.pluginId%3Aprocess&time=1515283200000
```

**Comment by JeroenSoeters** [comment]
Honestly that error could be a flaky test as it's a browser based test. I am on ET. These are the timestamps copied from the url: &from=1514782800000&to=1515301200000

**Comment by briangann** [comment]
That helped, I'm seeing data now. Will merge the plugin now.

image

**Comment by mattttt** [comment]
@JeroenSoeters One last tweak, the ID in the plugin.json needs to be:

`  "id": "instana-instana-datasource",`

**Comment by mattttt** [comment]
@JeroenSoeters Wait a tick, my mistake. Adjusting this commit to the repo to match the plugin.

**Comment by JeroenSoeters** [comment]
So we are good to go now @mattttt ?

**Pull request merged**
