### PR TITLE
adds diagram 1.7.2

### PR DESCRIPTION
**Pull request by jdbranham**

### CODE REVIEW

**Comment by jdbranham** [comment]
I'm guessing I need to update the build process to copy some files, but not sure where.  
I'll have to get back to this.

**Comment by marcusolsson** [comment]
Could you please update your PR to the [following format](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson):

```
{
  "id": "briangann-gauge-panel",
  "type": "panel",
  "url": "https://github.com/briangann/grafana-gauge-panel",
  "versions": [
    {
      "version": "0.0.8",
      "url": "https://github.com/briangann/grafana-gauge-panel",
      "download": {
        "any": {
          "url": "https://github.com/briangann/grafana-gauge-panel/releases/download/v0.0.8/briangann-gauge-panel-0.0.8.zip",
          "md5": "782c973460f330287b7efca5486aa015"
        }
      }
    }
  ]
}
```

Once you've updated your PR, make sure you paste the URL to the ZIP archive into the [plugin validator](https://plugin-validator.grafana.net/) to make sure it's ready for review.

**Comment by jdbranham** [comment]
That was easy - thanks @marcusolsson !!

**Comment by marcusolsson** [comment]
Published! 🎉

**Pull request merged**
