### PR TITLE
bmchelix ade datasource v21.02

### PR DESCRIPTION
**Pull request by abhijeet-teli**
BMC Helix Datasource v21.02

### CODE REVIEW

**Comment by marcusolsson** [comment]
Hi @abhijeet-teli,

I'm getting an error whenever I query the data source:

Screenshot 2021-03-29 at 09 59 30@2x

My credentials seem to work. Is there anything need to be enabled for the test account? 

A few minor feedback items:

- The image in the README seems to be broken: 
  - Doesn't work: https://raw.githubusercontent.com/bmcsoftware/bmchelix-datasource/master/screenshots/v3.1.0/configuration.png
  - Works: https://raw.githubusercontent.com/bmcsoftware/bmchelix-datasource/main/screenshots/configuration.png
- Missing `grafanaDependency`
  - The README says the plugin supports 7.0.0+, but the `grafanaVersion` says 7.3.1. Depending on which one, the `grafanaDependency` should say `>=7.0.0`, or `>=7.3.1`.

**Comment by briangann** [comment]
@abhijeet-teli can you fix the merge conflict also?

**Comment by briangann** [comment]
looks like the MD5 needs to be updated: 

```
md5sum bmchelix-ade-datasource-v1.0.0.zip: 8575e8d53de5ec3af44e7f68c2a9f8c4
```

**Review by briangann — APPROVED** [review]
lgtm

**Pull request merged**
