### PR TITLE
Instana datasource plugin 2.0.0

### PR DESCRIPTION
**Pull request by schmidtl**
* Receive all available metrics from API
* Add proxy mode support

### CODE REVIEW

**Comment by daniellee** [comment]
@schmidtl The query editor is not working for me anymore after this change.

I am using the docker-compose with mountebank. When I query using `filler` then I see that network request is being made that returns a list of items but the dropdown is empty:

image

image

Is there a bug with promises and the entity type cache or am I doing something wrong?

**Comment by schmidtl** [comment]
Hey Daniel, 
thanks for your response. 
It seems the last change is not properly reflected on the mountebank server.
I will adjust this and update the request. Sorry for this inconvenience.
/Lars

**Comment by schmidtl** [comment]
Hi Daniel, 
the mountebank should now be able to provide the available plugins.
/Lars

**Comment by daniellee** [comment]
Thank you! Merged and published.

**Pull request merged**
