### PR TITLE
add netsage-sankey-panel for review

### PR DESCRIPTION
**Pull request by KatrinaTurner**
Plugin is currently only signed privately.
I still need to add a few screenshots to the README, but wanted to get the review process started.
Thank you!

### CODE REVIEW

**Comment by briangann** [comment]
Can you run the zip file through the validator? I'm seeing some minor documentation issues from it.

https://plugin-validator.grafana.net/

**Comment by briangann** [comment]
I've added a stub for signing to your org, if you add a GRAFANA_API_KEY to your git workflow it will sign correctly.

**Comment by KatrinaTurner** [comment]
I'm not sure why it's saying the links are broken, I copy/pasted them directly from github's status badge generator and they show up fine on my README.
I am working on a getting a couple screenshots together to add to the readme still as well.  I will sign with the new API_KEY once I've finished updating it.  Thank you so much!

**Comment by KatrinaTurner** [comment]
Ah, ok I see the problem. So for some reason, the package it's creating for the zip file does not match my current source code.  It's building an old version from last week.  Trying to figure out what's going on now.

**Comment by KatrinaTurner** [comment]
Everything should be fixed now! :)

**Comment by zuchka** [comment]
Hi @KatrinaTurner 

Just a quick note to say that we've started reviewing this. I apologize for the delay. I'll loop back early next week 👍

**Comment by KatrinaTurner** [comment]
Awesome thanks! :)

**Comment by KatrinaTurner** [comment]
Hi @zuchka!
Just checking on the status of the sankey review?
I have a couple more features I want to add in before official release and not sure the best way to go about that.
Thanks!

**Comment by zuchka** [comment]
@KatrinaTurner I apologize for the delay, especially after telling you that I would turn this around quickly. We've had a few team-related issues that caused a bottleneck, but the delay is still on me.

Do you want to push the new changes? I will sync with my teammate this week and get you a response.

PS: I have installed your plugin and played with it. It's fantastic. Really beautiful.

I did notice two small issues: one with switching between dark and light modes, and another with using value-mappings. Do you think you could check on those two area before resubmitting?

Again, I apologize. It shouldn't take this long in the future--I promise!

**Comment by KatrinaTurner** [comment]
@zuchka No worries!  We're not in a rush, just wanted to check in.
Thank you! :)
Sounds good, I will push my changes tomorrow and check on those issues.  Right now I am not making use of Grafana themes, which is probably why switching between light and dark has an issue, but that's actually one of the features I wanted to add.  I will try to get that done and I'll check on the value-mappings as well, hopefully by the end of the week.

**Comment by KatrinaTurner** [comment]
Hi @zuchka ! I fixed the text to always just use the grafana default so it will switch more nicely between light and dark modes.  I also fixed the tooltips for using value mappings.  The value mappings purposely shouldn't affect the color of the sankey though because the thickness of the lines correlates to value and the color is to follow a path from the source node.

For some reason the circle CI check is failing saying I haven't updated to a higher version, but I was formerly on 1.0.1 and am now on 1.0.4, so I'm not sure why that's happening.  Maybe it needs a larger version change?  If so, I can re-release as 1.2.0 I suppose, just let me know. 
Thanks!!!

**Comment by KatrinaTurner** [comment]
Hi @zuchka sorry for the late response, but I think everything should be okay now?  I ran it through the plugin validator on my end and no warnings popped up.
I also added a little more detail to the README so hopefully it is clearer.
Thanks!

**Comment by marcusolsson** [comment]
Hi @KatrinaTurner,

Could you submit this using the new submission process from your Grafana Cloud account? More information is available in the README for this repository.

**Pull request closed without merging**
