### PR TITLE
Add kapacitor-grafana-datasource in repo.json

### PR DESCRIPTION
**Pull request by MananArya22**
Added kapacitor-grafana-datasource in repo.js

### CODE REVIEW

**Comment by alexanderzobnin** [comment]
@MananArya22 Thanks for the contribution! Looks like your plugin ID doesn't meet [Styleguide](https://grafana.com/docs/plugins/developing/code-styleguide/#plugin-json-mandatory). Could you fix it? Proper ID should look like `paytm-kapacitor-datasource`.

**Comment by MananArya22** [comment]
@alexanderzobnin Thanks for commenting. I have changed the plugin ID according to the styleguide.

**Comment by alexanderzobnin** [comment]
@MananArya22 you should change plugin ID in the `plugin.json` as well.

**Comment by MananArya22** [comment]
@alexanderzobnin thanks! I have updated the id in plugin.json and the commit id in this repo.

**Comment by alexanderzobnin** [comment]
@MananArya22 I've merged your PR, but in order to publish it at grafana.com you should create your account with `paytm` login.

**Comment by MananArya22** [comment]
Hi @alexanderzobnin  thank you for merging the PR. Should I create a github account with paytm login or the account at grafana.com ?

**Comment by alexanderzobnin** [comment]
@MananArya22 at grafana.com.

**Comment by MananArya22** [comment]
@alexanderzobnin Even after login using my paytm account i cannot see any way to publish my plugin or add it in the plugins list of grafana.com . Can you please guide or share the steps to be followed now to publish my plugin at Grafana's List? Thank you so much for your support.

**Comment by alexanderzobnin** [comment]
@MananArya22 What's a slug of your `paytm` account? You can see it at the end of url at the _My Grafana_ page: `https://grafana.com/orgs/<slug>`

Screenshot from 2019-07-30 12-25-40

**Comment by MananArya22** [comment]
@alexanderzobnin hi the URL is https://grafana.com/orgs/paytm and the slug name is "paytm"

**Comment by alexanderzobnin** [comment]
@MananArya22 looks strange, I get 404 on your URL.

**Comment by MananArya22** [comment]
@alexanderzobnin if I am logged out from my account and hit URL "https://grafana.com/orgs/paytm" then it gives me 404 but when I am logged in it opens my account page. 
Screenshot from 2019-07-30 21-53-30

**Comment by MananArya22** [comment]
Hi @alexanderzobnin I examined my repo and caught the bug. The private flag under package.json was set to true due to which it was not published. I have removed this flag and created a PR for the same: https://github.com/grafana/grafana-plugin-repository/pull/458 . I hope after merging this PR it will be listed publically.  Thanks for the continuous help. I hope the above PR will solve the issue.

**Comment by alexanderzobnin** [comment]
@MananArya22 hm... Interesting. I'll take a look. What `package.json` do you mean? One that is in plugin repo?

**Comment by alexanderzobnin** [comment]
@MananArya22 Finally, I get it published. Not sure what was a problem, I'll try to investigate. I'm closing #458, it's not necessary.

**Comment by MananArya22** [comment]
@alexanderzobnin Thank you so much for the help!

**Pull request merged**
