### PR TITLE
+ add f5-bdos-app  f5-bdos-evergreen-app plugins

### PR DESCRIPTION
**Pull request by akruman**

### CODE REVIEW

**Comment by daniellee** [comment]
Hi @akruman 

Is this plugin for a commercial, closed-source application(s)? It seems the main component is the datasource for F5 Network's BIG-IP?

From the PR template:
> Commercial plugins require a plugin subscription to be published. Commercial plugin subscriptions help us fund continued development of our open source platform and software. See the [terms](https://grafana.com/terms) for more details.

/Daniel

**Comment by akruman** [comment]
Yes, it's for F5 Network's BIG-IP

**Comment by daniellee** [comment]
Thanks - I will ask our Sales team to contact you.

**Comment by daniellee** [comment]
@akruman as this is a plugin for a commercial plugin, you need to purchase a plugin subscription to be published. See terms here: https://grafana.com/terms/

Closing this PR as it has been open for a long time and you haven't purchased a subscription but let me know if I should you put you in contact with anyone from our commercial team.

**Pull request closed without merging**
