### PR TITLE
OpenNMS Helm 2.0.0

### PR DESCRIPTION
**Pull request by j-white**
Updating the OpenNMS Helm plugin to v2.0.0.

This update includes minor bug fixes and a new datasource for querying flow datasource from OpenNMS.

### CODE REVIEW

**Comment by daniellee** [comment]
Is the opennms demo site down?

https://demo.opennms.org is not working for me anymore.

**Comment by daniellee** [comment]
I looked through the changes and tested without access to a datasource and it looks fine. Though the error message for the new Flow datasource when testing and saving is not as good as the other two.

Performance DS:

image

Flow DS:

image

To test properly, should I setup an OpenNMS environment with docker or will you be able to get the Demo site working again?

**Comment by j-white** [comment]
@daniellee the demo site should be back online now.

Note that the demo server doesn't have any flow data currently, so you won't be able to get much out of the Flow DS.

**Comment by daniellee** [comment]
Merged and published.

**Comment by j-white** [comment]
Thanks @daniellee!

**Pull request merged**
