### PR TITLE
Add btplc-xxxx-panel plugins

### PR DESCRIPTION
**Pull request by benthorner**

### CODE REVIEW

**Comment by daniellee** [comment]
Hi Ben,

Each repo has broken link to an image in the plugin.json. As there are two copies of the plugin.json, paths to images can be tricky. I would recommend doing it like [worldPing](https://github.com/raintank/worldping-app/tree/master/src) and have the plugin.json in the src (and dist) directory rather than in the root. This way you can have relative links like: `img/peak_report.png`

The following links are incorrect for the plugin.json in the dist directories:

https://raw.githubusercontent.com/BTplc/grafana-peak-report/3f7abb69c712201b8e2866aeddf43334df8335a6/dist/src/img/peak_report.png

https://raw.githubusercontent.com/BTplc/grafana-alarm-box/108dff1051ad1e82dd7f1f5ec0bd360742b4d405/dist/src/img/alarm_box.png

https://raw.githubusercontent.com/BTplc/grafana-trend-dot/87ec15cca2fdb188544db50f3bf522037bed45d6/dist/src/img/trend_dot.png

https://raw.githubusercontent.com/BTplc/grafana-trend-box/6e00a505db0fbd422cab1747e442616cdf2575b8/dist/src/img/trend_box.png:

**Comment by benthorner** [comment]
Hi Dan. Thanks for spotting that - fixed now in all 4 repos. I'd already done what you suggested for the logo image, but forgot to do the same for the screenshots. Could you take another look?

**Comment by daniellee** [comment]
Hi Ben,

Everything looks mostly fine now but I found a couple of small things to fix :-)

#### All plugins

- Link to Project site goes to the grafana-plugins repo

- Link to the license goes to the grafana-plugins repo

#### Trend Box

- Is it by design that the color doesn't change once a threshold is hit? For example, if the threshold is 10% and the percentage change first goes over 10% then the background color changes. If it then drops below 10% again, the color does not change back to the original color. If you refresh the page however, the color is reset.

**Comment by benthorner** [comment]
Hi Dan. Thanks again for spotting some more issues: links are fixed and trend-box now behaves as expected. Turns out there was a typo in the code and we'd never run into it on live.

I've also added a color picker to modify the default color for the 3 relevant plugins, as it's otherwise a bit awkward to define a color for all possible (negative) values. Fingers crossed this time ;-)

**Comment by daniellee** [comment]
Hi Ben,

Finally made some time now that Grafanacon is over. It's been hectic the last week or so. The plugins look great and are all published now:

- https://grafana.net/plugins/btplc-trend-box-panel

- https://grafana.net/plugins/btplc-trend-dot-pane

- https://grafana.net/plugins/btplc-alarm-box-panel

- https://grafana.net/plugins/btplc-peak-report-panel

**Comment by benthorner** [comment]
Hi Dan,


   Thanks - that's great. It was very satisfying to install them using the CLI [😉]


Yours, Ben

________________________________

**Pull request merged**
