### PR TITLE
Add chaos mesh datasource

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: Ben Ye <yb532204897@gmail.com>

### CODE REVIEW

**Comment by yeya24** [comment]
PTAL @marcusolsson  @daniellee

**Comment by zhouqiang-cl** [comment]
[Chaos Mesh](https://github.com/chaos-mesh/chaos-mesh) is a chaos engineering platform for Kubernetes. Grafana is the best way for us to observe the chaos and its effort. We want to use grafana to visualization Chaos event and action.
example

Could you please take a look at this PR @marcusolsson  @daniellee  thank you very much

In last week, Chaos Mesh join CNCF sandbox. Grafana help us a lot in product

**Comment by yeya24** [comment]
@marcusolsson Can you PTAL this when you get a chance?

**Comment by zhouqiang-cl** [comment]
@marcusolsson Could you please take a look again, thank you very much

**Comment by marcusolsson** [comment]
[Published](https://grafana.com/grafana/plugins/yeya24-chaosmesh-datasource)!

Thank you! ❤️

**Pull request merged**
