### PR TITLE
Add Humio-datasource plugin 

### PR DESCRIPTION
**Pull request by AlexanderBrandborg**
Initial version of Humio datasource plugin.

Instructions for test:
1. Create a free account on https://cloud.humio.com/
2. Under profile go to `your account`
3. Copy API token
4. Create Humio Datasource in Grafana by using https://cloud.humio.com/ as the url and by pasting the API token you just copied.

This should create a datasource with 3 repos, where humio-metrics and humio-audit have data. 
General instructions for use can be found in the docs: https://docs.humio.com/integrations/send-humio-data/grafana/
You'll need to use some Humio queries to fetch some data for the panels. The docs for the query language can be found here: https://docs.humio.com/query-functions/

### CODE REVIEW

**Comment by marcusolsson** [comment]
Thank you! I will get started on reviewing this. In the meantime, could you have a look at the issues reported by [the plugin validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/?url=https://github.com/humio/humio2grafana/releases/download/v3.1.1/humio.zip) (just enter the URL to the ZIP file and press Enter).

**Comment by marcusolsson** [comment]
Looks like it works as intended! I think I happened to stumble upon a bug though. Probably because of an invalid query.

Screen Shot 2020-11-18 at 15 40 52

Nothing stopping from publishing it though, unless you want to fix it first.

One minor comment that I'd appreciate if you updated is that the directory in the packaged plugin archive should have the same name as the plugin ID. Would you mind renaming the directory and uploading the new archive?

**Comment by AlexanderBrandborg** [comment]
Thank you, I'll have a look at fixing up these issues in the following days.

**Comment by AlexanderBrandborg** [comment]
@marcusolsson 
I've done a few bug fixes and updated the directory name, which have been rolled a new version (3.2.0). So everything should be in order and you have the go-ahead from my side. :- )

**Comment by marcusolsson** [comment]
[Published](https://grafana.com/grafana/plugins/humio-datasource)! 🎉

**Pull request merged**
