### PR TITLE
Added ACE.SVG

### PR DESCRIPTION
**Pull request by acedrew**
This plugin provides a simplified SVG renderer using react and the latest Grafana Data APIs. 
You can read more about what the goals of this plugin are in the project README.

### CODE REVIEW

**Comment by marcusolsson** [comment]
Hi @acedrew, and thank you for considering contributing your plugin! 🎉 

Before we can start reviewing your plugin, we need you to fix the errors reported by the plugin validator. You can check them out here:

[Validate your plugin](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/?url=https://github.com/ACE-IoT-Solutions/ace-svg-react/tree/19de692f84b0b2b44e0881d75ba602756eb46d96)

**Comment by acedrew** [comment]
Great! I saw references to the validator, but wasn't clear how to get to
it. Thank you! I'll get these cleared up quickly.
I was using the CircleCI and had everything good there.

**Comment by marcusolsson** [comment]
I'll try to get around and give it a more... memorable URL. But in the meantime you can find the link in the README for this repository :)

I definitely want to add the validator to CircleCI as well. If you want to run it from your own CI for now, you can find it at https://github.com/grafana/plugin-validator.

We're currently working on improving the review process. Hopefully, it'll get smoother over the coming weeks!

**Comment by acedrew** [comment]
image

Tada! Great tool, thanks for making that easy!

**Comment by marcusolsson** [comment]
Nice! 🎉 

I tried out the plugin. I love the idea of creating dynamic SVGs based on data from data sources. I have a few comments:

- The Monaco editor provides a nice experience. However, it doesn't resize along with the options editor. It seems to keep the width the options editor had when you entered edit mode.
- I think line numbers and the code overview to the right take up unnecessary screen space. This in combination with the previous comment makes it difficult to edit the code.

Screen Shot 2020-08-19 at 20 43 25

- I felt the default example you get when you create the panel is a bit too complicated at the moment. I'd love to see a simpler example that I could easily wrap my head around and start modifying to see the impact of my changes.
- I also recommend that you provide a description for each of the options to help the user understand each option.

I don't mind if you want to work on improving the experience for new users in a later release, but I'd very much like it if you could take a look at the comments regarding the editor as it makes editing a bit cumbersome.

**Comment by acedrew** [comment]
Great feedback! I work on a 4k display all the time with really small fonts and I forget sometimes that not everyone has such a spacious view. I'll work on both of those, I'm eager to get it published and available for broader feedback. 
I think there may be better ways to access the data than I'm using in the example right now as well, I basically just did some poking in the console to find those interfaces. I think adding a link to the DataFrame documentation in the plugin would be helpful as well.

**Comment by ryantxu** [comment]
Also note that you can use the builtin monoco editor now:
https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/text/TextPanelEditor.tsx#L35

however... (and this is a big BUT!) it does not yet include language bindings for xml/js

**Comment by acedrew** [comment]
@ryantxu I look forward to when it has support for the XML bindings/ a future release.
@marcusolsson I will work on a simpler example. I'm pretty enamored with the idea of animating the logo itself though perhaps I could set that animation up in the init function and then do some simpler additional elements in the render code.

**Comment by acedrew** [comment]
Thoughts on latest examples @marcusolsson? I think that there is a bug in grafana that is effecting the panel editing usability negatively, but it is still usable. I'd like to make sure everything within my control is handled and start getting broader feedback.

Andrew

**Comment by marcusolsson** [comment]
Sounds good!

Just a couple of things left:

- Could you remove the leading slashes, `/`, for the images? I'm getting 404s because of this when publishing.
  https://github.com/ACE-IoT-Solutions/ace-svg-react/blob/main/src/plugin.json#L17-L18
- Could you update the repo.json to only contain one release?

**Comment by acedrew** [comment]
@MarcusCalidus 👍

**Comment by acedrew** [comment]
@marcusolsson 👍

**Comment by marcusolsson** [comment]
Sorry to bother you with a couple of (hopefully) final fixes 🙏 

- The version in this PR (0.0.8) doesn't match the actual plugin version (0.0.6).
- The branch has conflicts that need to be resolved before merging.

**Comment by marcusolsson** [comment]
[Published](https://grafana.com/grafana/plugins/aceiot-svg-panel)!

Thank you for contributing to Grafana! ❤️

**Pull request merged**
