### PR TITLE
akamai-edgedns-datasource v1.0.0

### PR DESCRIPTION
**Pull request by svernick**
You will need "OPEN API credentials" to use this plugin.  I can provide those to you.  I can also provide instructions regarding how to test.

Please email me at svernick@akamai.com.

Thank you!

### CODE REVIEW

**Comment by marcusolsson** [comment]
Hi @svernick,

It seems to me that this is a plugin for a commercial offering from Akamai. Plugins for commercial products require a paid subscription to be published on Grafana.com (even if the plugin itself is open source).

Let me know if you're interested in a subscription for commercial plugin and I'll have our team reach out to you with more details.

**Comment by svernick** [comment]
Hi Marcus,

Akamai is a large corporation and sometimes moves slowly…

Right now, we are trying to find out whether Akamai has a paid subscription under someone else’s name.

Are you able to determine that from your side?

Thank you very much.

/Steve

**Comment by svernick** [comment]
We do not think that Akamai has an existing paid subscription.

We don’t want to use Grafana Cloud.  We just want to put our plugin on your Web site.

What does that cost?

Thanks!

/Steve

From: "Vernick, Steve" ***@***.***>
Date: Wednesday, March 10, 2021 at 9:07 AM
To: grafana/grafana-plugin-repository ***@***.***>, Marcus Olsson ***@***.***>
Subject: Re: [grafana/grafana-plugin-repository] akamai-edgedns-datasource v1.0.0 (#894)

Hi Marcus,

Akamai is a large corporation and sometimes moves slowly…

Right now, we are trying to find out whether Akamai has a paid subscription under someone else’s name.

Are you able to determine that from your side?

Thank you very much.

/Steve


From: Marcus Olsson ***@***.***>
Reply-To: grafana/grafana-plugin-repository ***@***.***>
Date: Tuesday, March 9, 2021 at 9:03 AM
To: grafana/grafana-plugin-repository ***@***.***>
Cc: "Vernick, Steve" ***@***.***>, Mention ***@***.***>
Subject: Re: [grafana/grafana-plugin-repository] akamai-edgedns-datasource v1.0.0 (#894)


Hi @svernick<https://urldefense.com/v3/__https:/github.com/svernick__;!!GjvTz_vk!FJlzT6kkAl2ijC7CljKq5n_qvzstKHJQIdPRMGLa4twuMk9NeZlA_AFnXucx2Uw$>,

It seems to me that this is a plugin for a commercial offering from Akamai. Plugins for commercial products require a paid subscription to be published on Grafana.com (even if the plugin itself is open source).

Let me know if you're interested in a subscription for commercial plugin and I'll have our team reach out to you with more details.

**Comment by marcusolsson** [comment]
Closing this as it seems like there hasn't been any activity on this submission in a while.

If you'd like to submit the plugin again, I'd like to invite you to use our new submission flow inside Grafana Cloud. For more information and instructions, check out the [README](https://github.com/grafana/grafana-plugin-repository).

**Pull request closed without merging**
