### PR TITLE
Update Akumuli datasource

### PR DESCRIPTION
**Pull request by Lazin**
Bugfix release

### CODE REVIEW

**Comment by Lazin** [comment]
This Akumuli instance can be used to test plugin - 206.189.27.155

**Comment by daniellee** [comment]
The version number in the PR does not match the version number in the [plugin.json file in dist](https://github.com/akumuli/akumuli-datasource/blob/master/dist/plugin.json#L11). If you can fix that then I can publish the update. Thanks!

**Comment by Lazin** [comment]
Thanks @daniellee 
I fixed the problem with plugin.json file.

**Comment by torkelo** [comment]
published!

**Pull request merged**
