### PR TITLE
Update vertamedia-clickhouse-datasource

### PR DESCRIPTION
**Pull request by hagen1778**
Hi! We've updated plugin with additional examples in README, syntax highlighting and other

### CODE REVIEW

**Comment by daniellee** [comment]
Two things to fix:

- Update the [version in the plugin.json](https://github.com/Vertamedia/clickhouse-grafana/blob/master/plugin.json#L27) to be 0.0.2 so that it matches the version number in this PR. 
- In the PR, rather than replacing 0.0.1, add 0.0.2 (like [this](https://github.com/grafana/grafana-plugin-repository/blob/master/repo.json#L7-L18)) to the version list.

Thanks!

**Comment by hagen1778** [comment]
Thanks!

**Comment by daniellee** [comment]
Published and merged. Love the changes in the readme. (I really like the query editor for Clickhouse but I think I said that before).

**Comment by hagen1778** [comment]
@daniellee Thank you for the kind words!

**Pull request merged**
