### PR TITLE
add netsage-slopegraph-panel

### PR DESCRIPTION
**Pull request by KatrinaTurner**
Submitting another plugin for review! :) 
I ran it through the validator and it just says it isn't signed, but I can't sign it publicly yet?  I tried creating a new API Key with a PluginPublisher role for it, but it still asks me for a root URL like I'm signing it publicly.  I'm guessing this will get fixed after you folks have reviewed it.

### CODE REVIEW

**Comment by marcusolsson** [comment]
Wonderful! 🎉 

You're right. We'll assign a signature level for the plugin once the plugin has passed the initial review. Please submit the unsigned plugin for now.

Unfortunately, I can't seem to download the plugin for review through this URL:

https://github.com/netsage-project/netsage-slopegraph-panel/releases/download/v1.0.0/netsage-slopegraph-panel-1.0.0.zip

Could you check to make sure the asset is available?

**Comment by KatrinaTurner** [comment]
So sorry!  The release was still sitting in my drafts.  The link should work now!  Thank you :)

**Comment by marcusolsson** [comment]
Thanks! I'll move you along to the review queue!

Meanwhile, I noticed that plugin.json seems to have a broken link:

https://github.com/katrinaturner/netsage-slope-graph-panel/master/LICENSE

**Comment by KatrinaTurner** [comment]
Hi @marcusolsson just wondering about the status of this plugin review?
Thanks!

**Comment by marcusolsson** [comment]
Hi @KatrinaTurner,

Could you submit this using the new submission process from your Grafana Cloud account? More information is available in the README for this repository.

**Pull request closed without merging**
