### PR TITLE
Add Redis Datasource v1.1.0

### PR DESCRIPTION
**Pull request by mikhailredis**
Please review and let me know if you have any questions.

- Initial release based on Grafana 7.0.5.
- Allows configuring password, TLS, and advanced settings.
- Supports Redis commands: CLIENT LIST, GET, HGET, HGETALL, HKEYS, HLEN, INFO, LLEN, SCARD, SLOWLOG GET, SMEMBERS, TTL, TYPE, XLEN.
- Supports RedisTimeSeries commands: TS.MRANGE, TS.RANGE.
- Provides Redis monitoring dashboard.

### CODE REVIEW

**Comment by mikhailredis** [comment]
It's been 7 days since the data source was submitted.
Please let me know when it can be added.

**Comment by ryantxu** [comment]
What is the relationship between `redistimeseries` and `redis`?

Is the datasource normal redis?  published by the company redis?  if so, I think this should be `redis-database`

Also note -- I am super excited about some upcoming streaming/event driven APIs where redis is a perfect fit

**Comment by mikhailredis** [comment]
Thank you @briangann and @ryantxu for the review. @ryantxu already submitted a pull request to add dashboard and I will do it today with dependencies update.

@ryantxu, I am working at Redis Labs, the company behind Redis. We started this data source development to support RedisTimeSeries module and then extended to support multiple Redis data types (hashes, lists, sets and so on). According to Review Guidelines (https://grafana.com/docs/grafana/latest/developers/plugins/legacy/review-guidelines/), name `redis-datasource` is valid.

Should I rename it as `redis-database-datasource` or what is the best name to use?

**Comment by mikhailredis** [comment]
@ryantxu Where I can learn more about "upcoming streaming/event driven APIs"? I was planning to implement streaming using Redis Stream in the coming weeks.

**Comment by ryantxu** [comment]
@mikhailredis -- do you have time for a quick chat this aftenoon?  email me `ryan @ grafana`

New streaming stuff it a total WIP, but will be based on including https://github.com/centrifugal/centrifuge in grafana core
https://github.com/grafana/grafana/pull/26537

**Comment by ryantxu** [comment]
@briangann -- We added @mikhailredis to the redis org, and this should be published in the redis org and works with any redis instance.  He is working on a few tweaks and will update soon for 1.1.0

**Comment by mikhailredis** [comment]
Hello @briangann, @ryantxu version 1.1.0 submitted, please review and let me know if I need to do anything else.

##  Added features

 * Updated to [Grafana 7.1.0](https://github.com/grafana/grafana/releases/tag/v7.1.0) and the latest version of Radix #27
 * Add dashboard as a part of datasource #25 
 * Add Field config units to the response #26

**Comment by mikhailredis** [comment]
@briangann Any update with the review. Thank you.

**Comment by briangann** [comment]
taking a look now

**Comment by briangann** [comment]
merged and published

**Pull request merged**
