### PR TITLE
Adding untu-saymon-datasource plugin.

### PR DESCRIPTION
**Pull request by weekens**
To test the plugin, please follow the instructions in README.md, using the following plug-in settings:

URL: https://saas.saymon.info
Login: guest
Password: guestujcnm

Test object ID: 2274
Test metic name: body.main.temp

### CODE REVIEW

**Comment by weekens** [comment]
Fixed points 1 and 2.

For point 3, we're not really a SAAS provider. We have one public installation, which we call SAAS, but we have many other installations, all of which are on-premise.

**Comment by alexanderzobnin** [comment]
@weekens is saymon a paid service or it's an open source? Commercial plugins require a plugin subscription to be published. See [terms](https://grafana.com/terms) for details.

**Comment by weekens** [comment]
@alexanderzobnin , yes, SAYMON is a commercial software. Didn't know about plugin subscription, thanks for pointing out! I'll discuss this with management. Let's take a pause for now.

**Comment by alexanderzobnin** [comment]
@weekens yea, sure.

**Comment by daniellee** [comment]
@weekens as this is a plugin for a commercial service, you need to purchase a plugin subscription to be published. See terms here: https://grafana.com/terms/

Closing this PR as it has been open for a long time and you haven't purchased a subscription but let me know if I should you put you in contact with anyone from our commercial team.

**Pull request closed without merging**
