### PR TITLE
opennms-helm plugin v3.0.1

### PR DESCRIPTION
**Pull request by RangerRick**
This PR adds the latest OpenNMS Helm plugin to the plugin repository.  It contains quite a few feature enhancements but the structure and basic usage of the data sources remains largely the same compared to 2.0.

### CODE REVIEW

**Comment by daniellee** [comment]
There are a lot of items in the changelog! Mostly looks fine except for this issue:

This line is throwing an error when loading the dashboard in Grafana 6.0: https://github.com/OpenNMS/opennms-helm/blob/develop/src/panels/alarm-histogram/ctrl.js#L115

If the ctrl has not fully loaded and I don't have a row and then the last part of the condition can throw an exception: `this.ctrl.row.height`

```
TypeError: Cannot read property 'height' of undefined
    at AlarmHistogramCtrl.onRender (ctrl.js:115)
    at EventEmitter.emit (index.js:150)
    at Emitter../public/app/core/utils/emitter.ts.Emitter.emit (emitter.ts:11)
    at AlarmHistogramCtrl../public/app/features/panel/panel_ctrl.ts.PanelCtrl.render (panel_ctrl.ts:209)
    at AlarmHistogramCtrl.onDataError (ctrl.js:106)
    at EventEmitter.emit (index.js:129)
    at Emitter../public/app/core/utils/emitter.ts.Emitter.emit (emitter.ts:11)
    at metrics_panel_ctrl.ts:108
    at processQueue (angular.js:17051)
    at angular.js:17095 "Possibly unhandled rejection: {}"
```

**Comment by RangerRick** [comment]
OK.  So in that case should I short-circuit render and let it get called again in the future? Since Grafana 6 isn't out yet and we've got a batch of new features being worked on for the next iteration, I wasn't planning on looking into compat with it until the next Helm release.

**Comment by RangerRick** [comment]
Also, I can't find documentation for the allowed formats of `grafanaVersion` in `plugin.json`... is it normal npm-style semantic versioning stuff?  If I fix grafana 6 support, should I set it to `>=5.0.0`?

**Comment by alexanderzobnin** [comment]
@RangerRick we have no strong rules right now for `grafanaVersion` field. It looks like "minimum Grafana version required for plugin", so `5.0.0` should work.

**Comment by alexanderzobnin** [comment]
@RangerRick could you also update plugin id in `repo.json` to match proper plugin id in `plugin.json` (opennms-helm-app)?

**Comment by RangerRick** [comment]
Alright, we've got a new release that's been tested on Grafana 6 and has some other bugfixes.  I've updated this PR to reflect that version, and also to fix the plugin ID.

**Comment by mfuhrmann** [comment]
I'm really looking forward for HELM 3. It provides a lot of new features. :+1:

**Comment by chrismarkovic** [comment]
@mfuhrmann Absolutely. It curious why it takes so long for a pull to be processed. Super keen on this one.

**Comment by mfuhrmann** [comment]
@chrismarkovic Good things take time to ripen :-)

**Comment by indigo423** [comment]
yepp can't wait to see it online :)

**Comment by RangerRick** [comment]
@daniellee @alexanderzobnin anything else you need from me to merge this?

Thanks!

**Comment by Scifire** [comment]
any news on this? waiting for a new feature for production ;)

**Comment by daniellee** [comment]
@RangerRick Really sorry for the delay. Totally my fault. Merged and published now.

I got a question about a potential bug in the OpenNms app that I was intending to investigate but never got around to. 

We have a customer that claims: [snmpIfAlias](https://wiki.opennms.org/wiki/Filters) (from versions 1.6.6 and 1.7.4) doesn't work.

```
“resourceId”: “nodeSource[PRJU_Network_SR:prju1dc649-gwan1-rtr].interfaceSnmp[Gi0_2-f40f1b872d02]“,
```

Would you know anything about this?

**Comment by RangerRick** [comment]
I'm not familiar with that particular functionality offhand but it could be something on the Helm or the OpenNMS side.  If they could open an issue at https://issues.opennms.org/projects/HELM we can give it a look.

**Pull request merged**
