### PR TITLE
add google calendar annotation datasource

### PR DESCRIPTION
**Pull request by mtanda**
This is a datasource, annotate schedule to graph.
Use case: annotation new feature release date, campaign date, or something

I'm not sure such strange data source plugin is acceptable for grafana.net.
If it is acceptable, I'll prepare screenshot and README.

### CODE REVIEW

**Comment by DanCech** [comment]
This looks great @mtanda , it does look like https://github.com/mtanda/grafana-google-calendar-datasource/blob/master/src/plugin.json#L7 needs to be updated

**Comment by mtanda** [comment]
Oops, thanks for pointing out the mistake!

Okay, I'll prepare for registering plugin.

**Comment by mtanda** [comment]
I add README and snapshot. Please check it!

**Comment by daniellee** [comment]
Thanks @mtanda I'll review it on Monday. Have a great weekend!

**Comment by mtanda** [comment]
Thanks!!

**Comment by Dieterbe** [comment]
this is really great. for marketing events, etc, to see them on your graph, so you can correlate changing metric data to such important events. thanks Mitsuhiro Tanda.

**Comment by daniellee** [comment]
@mtanda Yes, this is a plugin that we will publish!

All the meta data looks fine - the plugin.json and README.md are good to merge.

I couldn't get it to sign me in from my local grafana. I followed the quickstart guide and ran the quickstart.html with the python webserver and everything worked but it is not working for me in the plugin. What should I have here:

image

and here:

image

I have 2 questions about the data source config page: 

- what should go in the url field? Is it just a dummy field?
- Is it possible to test the data source and the authentication rather just returning true [here](https://github.com/mtanda/grafana-google-calendar-datasource/blob/master/src/datasource.js#L19)?

**Comment by mtanda** [comment]
@daniellee 

Sorry, you don't need to follow all step.
Only follow step 1 and then get client id.

> what should go in the url field? Is it just a dummy field?

Yes, it is dummy. I forgot to remove the section. I fixed.

> Is it possible to test the data source and the authentication rather just returning true here?

Try to fix it by calling `gapi.client.init()`. If the client id is invalid, the API call might fail.

**Comment by daniellee** [comment]
@mtanda getting this error:

`gapi.auth2 has been initialized with different options. Consider calling gapi.auth2.getAuthInstance() instead of gapi.auth2.init().`

With this stacktrace:

`"gapi.auth2.ExternallyVisibleError
    at new uO (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.ja.m7gP1Ua4Oyo.O/m=auth2,client/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCNywxnpE8_QHM-CiX1LG3Re6g05Yw/cb=gapi.loaded_0:154:25)
    at Object._.hN [as init] (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.ja.m7gP1Ua4Oyo.O/m=auth2,client/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCNywxnpE8_QHM-CiX1LG3Re6g05Yw/cb=gapi.loaded_0:178:77)
    at https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.ja.m7gP1Ua4Oyo.O/m=auth2,client/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCNywxnpE8_QHM-CiX1LG3Re6g05Yw/cb=gapi.loaded_0:707:247
    at Y (http://localhost:3000/public/plugins/mtanda-google-calendar-datasource/libs/api.js?bust=1489579716678:220:31)
    at Z (http://localhost:3000/public/plugins/mtanda-google-calendar-datasource/libs/api.js?bust=1489579716678:179:18)
    at eval (http://localhost:3000/public/plugins/mtanda-google-calendar-datasource/libs/api.js?bust=1489579716678:239:20)
    at X (http://localhost:3000/public/plugins/mtanda-google-calendar-datasource/libs/api.js?bust=1489579716678:233:20)
    at Object.x.load (http://localhost:3000/public/plugins/mtanda-google-calendar-datasource/libs/api.js?bust=1489579716678:238:18)
    at https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.ja.m7gP1Ua4Oyo.O/m=auth2,client/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCNywxnpE8_QHM-CiX1LG3Re6g05Yw/cb=gapi.loaded_0:707:203
    at new _.C (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.ja.m7gP1Ua4Oyo.O/m=auth2,client/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCNywxnpE8_QHM-CiX1LG3Re6g05Yw/cb=gapi.loaded_0:75:299)"`

**Comment by mtanda** [comment]
I try to replicate that by adding new datasource and new panel, new annotation.
But I can't replicate it in Chrome and Firefox.

I'll check it later. If you remember your actual step to test the plugin, please share me :-)

**Comment by daniellee** [comment]
Aha, figured out what the problem was. Chrome blocked the pop up that was asking for authentication and I did not see it.

image

I just got rate limited for trying to sign in too many times. Will try again later:

```json
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceededUnreg",
    "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
    "extendedHelp": "https://code.google.com/apis/console"
   }
  ],
  "code": 403,
  "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
 }
}
```

**Comment by daniellee** [comment]
Hmm, actually the daily limit problem does not exist if I use the quickstart.html code from here:

https://developers.google.com/google-apps/calendar/quickstart/js

image

**Comment by mtanda** [comment]
> Chrome blocked the pop up that was asking for authentication and I did not see it.

I need to write about the pop-up in README!

If you accept this dialog question, it should work.
google_calendar_req_permission

But, I may miss something, I'll check it.

**Comment by daniellee** [comment]
I did accept the dialog but still getting that error about rate limiting and being unauthenticated: `Daily Limit for Unauthenticated Use Exceeded`. The quickstart code which is really similar to the code in plugin works.

**Comment by mtanda** [comment]
@daniellee Finally, I success to replicate the issue.
And, I notice that I need to update `api.js` which is provided at `https://apis.google.com/js/api.js`, and I copy it to plugin repository. (I tried to load the `api.js` from plugin, but it is hard, I give up...)

https://github.com/mtanda/grafana-google-calendar-datasource/commit/a796729cc71e7a58b290b44623f6d5f7909cbe36

Now, this plugin works again.

**Comment by daniellee** [comment]
Great persistence! Thanks for making time for it. I will test again tomorrow morning.

**Comment by daniellee** [comment]
Works great now!

Merged manually(dc31679772f2a886fdfac70e3d4dc000589a526b) and published: https://grafana.com/plugins/mtanda-google-calendar-datasource

**Comment by mtanda** [comment]
Thanks!!

**Pull request closed without merging**
