### PR TITLE
Releasing Grafana Druid Plugin 0.0.3 & 0.0.4

### PR DESCRIPTION
**Pull request by abhisant**
Release Notes:
Plugin Version 0.0.3:

- Added plugin build scripts:
- Fixed a bug: (Can't add approxHistogramFold to Aggregators #2
)https://github.com/grafana-druid-plugin/druidplugin/issues/2

Plugin Version 0.0.4:
- Added support for Grafana-4-x-x
- Fixed bug: (error on Timeseries with Grafana 4.1.2 #8
) https://github.com/grafana-druid-plugin/druidplugin/issues/8

### CODE REVIEW

**Comment by daniellee** [comment]
The version is taken from the plugin.json file (in the dist folder) and it is still at version 0.0.2 for both of those commits. Can you amend those commits, update the version and send me the new commit SHA's? The commits do not have to be in the master branch.

**Comment by abhisant** [comment]
Done.

**Comment by abhisant** [comment]
@daniellee : Did you get a change to review this. Thank you in advance.

**Comment by DanCech** [comment]
Sorry for the delay, the new versions are published :)

**Comment by abhisant** [comment]
Thank you so much @DanCech 👍 .. You guys are already multitasking with thousands of contributors. No need to be sorry. Grafana rocks 👍

**Comment by knepperjm** [comment]
Hey, Abhisant - what role / endpoint do we point the url at?

Coordinator?  Broker?  Thanks!

**Comment by abhisant** [comment]
It has to be a Broker (the one with the port 8082).

**Comment by knepperjm** [comment]
Thanks, @abhisant I'm getting an "unknown error" when I use the following URL that is routing 8082 to 8082 on the server:

http://druid-broker-external.demandbase.com:8082

**Comment by abhisant** [comment]
Can you try firing some rest API queries through postman ?
/druid/v2/datasources

**Comment by knepperjm** [comment]
Yeah, I get this response: 

[
"ip_queries_daily_v4",
"advertising_metric_aggregates"
]

Which is solid

**Comment by knepperjm** [comment]
Should my druid broker url include the REST path you described?

**Comment by abhisant** [comment]
No it shouldn't include it. 
When you add the datasource, it will fire similar query. Can you see in the Chrome developer tools -> Network tab, which query is getting fired after you add the datasource and you can compare it to the query you fired from the postman.
One more thing you might check for is, whether the druid instance is accessible form the environment you are using Grafana.

**Comment by knepperjm** [comment]
So it looks like I get a 200, but the "unknown error" still appears?  Thanks for helping, by the way! - any thoughts on this one?

**Comment by knepperjm** [comment]
Request URL:http://druid-broker-external.demandbase.com:8082/druid/v2/datasources
Request Method:GET
Status Code:200 OK

**Comment by knepperjm** [comment]
I figured it out I was using direct and not proxy, and it was behind a load balancer.  Thanks @abhisant

**Comment by abhisant** [comment]
Okay cool.

**Pull request merged**
