### PR TITLE
Adding new datasource plugin for OSIsoft PI System

### PR DESCRIPTION
**Pull request by ritchiecarroll**

### CODE REVIEW

**Comment by ritchiecarroll** [comment]
I saw on Hawkular PR that you needed non-relative paths in readme so that images would show up properly on Grafana web site. I have updated this PR to correct this.

**Comment by daniellee** [comment]
Hi @ritchiecarroll 

The readme looks great so no problems there.

I noticed that the [info toggles at the bottom of the query editor (in the query.options.html file)](https://github.com/GridProtectionAlliance/osisoftpi-grafana/blob/master/src/partials/query.options.html#L20), don't seem to have any content. I get a JavaScript error when I click on them and I can't see any content for them in the code.

Here is an [example](https://github.com/grafana/grafana/blob/05d43999dc83c2adc5bda27eb8e41e0b762c35ea/public/app/plugins/datasource/influxdb/partials/query.options.html#L43) of Info toggles in the Graphite query editor.

The query editor looks very advanced but I had no way of testing it. Do you know if there are any Docker containers or Virtual Box images for the PI System?

Otherwise, it looks solid. If you can fix the info toggles, then I can publish it. Great work again on making your second plugin!

**Comment by ritchiecarroll** [comment]
OK - Jeff has updated this, let us know if this is working better. Thanks!

**Comment by EEParker** [comment]
Thanks! I have updated the data source to include the quick help texts. As for testing, I believe OSIsoft does offer a virtual environment for students, university staff and licensees of their software. https://learning.osisoft.com/Labs/LabInformation/

**Comment by daniellee** [comment]
Published: https://grafana.net/plugins/gridprotectionalliance-osisoftpi-datasource

Nice work with the info toggles and links to the documentation.

**Pull request merged**
