### PR TITLE
Update fifemon-graphql-datasource to v1.2.0

### PR DESCRIPTION
**Pull request by retzkek**
Minor changes from v1.1.3, but an important bug fix:

* **improvement** Use templateSrv to interpolate timeFrom and timeTo variables.
* **bug fix** Fix error in isRFC3339_ISO6801 when field is non-string

### CODE REVIEW

**Comment by marcusolsson** [comment]
Thank you for your patience while waiting for us to review your plugin. 

We're working hard at improving the plugin experience for both users and authors. I'd like to share some important information on how to package and publish plugins going forward.

Since Grafana 7.3, we require all plugins to be _signed_. By signing your plugin, users can guarantee the integrity of the plugin and that the plugin version they've installed hasn't been modified since it was released. For more information on how to sign your plugin, refer to [Sign a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/).

With this, we now require plugins to be _packaged_ before we publish them. This means that instead of a commit containing a `dist` directory, you will need to submit a link to a ZIP archive containing your plugin. For more information on how to package your plugin, refer to [Package a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/).

Once you've packaged your plugin, you'll need to update your entry to `repo.json` to the new format. You can read more on how to do this under [Add a plugin to repo.json](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson).

To summarize, to publish your plugin, make sure that you:

1. [Sign your plugin](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/)
2. [Package your plugin](https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/)
3. Create a new GitHub release and upload the packaged plugin as a release asset
4. [Update your repo.json entry](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson)

Here's an [example](https://github.com/marcusolsson/grafana-jsonapi-datasource/releases/tag/v0.6.0) of a properly packaged plugin. In the same repository, you can find a [GitHub Action](https://github.com/marcusolsson/grafana-jsonapi-datasource/blob/master/.github/workflows/main.yml) that signs, packages, and releases the plugin whenever you create a new tag.

Once you've created a GitHub release with the packaged plugin, you can right-click the release asset, copy the link, and validate it using [the plugin validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app). 

Finally, in the November [community call](https://groups.google.com/g/grafana-developers/c/ps2vzCXRDCM/m/i7uAK1u9AQAJ), I'll be walking through the steps needed to sign and package your plugin. A recording will be made available on our [YouTube account](https://www.youtube.com/playlist?list=PLDGkOdUX1Ujo0OyE5HFffHE9GJVvaVXGs), in case you can't make it.

**Comment by retzkek** [comment]
@marcusolsson thanks for the great docs and the example action. I'm hitting a problem with the plugin validator:
```
{
  "level": "error",
  "message": "Missing Grafana.com account",
  "details": "The first part of the plugin ID must be a valid Grafana.com organization or user. [Sign up on Grafana.com](https://grafana.com/signup/starter/connect-account) to claim **fifemon**."
}
```
While `fifemon` is indeed my organization:
```
) curl https://grafana.com/api/orgs/fifemon
{
  "id": 14309,
  "slug": "fifemon",
  "name": "FIFEmon",
  "url": "",
  "createdAt": "2016-04-12T22:07:19.000Z",
  "createdBy": "",
  "updatedAt": "2020-08-18T14:23:46.000Z",
  "updatedBy": "",
  "avatar": "default",
  "links": [
    {
      "rel": "self",
      "href": "/orgs/fifemon"
    },
    {
      "rel": "members",
      "href": "/orgs/fifemon/members"
    }
  ]
}
```

Looking at the code I see it's actually checking for a username first, and sure enough it says that the username is available:
```
) curl https://grafana.com/api/checkusername/fifemon
true
```

Suggestion to proceed? Is this an issue with the validator, the API, or my org?

**Comment by marcusolsson** [comment]
Hm. Gut feeling is that something's changed in the Grafana.com API. I'll check with the team responsible and get back to you.

**Comment by marcusolsson** [comment]
Yes, this is indeed a change on our side. I'll have to update the validator to use a different endpoint. For now you can ignore the error.

**Comment by marcusolsson** [comment]
FYI I've updated the plugin validator to the new endpoint. Let me know if you're still getting the error about account not existing.

**Comment by retzkek** [comment]
Thanks @marcusolsson it worked now! I've updated to new release v1.2.0, which has been signed and checked (thanks to your example workflow).

**Comment by marcusolsson** [comment]
Looks great! 👍 

I'll move this to the review queue!

**Comment by marcusolsson** [comment]
Published! 🎉

**Comment by retzkek** [comment]
Thank you @marcusolsson!

**Pull request merged**
