### PR TITLE
cognite datasource v2.1.0

### PR DESCRIPTION
**Pull request by polomani**
Hi, introducing a new v2.1.0 of the plugin.

### Changelog
* Rewrote `queryEditor` and `configEditor` GUI to React as was previously adviced by @daniellee .
* Time series (first tab) are now saved to JSON by their `externalId` where possible.
Timeseries in Cognite api has two different identifiers, `internal id` and `externalId`. `externalId` is the preferred one, so starting from now it is used whenever it's possible. Old panels that are using `internal id` can be updated on save. 
* Support for [synthetic time series alignment](https://docs.cognite.com/dev/concepts/resource_types/synthetic_timeseries.html#alignment).
* Updated CDF logo to match light/dark theme.

### Secret feature
We also added a dev feature for auth token pass through `oauthPassThru=true`. This can be activated by a special key sequence. (no need to test this on your side)
We don't expose it for everyone, since we need some more testing.
It seems to work well with AAD+our API on self-hosted instances. But we are actually wondering, how one can set up their own AAD/ADFS auth for enterprise/cloud instances? I'm not sure if this a correct place to ask, I could try support if not?

### Plugin signature
I requested a commercial signature level, waiting for the support team to answer.
Hopefully it's ok if I push it a bit later, while PR is being in review?

**Feel free to reach me if you have any troubles with testing / questions.**

### CODE REVIEW

**Comment by ethirolle** [comment]
@daniellee @marcusolsson Ivan has put in a support ticket to ask for expedited review/approval of this change:

> We would really appreciate if this can be reviewed in a couple of days (we are a bit short on time).
Daniel Lee is usually the person that reviews our PRs, so he should have the most context :)

Thanks!

**Comment by marcusolsson** [comment]
Hi @polomani,

I'll get started on reviewing this. In the meantime, could you have a look at signing and packaging the plugin (you should have received a signature level now)?

You can find more information on this here:

- [Sign a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/)
- [Package a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/)

Once your done, you can validate the plugin using the [plugin validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app) by pasting the URL to the ZIP archive containing the plugin.

**Comment by polomani** [comment]
@marcusolsson I can see now that some plugins have urls to zip files in `"download": {...}` in `repo.json`.
Is this something that I need to do as well?

**Comment by marcusolsson** [comment]
I found one issue while reviewing this version. It seems like Grafana can't find a logo. I can't seem to find the `img` directory in the [dist](https://github.com/cognitedata/cognite-grafana-datasource/tree/4b15581c0cfe87dabec94ec973ab3a456798e10e/dist) directory.

Screen Shot 2020-11-19 at 09 43 54

A _super_ minor feedback is that the gaps in the query editor seem to be inconsistent:

Screen Shot 2020-11-19 at 09 48 18

Not a blocker of course, but maybe something you could look at for the next version :)

Let me know if you run into any trouble!

**Comment by marcusolsson** [comment]
> @marcusolsson I can see now that some plugins have urls to zip files in `"download": {...}` in `repo.json`.
> Is this something that I need to do as well?

Yes, going forward, all plugin submissions need to reference a package plugin (rather than a commit on GitHub). I recently sent out the following information to all open pull requests that might be helpful:

---

Thank you for your patience while waiting for us to review your plugin. 

We're working hard at improving the plugin experience for both users and authors. I'd like to share some important information on how to package and publish plugins going forward.

Since Grafana 7.3, we require all plugins to be _signed_. By signing your plugin, users can guarantee the integrity of the plugin and that the plugin version they've installed hasn't been modified since it was released. For more information on how to sign your plugin, refer to [Sign a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/).

With this, we now require plugins to be _packaged_ before we publish them. This means that instead of a commit containing a `dist` directory, you will need to submit a link to a ZIP archive containing your plugin. For more information on how to package your plugin, refer to [Package a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/).

Once you've packaged your plugin, you'll need to update your entry to `repo.json` to the new format. You can read more on how to do this under [Add a plugin to repo.json](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson).

To summarize, to publish your plugin, make sure that you:

1. [Sign your plugin](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/)
2. [Package your plugin](https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/)
3. Create a new GitHub release and upload the packaged plugin as a release asset
4. [Update your repo.json entry](https://github.com/grafana/grafana-plugin-repository#add-a-plugin-to-repojson)

Here's an [example](https://github.com/marcusolsson/grafana-jsonapi-datasource/releases/tag/v0.6.0) of a properly packaged plugin. In the same repository, you can find a [GitHub Action](https://github.com/marcusolsson/grafana-jsonapi-datasource/blob/master/.github/workflows/main.yml) that signs, packages, and releases the plugin whenever you create a new tag.

Once you've created a GitHub release with the packaged plugin, you can right-click the release asset, copy the link, and validate it using [the plugin validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app). 

Finally, in the November [community call](https://groups.google.com/g/grafana-developers/c/ps2vzCXRDCM/m/i7uAK1u9AQAJ), I'll be walking through the steps needed to sign and package your plugin. A recording will be made available on our [YouTube account](https://www.youtube.com/playlist?list=PLDGkOdUX1Ujo0OyE5HFffHE9GJVvaVXGs), in case you can't make it.

**Comment by polomani** [comment]
@marcusolsson I pointed this to a newer commit, that contains the missing logo. Thanks for noticing this :)

**Comment by polomani** [comment]
@marcusolsson I signed the plugin, validated it and fixed the issues related to validation.
However I can see that CI choked on it for some reason.

Feel free to ping me if anything is needed.

**Comment by marcusolsson** [comment]
[Published](https://grafana.com/grafana/plugins/cognitedata-datasource/installation?version=2.1.0)! 🎉 

Screen Shot 2020-11-19 at 18 34 27

**Comment by marcusolsson** [comment]
As for the build fail, looks like we've yet to update the CI for the new plugin structure. I'll look into it. Let me know if you have any questions or issues!

**Comment by polomani** [comment]
@marcusolsson nice, thanks a lot for such a quick process! :) 💯

**Comment by polomani** [comment]
Hi @marcusolsson , we undortunately introduced a bug in one of the tabs.
Fixed here https://github.com/grafana/grafana-plugin-repository/pull/797
would be nice if you can have a look.

**Pull request merged**
