### PR TITLE
Add GraphQL datasource 

### PR DESCRIPTION
**Pull request by retzkek**
Datasource plugin that provides access to a GraphQL API for numerical timeseries
data, general/tabular data, and annotations (thanks @retrodaredevil!).

Examples using GitHub API (using user's GitHub OAuth token):
* https://grafana.kmr.me/github-demo/d/N2Xxd_3Zz/security-advisories?orgId=1
* https://grafana.kmr.me/github-demo/d/u6O_F_qWk/repository?orgId=1

Example using Deutsche Bahn public timetable API to show train arrivals:
* https://grafana.kmr.me/github-demo/d/Z-cp4bqZk/db-arrivals?orgId=1

## Configuration

URL: https://bahnql.herokuapp.com/graphql

## Table with train number and platform

Query:

```
{
  station:stationWithEvaId(evaId: 8000105) {
    timetable {
      nextArrivals {
        Time:time
        trainNumber
        platform
      }
    }
  }
}
```

Data path: `station.timetable.nextArrivals`

## Annotations

Query and datapath same as above
Title: `$field_trainNumber`
Text: `Platform $field_platform`

## Screenshot

image

### CODE REVIEW

**Comment by retzkek** [comment]
We're going to put in a breaking change to eliminate the need to include the top-level "data" in the data path. I'll update this PR once that's released.

**Comment by retzkek** [comment]
So it seems that a build of the plugin with 6.x libraries won't run under 7.0, and vice-versa, so now I have build for both, but there's no way to indicate that in the plugin repo? Not that I'm too keen on maintaining parallel builds indefinitely, but probably at least until 7.1 is out.

**Comment by marcusolsson** [comment]
Hi @retzkek! Really cool plugin!

I tested the data source and it worked as I expected it to 👍 

Before I can publish this, however, I need you to fix the errors reported by [the plugin validator](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/).  You can enter the URL to this PR, or to a specific commit.

**Comment by retzkek** [comment]
@marcusolsson ❤️ the validator! Now passing with flying colors 😄

**Comment by marcusolsson** [comment]
[Published](https://grafana.com/grafana/plugins/fifemon-graphql-datasource)! Thank you for contributing! ❤️

**Pull request merged**
